#!/usr/bin/env bash
# =============================================================================
# NFTBan v1.21.0 - HTTP Bot Guard CLI Handler
# =============================================================================
# SPDX-License-Identifier: MPL-2.0
# Purpose: CLI for HTTP Bot Guard — enable, disable, status, test
#
# meta:name="cmd_botguard"
# meta:type="cli"
# meta:header="Bot Guard CLI"
# meta:version="1.0.0"
# meta:owner="Antonios Voulvoulis <contact@nftban.com>"
# meta:homepage="https://nftban.com"
#
# meta:description="CLI handler for HTTP Bot Guard (crawler detection & protection)"
# meta:input="Command line arguments (enable, disable, status, test)"
# meta:output="Bot guard management output"
# meta:depends="bash"
#
# meta:inventory.files=""
# meta:inventory.binaries="nft"
# meta:inventory.env_vars=""
# meta:inventory.config_files="/etc/nftban/conf.d/botguard/main.conf"
# meta:inventory.systemd_units=""
# meta:inventory.network=""
# meta:inventory.privileges="root"
#
# meta:created_date="2026-03-14"
# =============================================================================

set -Eeuo pipefail

[[ -z "${NFTBAN_LIB_DIR:-}" ]] && readonly NFTBAN_LIB_DIR="/usr/lib/nftban"

# Load common CLI helpers (provides cmd_init, cmd_error, cmd_is_json_mode, etc.)
# shellcheck source=/dev/null
source "${NFTBAN_LIB_DIR}/lib/cmd_common.sh" || return 1

# Initialize CLI environment
cmd_init

# =============================================================================
# HELP TEXT
# =============================================================================

_nftban_botguard_help() {
    source "${NFTBAN_LIB_DIR}/core/nftban_output.sh" || return 1
    nftban_banner

    cat <<'HELP'

USAGE:
    nftban botguard <command> [options]

COMMANDS:
    enable              Enable HTTP Bot Guard protection
    disable             Disable HTTP Bot Guard protection
    status              Show bot guard status and statistics
    config              Show bot guard configuration
    stats               Show bot guard set statistics
    test <ip>           Test classification for a specific IP
    list [--set=NAME]   List IPs in bot guard sets
    verify <ip>         Manual FCrDNS verification for an IP
    help                Show this help message

DESCRIPTION:
    HTTP Bot Guard provides intelligent crawler detection and protection
    using a three-clock hybrid architecture:

      Clock 1 (Kernel):  nft meter marks suspect IPs per-packet
      Clock 2 (Go 60s):  Classification + FCrDNS verification loop
      Clock 3 (Shell):   Botscan batch pattern matching (10 min)

    Bot Guard is a SEPARATE module from DDoS protection. Both can run
    independently. Bot Guard adds HTTP-specific bot classification on
    top of DDoS rate limiting.

CONFIGURATION:
    /etc/nftban/conf.d/botguard/main.conf
    /etc/nftban/conf.d/botguard/main.conf.local       (user overrides)
    /etc/nftban/conf.d/botguard/allowed_crawlers.conf  (verified bots)
    /etc/nftban/conf.d/botguard/denied_crawlers.conf   (blocked bots)

EXAMPLES:
    nftban botguard enable                # Enable bot guard
    nftban botguard status                # Show current status
    nftban botguard test 1.2.3.4          # Test IP classification
    nftban botguard list --set=allow      # Show verified crawlers
    nftban botguard verify 66.249.79.1    # FCrDNS check (Googlebot)
    nftban botguard status --json         # JSON output for scripting

HELP
}

# =============================================================================
# CONFIG HELPERS
# =============================================================================

_BOTGUARD_CONF="/etc/nftban/conf.d/botguard/main.conf"
_BOTGUARD_CONF_LOCAL="/etc/nftban/conf.d/botguard/main.conf.local"

# Read a config value (local override takes precedence)
_botguard_config_get() {
    local key="$1"
    local default="${2:-}"
    local value=""

    # Check local override first
    if [[ -f "$_BOTGUARD_CONF_LOCAL" ]]; then
        value=$(grep -m1 "^${key}=" "$_BOTGUARD_CONF_LOCAL" 2>/dev/null | cut -d'=' -f2- | tr -d '"' || true)
    fi

    # Fall back to main config
    if [[ -z "$value" && -f "$_BOTGUARD_CONF" ]]; then
        value=$(grep -m1 "^${key}=" "$_BOTGUARD_CONF" 2>/dev/null | cut -d'=' -f2- | tr -d '"' || true)
    fi

    echo "${value:-$default}"
}

# Write a config value to local override
_botguard_config_set() {
    local key="$1"
    local value="$2"

    # Ensure local config exists
    if [[ ! -f "$_BOTGUARD_CONF_LOCAL" ]]; then
        mkdir -p "$(dirname "$_BOTGUARD_CONF_LOCAL")"
        cat > "$_BOTGUARD_CONF_LOCAL" <<'HEADER'
# NFTBan HTTP Bot Guard - Local Overrides
# This file overrides values from main.conf
# Generated by: nftban botguard enable/disable
HEADER
    fi

    # Update or append the key
    if grep -q "^${key}=" "$_BOTGUARD_CONF_LOCAL" 2>/dev/null; then
        sed -i "s|^${key}=.*|${key}=\"${value}\"|" "$_BOTGUARD_CONF_LOCAL"
    else
        echo "${key}=\"${value}\"" >> "$_BOTGUARD_CONF_LOCAL"
    fi
}

# =============================================================================
# COMMANDS
# =============================================================================

_nftban_botguard_enable() {
    local json_mode="${1:-false}"

    _botguard_config_set "HTTP_BOTGUARD_ENABLED" "true"

    # Apply nft fragment: create sets + rules + jump chains
    # shellcheck source=/dev/null
    source "${NFTBAN_LIB_DIR}/lib/nft_fragment.sh" || true
    if declare -f nft_fragment_enable_module &>/dev/null; then
        nft_fragment_enable_module "botguard" || {
            if [[ "$json_mode" != "true" ]]; then
                echo "WARNING: Failed to apply nft rules. Run: nftban rebuild"
            fi
        }
    fi

    # Auto-restart nftband to activate immediately
    local restart_ok="false"
    if systemctl is-active nftband &>/dev/null; then
        if systemctl restart nftband 2>/dev/null; then
            restart_ok="true"
        fi
    fi

    if [[ "$json_mode" == "true" ]]; then
        printf '{"status":"ok","message":"HTTP Bot Guard enabled","daemon_restarted":%s}\n' "$restart_ok"
    else
        echo "HTTP Bot Guard enabled."
        if [[ "$restart_ok" == "true" ]]; then
            echo "Daemon restarted — Bot Guard is now active."
        else
            echo "Note: nftband not running. Start with: systemctl start nftband"
        fi
    fi
}

_nftban_botguard_disable() {
    local json_mode="${1:-false}"

    _botguard_config_set "HTTP_BOTGUARD_ENABLED" "false"

    # Remove nft fragment: cleanup sets + rules
    # shellcheck source=/dev/null
    source "${NFTBAN_LIB_DIR}/lib/nft_fragment.sh" || true
    if declare -f nft_fragment_disable_module &>/dev/null; then
        nft_fragment_disable_module "botguard" || true
    fi

    # Auto-restart nftband to deactivate immediately
    local restart_ok="false"
    if systemctl is-active nftband &>/dev/null; then
        if systemctl restart nftband 2>/dev/null; then
            restart_ok="true"
        fi
    fi

    if [[ "$json_mode" == "true" ]]; then
        printf '{"status":"ok","message":"HTTP Bot Guard disabled","daemon_restarted":%s}\n' "$restart_ok"
    else
        echo "HTTP Bot Guard disabled."
        if [[ "$restart_ok" == "true" ]]; then
            echo "Daemon restarted — Bot Guard is now inactive."
        else
            echo "Note: nftband not running. No action needed."
        fi
    fi
}

_nftban_botguard_status() {
    local json_mode="${1:-false}"
    local enabled
    enabled=$(_botguard_config_get "HTTP_BOTGUARD_ENABLED" "false")

    local loop_interval
    loop_interval=$(_botguard_config_get "HTTP_BOT_FAST_LOOP_INTERVAL" "60")

    local pressure_interval
    pressure_interval=$(_botguard_config_get "HTTP_BOT_FAST_LOOP_PRESSURE_INTERVAL" "40")

    local suspect_rate
    suspect_rate=$(_botguard_config_get "HTTP_BOT_SUSPECT_RATE" "30/second")

    # Check if suspect sets exist
    local ipv4_suspects=0
    local ipv6_suspects=0
    if nft list set ip nftban http_bot_suspect &>/dev/null; then
        ipv4_suspects=$(nft list set ip nftban http_bot_suspect 2>/dev/null | grep -c "timeout" || echo "0")
    fi
    if nft list set ip6 nftban http_bot_suspect6 &>/dev/null; then
        ipv6_suspects=$(nft list set ip6 nftban http_bot_suspect6 2>/dev/null | grep -c "timeout" || echo "0")
    fi

    # Check daemon status via IPC
    local daemon_running="false"
    if systemctl is-active nftband &>/dev/null; then
        daemon_running="true"
    fi

    if [[ "$json_mode" == "true" ]]; then
        printf '{"enabled":%s,"daemon_running":%s,"loop_interval":%s,"pressure_interval":%s,"suspect_rate":"%s","ipv4_suspects":%s,"ipv6_suspects":%s}\n' \
            "$enabled" "$daemon_running" "$loop_interval" "$pressure_interval" \
            "$suspect_rate" "$ipv4_suspects" "$ipv6_suspects"
    else
        echo "=== HTTP Bot Guard Status ==="
        echo ""
        echo "  Enabled:            $enabled"
        echo "  Daemon running:     $daemon_running"
        echo "  Loop interval:      ${loop_interval}s (${pressure_interval}s under pressure)"
        echo "  Suspect rate:       $suspect_rate"
        echo "  IPv4 suspects:      $ipv4_suspects"
        echo "  IPv6 suspects:      $ipv6_suspects"
        echo ""
        echo "  Config:             $_BOTGUARD_CONF"
        if [[ -f "$_BOTGUARD_CONF_LOCAL" ]]; then
            echo "  Local overrides:    $_BOTGUARD_CONF_LOCAL"
        fi
    fi
}

_nftban_botguard_test() {
    local ip="${1:-}"
    local json_mode="${2:-false}"

    if [[ -z "$ip" ]]; then
        cmd_error "Usage: nftban botguard test <ip>" "$json_mode"
        return 1
    fi

    # Check if IP is in any bot guard set
    local found_in=""
    for set_name in http_bot_suspect http_bot_allow http_bot_ban http_bot_grey http_bot_emergency http_bot_pending; do
        local table="ip nftban"
        # Check if IPv6
        if [[ "$ip" == *":"* ]]; then
            table="ip6 nftban"
            set_name="${set_name}6"
        fi

        if nft list set $table "$set_name" 2>/dev/null | grep -q "$ip"; then
            found_in="$set_name"
            break
        fi
    done

    if [[ "$json_mode" == "true" ]]; then
        if [[ -n "$found_in" ]]; then
            printf '{"ip":"%s","found":true,"set":"%s"}\n' "$ip" "$found_in"
        else
            printf '{"ip":"%s","found":false,"set":null}\n' "$ip"
        fi
    else
        if [[ -n "$found_in" ]]; then
            echo "IP $ip found in set: $found_in"
        else
            echo "IP $ip not found in any bot guard set"
        fi
    fi
}

_nftban_botguard_list() {
    local set_filter="${1:-all}"
    local json_mode="${2:-false}"

    # Parse --set= argument
    case "$set_filter" in
        --set=*) set_filter="${set_filter#--set=}" ;;
    esac

    local sets
    case "$set_filter" in
        allow)     sets="http_bot_allow" ;;
        ban)       sets="http_bot_ban" ;;
        grey)      sets="http_bot_grey" ;;
        pending)   sets="http_bot_pending" ;;
        suspect)   sets="http_bot_suspect" ;;
        emergency) sets="http_bot_emergency" ;;
        all)       sets="http_bot_suspect http_bot_pending http_bot_allow http_bot_grey http_bot_ban http_bot_emergency" ;;
        *)
            cmd_error "Unknown set: $set_filter. Use: allow, ban, grey, pending, suspect, emergency, all" "$json_mode"
            return 1
            ;;
    esac

    if [[ "$json_mode" == "true" ]]; then
        printf '{"sets":['
        local first="true"
        for set_name in $sets; do
            local ipv4_output ipv6_output
            ipv4_output=$(nft list set ip nftban "$set_name" 2>/dev/null || true)
            ipv6_output=$(nft list set ip6 nftban "${set_name}6" 2>/dev/null || true)
            if [[ "$first" == "true" ]]; then first="false"; else printf ','; fi
            printf '{"name":"%s","ipv4":"%s","ipv6":"%s"}' \
                "$set_name" \
                "$(echo "$ipv4_output" | grep -c "timeout" 2>/dev/null || echo 0)" \
                "$(echo "$ipv6_output" | grep -c "timeout" 2>/dev/null || echo 0)"
        done
        printf ']}\n'
    else
        for set_name in $sets; do
            echo "=== $set_name (IPv4) ==="
            if nft list set ip nftban "$set_name" 2>/dev/null; then
                true
            else
                echo "  (set not found or empty)"
            fi
            echo ""
            echo "=== ${set_name}6 (IPv6) ==="
            if nft list set ip6 nftban "${set_name}6" 2>/dev/null; then
                true
            else
                echo "  (set not found or empty)"
            fi
            echo ""
        done
    fi
}

_nftban_botguard_verify() {
    local ip="${1:-}"
    local json_mode="${2:-false}"

    if [[ -z "$ip" ]]; then
        cmd_error "Usage: nftban botguard verify <ip>" "$json_mode"
        return 1
    fi

    # Step 1: Reverse DNS lookup
    local ptr_result hostname
    ptr_result=$(dig +short -x "$ip" 2>/dev/null || true)
    hostname=$(echo "$ptr_result" | head -1 | sed 's/\.$//')

    if [[ -z "$hostname" ]]; then
        if [[ "$json_mode" == "true" ]]; then
            printf '{"ip":"%s","status":"no_rdns","hostname":null,"forward_match":false}\n' "$ip"
        else
            echo "IP: $ip"
            echo "Status: NO REVERSE DNS"
            echo "No PTR record found"
        fi
        return 0
    fi

    # Step 2: Forward DNS confirmation
    local fwd_result fwd_match="false"
    if [[ "$ip" == *":"* ]]; then
        fwd_result=$(dig +short AAAA "$hostname" 2>/dev/null || true)
    else
        fwd_result=$(dig +short A "$hostname" 2>/dev/null || true)
    fi

    if echo "$fwd_result" | grep -qF "$ip"; then
        fwd_match="true"
    fi

    # Step 3: Check against allowed crawlers config
    local bot_name="unknown"
    local allowed_conf="/etc/nftban/conf.d/botguard/allowed_crawlers.conf"
    if [[ -f "$allowed_conf" ]]; then
        local host_lower
        host_lower=$(echo "$hostname" | tr '[:upper:]' '[:lower:]')
        while IFS='|' read -r name domains _rest; do
            [[ "$name" =~ ^# ]] && continue
            [[ -z "$name" ]] && continue
            IFS=',' read -ra domain_list <<< "$domains"
            for domain in "${domain_list[@]}"; do
                domain=$(echo "$domain" | tr -d ' ' | tr '[:upper:]' '[:lower:]')
                if [[ "$host_lower" == *".${domain}" || "$host_lower" == "$domain" ]]; then
                    bot_name="$name"
                    break 2
                fi
            done
        done < "$allowed_conf"
    fi

    local status="failed"
    if [[ "$fwd_match" == "true" && "$bot_name" != "unknown" ]]; then
        status="verified"
    elif [[ "$fwd_match" == "true" ]]; then
        status="forward_confirmed"
    fi

    if [[ "$json_mode" == "true" ]]; then
        printf '{"ip":"%s","status":"%s","hostname":"%s","forward_match":%s,"bot_name":"%s"}\n' \
            "$ip" "$status" "$hostname" "$fwd_match" "$bot_name"
    else
        echo "=== FCrDNS Verification ==="
        echo ""
        echo "  IP:               $ip"
        echo "  Reverse DNS:      $hostname"
        echo "  Forward match:    $fwd_match"
        echo "  Bot identity:     $bot_name"
        echo "  Status:           $status"
        echo ""
        if [[ "$status" == "verified" ]]; then
            echo "  Result: VERIFIED — $bot_name crawler confirmed via FCrDNS"
        elif [[ "$status" == "forward_confirmed" ]]; then
            echo "  Result: Forward DNS confirmed but hostname not in allowed list"
        else
            echo "  Result: FAILED — FCrDNS verification did not pass"
        fi
    fi
}

# =============================================================================
# CONFIG / STATS SUBCOMMANDS (v1.29.0)
# =============================================================================

_nftban_botguard_config() {
    local json_mode="${1:-false}"

    local config_file="$_BOTGUARD_CONF"
    local config_local="$_BOTGUARD_CONF_LOCAL"

    local enabled
    enabled=$(_botguard_config_get "HTTP_BOTGUARD_ENABLED" "false")
    local suspect_rate
    suspect_rate=$(_botguard_config_get "HTTP_BOT_SUSPECT_RATE" "30/second")
    local loop_interval
    loop_interval=$(_botguard_config_get "HTTP_BOT_FAST_LOOP_INTERVAL" "60")
    local pressure_interval
    pressure_interval=$(_botguard_config_get "HTTP_BOT_FAST_LOOP_PRESSURE_INTERVAL" "40")
    local batch_interval
    batch_interval=$(_botguard_config_get "HTTP_BOT_BOTSCAN_INTERVAL" "600")
    local suspect_timeout
    suspect_timeout=$(_botguard_config_get "HTTP_BOT_SUSPECT_TIMEOUT" "300")

    if [[ "$json_mode" == "true" ]]; then
        printf '{"config_file":"%s","config_local":"%s","local_exists":%s,"settings":{"enabled":%s,"suspect_rate":"%s","loop_interval":%s,"pressure_interval":%s,"batch_interval":%s,"suspect_timeout":%s}}\n' \
            "$config_file" "$config_local" \
            "$([[ -f "$config_local" ]] && echo "true" || echo "false")" \
            "$enabled" "$suspect_rate" "$loop_interval" "$pressure_interval" \
            "$batch_interval" "$suspect_timeout"
    else
        echo "Bot Guard Configuration"
        echo "======================="
        echo ""
        echo "  Config File:        $config_file"
        echo "  Override File:      $config_local"
        if [[ -f "$config_local" ]]; then
            echo "  Status:             [Override Active]"
        else
            echo "  Status:             [Using defaults]"
        fi
        echo ""
        echo "Settings:"
        echo "  Enabled:            $enabled"
        echo "  Suspect Rate:       $suspect_rate"
        echo "  Loop Interval:      ${loop_interval}s"
        echo "  Pressure Interval:  ${pressure_interval}s"
        echo "  Batch Interval:     ${batch_interval}s"
        echo "  Suspect Timeout:    ${suspect_timeout}s"
        echo ""
        echo "To override settings, create/edit: $config_local"
    fi
}

_nftban_botguard_stats() {
    local json_mode="${1:-false}"

    # Count IPs in each set
    local suspect_v4=0 suspect_v6=0
    local allow_v4=0 allow_v6=0
    local ban_v4=0 ban_v6=0
    local grey_v4=0 grey_v6=0
    local pending_v4=0 pending_v6=0
    local emergency_v4=0 emergency_v6=0

    for set_pair in \
        "http_bot_suspect:suspect_v4:suspect_v6" \
        "http_bot_allow:allow_v4:allow_v6" \
        "http_bot_ban:ban_v4:ban_v6" \
        "http_bot_grey:grey_v4:grey_v6" \
        "http_bot_pending:pending_v4:pending_v6" \
        "http_bot_emergency:emergency_v4:emergency_v6"; do

        local set_name="${set_pair%%:*}"
        local rest="${set_pair#*:}"
        local v4_var="${rest%%:*}"
        local v6_var="${rest#*:}"

        local v4_count=0 v6_count=0
        if nft list set ip nftban "$set_name" &>/dev/null; then
            v4_count=$(nft list set ip nftban "$set_name" 2>/dev/null | grep -c "timeout" || echo "0")
        fi
        if nft list set ip6 nftban "${set_name}6" &>/dev/null; then
            v6_count=$(nft list set ip6 nftban "${set_name}6" 2>/dev/null | grep -c "timeout" || echo "0")
        fi

        eval "$v4_var=$v4_count"
        eval "$v6_var=$v6_count"
    done

    local daemon_running="false"
    if systemctl is-active nftband &>/dev/null; then
        daemon_running="true"
    fi

    if [[ "$json_mode" == "true" ]]; then
        printf '{"daemon_running":%s,"sets":{"suspect":{"v4":%s,"v6":%s},"allow":{"v4":%s,"v6":%s},"ban":{"v4":%s,"v6":%s},"grey":{"v4":%s,"v6":%s},"pending":{"v4":%s,"v6":%s},"emergency":{"v4":%s,"v6":%s}}}\n' \
            "$daemon_running" \
            "$suspect_v4" "$suspect_v6" \
            "$allow_v4" "$allow_v6" \
            "$ban_v4" "$ban_v6" \
            "$grey_v4" "$grey_v6" \
            "$pending_v4" "$pending_v6" \
            "$emergency_v4" "$emergency_v6"
    else
        echo "Bot Guard Statistics"
        echo "===================="
        echo ""
        echo "  Daemon Running:   $daemon_running"
        echo ""
        printf "  %-12s  %6s  %6s\n" "Set" "IPv4" "IPv6"
        printf "  %-12s  %6s  %6s\n" "───────────" "──────" "──────"
        printf "  %-12s  %6s  %6s\n" "suspect" "$suspect_v4" "$suspect_v6"
        printf "  %-12s  %6s  %6s\n" "pending" "$pending_v4" "$pending_v6"
        printf "  %-12s  %6s  %6s\n" "allow" "$allow_v4" "$allow_v6"
        printf "  %-12s  %6s  %6s\n" "grey" "$grey_v4" "$grey_v6"
        printf "  %-12s  %6s  %6s\n" "ban" "$ban_v4" "$ban_v6"
        printf "  %-12s  %6s  %6s\n" "emergency" "$emergency_v4" "$emergency_v6"
        echo ""
    fi
}

# =============================================================================
# MAIN DISPATCH
# =============================================================================

nftban_cmd_botguard() {
    local action="${1:-help}"
    shift || true

    # Detect JSON mode
    local json_mode="false"
    for arg in "$@"; do
        if [[ "$arg" == "--json" ]]; then
            json_mode="true"
            break
        fi
    done

    case "$action" in
        enable)
            _nftban_botguard_enable "$json_mode"
            ;;
        disable)
            _nftban_botguard_disable "$json_mode"
            ;;
        status)
            _nftban_botguard_status "$json_mode"
            ;;
        config)
            _nftban_botguard_config "$json_mode"
            ;;
        stats)
            _nftban_botguard_stats "$json_mode"
            ;;
        test)
            local ip="${1:-}"
            shift || true
            _nftban_botguard_test "$ip" "$json_mode"
            ;;
        list)
            local set_arg="${1:---set=all}"
            shift || true
            _nftban_botguard_list "$set_arg" "$json_mode"
            ;;
        verify)
            local ip="${1:-}"
            shift || true
            _nftban_botguard_verify "$ip" "$json_mode"
            ;;
        help|--help|-h)
            _nftban_botguard_help
            ;;
        *)
            cmd_error "Unknown command: $action. Use: enable, disable, status, config, stats, test, list, verify, help" "$json_mode"
            return 1
            ;;
    esac
}

# =============================================================================
# EXPORT FOR MAIN CLI
# =============================================================================

export -f nftban_cmd_botguard
export -f _nftban_botguard_help
export -f _nftban_botguard_enable
export -f _nftban_botguard_disable
export -f _nftban_botguard_status
export -f _nftban_botguard_test
export -f _nftban_botguard_list
export -f _nftban_botguard_verify
export -f _nftban_botguard_config
export -f _nftban_botguard_stats
export -f _botguard_config_get
export -f _botguard_config_set

# Execute if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    nftban_cmd_botguard "$@"
fi
