#!/usr/bin/env bash
# =============================================================================
# NFTBan v1.4.0 - Zabbix Integration CLI
# =============================================================================
# SPDX-License-Identifier: MPL-2.0
# Purpose: CLI commands for Zabbix metrics integration
#
# meta:name="cmd_zabbix"
# meta:type="cli"
# meta:header="Zabbix Integration"
# meta:version="1.39.0"
# meta:owner="Antonios Voulvoulis <contact@nftban.com>"
# meta:homepage="https://nftban.com"
#
# meta:description="Manage Zabbix trapper metrics integration"
# meta:inventory.files=""
# meta:inventory.binaries="zabbix_sender(optional)"
# meta:inventory.env_vars=""
# meta:inventory.config_files="/etc/nftban/nftban.conf"
# meta:inventory.systemd_units="nftban-unified-exporter.timer"
# meta:inventory.network="10051/tcp"
# meta:inventory.privileges="root"
#
# meta:created_date="2026-01-22"
# meta:updated_date="2026-01-22"
# =============================================================================

set -Eeuo pipefail

# =============================================================================
# CONFIGURATION LOADING (standard pattern)
# =============================================================================
# Bootstrap paths (nftban.conf will make them readonly)
: "${NFTBAN_LIB_DIR:=/usr/lib/nftban}"
: "${NFTBAN_CONFIG_DIR:=/etc/nftban}"
: "${NFTBAN_SHARE_DIR:=/usr/share/nftban}"

# Load main config (sets readonly paths)
source "${NFTBAN_CONFIG_DIR}/nftban.conf" 2>/dev/null || true

# Load zabbix defaults FIRST (before user overrides)
source "${NFTBAN_CONFIG_DIR}/conf.d/zabbix.conf" 2>/dev/null || true

# Load zabbix user overrides
source "${NFTBAN_CONFIG_DIR}/conf.d/zabbix.conf.local" 2>/dev/null || true

# Load metrics config (needed to detect NFTBAN_METRICS_ENABLED correctly)
source "${NFTBAN_CONFIG_DIR}/conf.d/metrics.conf" 2>/dev/null || true
source "${NFTBAN_CONFIG_DIR}/conf.d/metrics.conf.local" 2>/dev/null || true

# Load global user overrides LAST (highest priority - written by nftban config set)
source "${NFTBAN_CONFIG_DIR}/nftban.conf.local" 2>/dev/null || true

# Set bash defaults for any unset variables
: "${NFTBAN_ZABBIX_ENABLED:=false}"
: "${NFTBAN_ZABBIX_SERVER:=}"
: "${NFTBAN_ZABBIX_PORT:=10051}"
: "${NFTBAN_ZABBIX_HOSTNAME:=auto}"
: "${NFTBAN_ZABBIX_INTERVAL:=60}"
: "${NFTBAN_ZABBIX_TLS_ENABLED:=false}"
: "${NFTBAN_ZABBIX_PSK_ENABLED:=false}"
: "${NFTBAN_ZABBIX_FIREWALL_AUTO:=true}"

# Load central config library for writing config
if [[ -f "${NFTBAN_LIB_DIR}/core/nftban_config.sh" ]]; then
    source "${NFTBAN_LIB_DIR}/core/nftban_config.sh" || return 1
fi

# Load output module for banner and styling
if [[ -f "${NFTBAN_LIB_DIR}/core/nftban_output.sh" ]]; then
    source "${NFTBAN_LIB_DIR}/core/nftban_output.sh" || return 1
fi

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

_zabbix_config_get() {
    # Get config value (variable is already loaded from .conf/.conf.local)
    # Args: $1 = key name, $2 = default value
    local key="$1"
    local default="${2:-}"
    local value="${!key:-}"
    echo "${value:-$default}"
}

_zabbix_config_set() {
    # Write config to zabbix.conf.local (module-specific for proper permissions)
    # The unified exporter runs as 'nftban' user and needs read access
    local key="$1"
    local value="$2"
    local conf_local="${NFTBAN_CONFIG_DIR}/conf.d/zabbix.conf.local"

    mkdir -p "$(dirname "$conf_local")" || return 1
    if [[ ! -f "$conf_local" ]]; then
        cat > "$conf_local" <<'EOF'
# NFTBan - Zabbix User Overrides
# Auto-generated by: nftban zabbix setup
# This file is read by nftban-unified-exporter.service (runs as nftban user)
EOF
        chown root:nftban "$conf_local" 2>/dev/null || true
        chmod 640 "$conf_local"
    fi

    if grep -qE "^${key}=" "$conf_local" 2>/dev/null; then
        sed -i "s|^${key}=.*|${key}=\"${value}\"|" "$conf_local"
    else
        echo "${key}=\"${value}\"" >> "$conf_local"
    fi

    # Update in-memory variable
    declare -g "$key"="$value"
}

_zabbix_print_header() {
    local title="$1"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  $title"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
}

_zabbix_print_success() {
    echo "✅ $1"
}

_zabbix_print_error() {
    echo "❌ $1" >&2
}

_zabbix_print_warning() {
    echo "⚠️  $1"
}

_zabbix_print_info() {
    echo "ℹ️  $1"
}

# Firewall helper: Allow outbound traffic to Zabbix server
_zabbix_firewall_allow() {
    local server="$1"
    local port="$2"

    # Resolve hostname to IP if needed
    local server_ip
    if [[ "$server" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        server_ip="$server"
    else
        server_ip=$(getent hosts "$server" 2>/dev/null | awk '{print $1}' | head -1)
        [[ -z "$server_ip" ]] && server_ip=$(host "$server" 2>/dev/null | awk '/has address/ {print $4}' | head -1) || true
    fi

    [[ -z "$server_ip" ]] && return 1

    # Check if rule already exists
    if nft list chain ${NFTBAN_TABLE_IPV4} output 2>/dev/null | grep -q "daddr $server_ip.*dport $port"; then
        return 0  # Already exists
    fi

    # Add outbound rule to nftban output chain
    # Use handle-based insertion for proper priority
    if nft add rule ${NFTBAN_TABLE_IPV4} output ip daddr "$server_ip" tcp dport "$port" accept comment \"zabbix-export\" 2>/dev/null; then
        return 0
    fi

    # Fallback: Try ip family if inet doesn't exist
    if nft add rule ip nftban output ip daddr "$server_ip" tcp dport "$port" accept comment \"zabbix-export\" 2>/dev/null; then
        return 0
    fi

    return 1
}

# Firewall helper: Remove Zabbix outbound rule
_zabbix_firewall_remove() {
    local server="$1"
    local port="$2"

    # Resolve hostname to IP
    local server_ip
    if [[ "$server" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        server_ip="$server"
    else
        server_ip=$(getent hosts "$server" 2>/dev/null | awk '{print $1}' | head -1)
    fi

    [[ -z "$server_ip" ]] && return 1

    # Find and delete rule with zabbix-export comment
    local handle
    handle=$(nft -a list chain "${NFTBAN_TABLE_IPV4}" output 2>/dev/null | grep "zabbix-export" | grep -oP 'handle \K\d+')

    if [[ -n "$handle" ]]; then
        nft delete rule "${NFTBAN_TABLE_IPV4}" output handle "$handle" 2>/dev/null && return 0
    fi

    # Try ip family
    handle=$(nft -a list chain ip nftban output 2>/dev/null | grep "zabbix-export" | grep -oP 'handle \K\d+')
    if [[ -n "$handle" ]]; then
        nft delete rule ip nftban output handle "$handle" 2>/dev/null && return 0
    fi

    return 1
}

# =============================================================================
# Command: nftban zabbix setup
# =============================================================================
_cmd_zabbix_setup() {
    local server=""
    local port="10051"
    local hostname="auto"
    local tls="false"
    local psk="false"
    local interactive="true"
    local ipv4="true"
    local ipv6="false"

    # =========================================================================
    # PREREQUISITE CHECKS
    # =========================================================================
    local prereq_warnings=""

    # Check: NFTBan installed
    if [[ ! -f "${NFTBAN_CONFIG_DIR}/nftban.conf" ]]; then
        _zabbix_print_error "NFTBan not installed or configured"
        echo "  Config not found: ${NFTBAN_CONFIG_DIR}/nftban.conf"
        echo ""
        echo "Please install NFTBan first:"
        echo "  nftban install"
        return 1
    fi

    # Check: NFTBan daemon service exists
    if ! systemctl list-unit-files nftband.service &>/dev/null 2>&1; then
        prereq_warnings+="  [WARN] NFTBan daemon (nftband.service) not found - metrics may be limited\n"
    fi

    # Check: Metrics exporter — auto-enable during setup (BEFORE wizard starts)
    local metrics_enabled="${NFTBAN_METRICS_ENABLED:-false}"
    local metrics_local="${NFTBAN_CONFIG_DIR}/conf.d/metrics.conf.local"
    local global_local="${NFTBAN_CONFIG_DIR}/nftban.conf.local"
    if [[ "$metrics_enabled" != "true" ]]; then
        echo ""
        echo "  [ACTION] Metrics collection is disabled - enabling it now..."
        # Update conf.d/metrics.conf.local (used by unified exporter)
        mkdir -p "$(dirname "$metrics_local")" 2>/dev/null || true
        if [[ -f "$metrics_local" ]] && grep -q "^NFTBAN_METRICS_ENABLED=" "$metrics_local" 2>/dev/null; then
            sed -i 's/^NFTBAN_METRICS_ENABLED=.*/NFTBAN_METRICS_ENABLED="true"/' "$metrics_local"
        else
            echo 'NFTBAN_METRICS_ENABLED="true"' >> "$metrics_local"
        fi
        chmod 640 "$metrics_local" 2>/dev/null || true
        chown root:nftban "$metrics_local" 2>/dev/null || true
        # Also update nftban.conf.local (highest priority — keeps consistent with 'nftban metrics disable')
        if [[ -f "$global_local" ]] && grep -q "^NFTBAN_METRICS_ENABLED=" "$global_local" 2>/dev/null; then
            sed -i 's/^NFTBAN_METRICS_ENABLED=.*/NFTBAN_METRICS_ENABLED="true"/' "$global_local"
        fi
        # Reload the variable so rest of setup sees it
        NFTBAN_METRICS_ENABLED="true"
        echo "  [OK] Metrics config enabled"

        # Start the unified exporter service
        if systemctl list-unit-files nftban-unified-exporter.service &>/dev/null 2>&1; then
            echo "  [ACTION] Starting NFTBan unified exporter service..."
            systemctl enable nftban-unified-exporter.service &>/dev/null || true
            systemctl start nftban-unified-exporter.service &>/dev/null || true
            if systemctl is-active --quiet nftban-unified-exporter.service 2>/dev/null; then
                echo "  [OK] NFTBan exporter service started"
            else
                echo "  [WARN] Exporter service failed to start - check: systemctl status nftban-unified-exporter"
            fi
        fi
        echo ""
    fi

    # Check: Zabbix transport - use what's available, install ncat only if nothing exists
    if command -v zabbix_sender &>/dev/null; then
        : # Best option, already installed
    elif command -v ncat &>/dev/null || command -v nc &>/dev/null; then
        : # Good enough, native protocol works
    else
        # Nothing available - install ncat (in default repos)
        echo "  [ACTION] Installing ncat for Zabbix transport..."
        local distro_id
        distro_id=$(grep "^ID=" /etc/os-release 2>/dev/null | cut -d= -f2 | tr -d '"')
        case "$distro_id" in
            debian|ubuntu) apt-get install -y ncat &>/dev/null && echo "  [OK] ncat installed" || prereq_warnings+="  [WARN] apt install ncat failed\n" ;;
            centos|rhel|rocky|almalinux|fedora) dnf install -y nmap-ncat &>/dev/null && echo "  [OK] ncat installed" || prereq_warnings+="  [WARN] dnf install nmap-ncat failed\n" ;;
            *) prereq_warnings+="  [WARN] Install ncat for Zabbix: apt/dnf install ncat\n" ;;
        esac
    fi

    # Show warnings if any
    if [[ -n "$prereq_warnings" ]]; then
        echo ""
        echo "Prerequisites:"
        echo -e "$prereq_warnings"
        echo ""
    fi

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --server)   server="$2"; shift 2 ;;
            --server=*) server="${1#*=}"; shift ;;
            --port)     port="$2"; shift 2 ;;
            --port=*)   port="${1#*=}"; shift ;;
            --hostname) hostname="$2"; shift 2 ;;
            --hostname=*) hostname="${1#*=}"; shift ;;
            --ipv4)     ipv4="true"; shift ;;
            --ipv6)     ipv6="true"; shift ;;
            --no-ipv4)  ipv4="false"; shift ;;
            --no-ipv6)  ipv6="false"; shift ;;
            --tls)      tls="true"; shift ;;
            --psk)      psk="true"; shift ;;
            --non-interactive) interactive="false"; shift ;;
            *)          shift ;;
        esac
    done

    if [[ "$interactive" == "true" && -z "$server" ]]; then
        _zabbix_print_header "NFTBan Zabbix Setup Wizard"

        echo "This wizard will configure NFTBan to push metrics to your Zabbix server."
        echo ""

        read -rp "Zabbix Server address: " server
        read -rp "Zabbix Trapper port (outbound) [10051]: " port_input
        port="${port_input:-10051}"
        read -rp "Hostname to report [auto]: " hostname_input
        hostname="${hostname_input:-auto}"

        echo ""
        echo "IP Protocol support:"
        read -rp "  Enable IPv4? [Y/n]: " ipv4_answer
        [[ "$ipv4_answer" =~ ^[Nn] ]] && ipv4="false" || ipv4="true"
        read -rp "  Enable IPv6? [y/N]: " ipv6_answer
        [[ "$ipv6_answer" =~ ^[Yy] ]] && ipv6="true"

        echo ""
        read -rp "Enable TLS encryption? [y/N]: " tls_answer
        [[ "$tls_answer" =~ ^[Yy] ]] && tls="true"

        if [[ "$tls" != "true" ]]; then
            read -rp "Enable PSK authentication? [y/N]: " psk_answer
            [[ "$psk_answer" =~ ^[Yy] ]] && psk="true" || true
        fi
    fi

    # Validate
    if [[ -z "$server" ]]; then
        _zabbix_print_error "Zabbix server address required"
        return 1
    fi

    # Auto-detect hostname if needed
    if [[ "$hostname" == "auto" ]]; then
        hostname=$(hostname -f 2>/dev/null || hostname)
    fi

    # Write config
    _zabbix_print_info "Saving configuration..."
    _zabbix_config_set "NFTBAN_ZABBIX_ENABLED" "true"
    _zabbix_config_set "NFTBAN_ZABBIX_SERVER" "$server"
    _zabbix_config_set "NFTBAN_ZABBIX_PORT" "$port"
    _zabbix_config_set "NFTBAN_ZABBIX_HOSTNAME" "$hostname"
    _zabbix_config_set "NFTBAN_ZABBIX_TLS_ENABLED" "$tls"
    _zabbix_config_set "NFTBAN_ZABBIX_PSK_ENABLED" "$psk"

    # Note: Metrics collection is enabled at the start of setup (prerequisites phase)

    # Configure firewall for outbound Zabbix traffic
    local firewall_auto
    firewall_auto=$(_zabbix_config_get "NFTBAN_ZABBIX_FIREWALL_AUTO" "true")
    if [[ "$firewall_auto" == "true" ]]; then
        _zabbix_print_info "Configuring firewall for outbound traffic to $server:$port..."

        # Default to both IPv4 and IPv6 if neither was explicitly selected
        if [[ "$ipv4" == "false" && "$ipv6" == "false" ]]; then
            ipv4="true"
            ipv6="true"
        fi

        # Check if port already exists in ports.d
        # Format is PORT/PROTO/DIR where PROTO=T(tcp)|U(udp)|B(both) and DIR=I(in)|O(out)|IO(inout)
        local port_exists=false
        local existing_file=""
        for f in "${NFTBAN_CONFIG_DIR}/ports.d"/*.conf; do
            [[ -f "$f" ]] || continue
            # Check for output (O) or inout (IO) direction
            if grep -qE "^${port}/T/(O|IO)$" "$f" 2>/dev/null; then
                port_exists=true
                existing_file="$f"
                break
            fi
        done

        if [[ "$port_exists" == "true" ]]; then
            _zabbix_print_info "Port $port/tcp output already configured in: $existing_file"
        else
            # Use nftban port add command (single point of truth)
            # Syntax: nftban port add <port> <protocol> <direction>
            # Direction: in, out, inout
            _zabbix_print_info "Adding port $port/tcp (output) via nftban port add..."

            # Use nftban port add with positional arguments
            if nftban port add "$port" tcp out 2>/dev/null; then
                _zabbix_print_success "Port $port/tcp (output) added to firewall"
            else
                # Fallback: create config directly using correct format
                local port_conf="${NFTBAN_CONFIG_DIR}/ports.d/99-zabbix.conf"
                mkdir -p "$(dirname "$port_conf")" || return 1

                cat > "$port_conf" << EOF
# =============================================================================
# NFTBan - Zabbix Server Connection (Auto-generated)
# =============================================================================
# Created: $(date '+%Y-%m-%d %H:%M:%S')
# Server:  $server
# Purpose: Allow outbound metrics push to Zabbix trapper port
# Format:  PORT/PROTO/DIR where PROTO=T(tcp)|U(udp)|B(both), DIR=I(in)|O(out)|IO(inout)
# =============================================================================

# Zabbix trapper port - OUTBOUND connection to monitoring server
# Added by: nftban zabbix setup ($(date '+%Y-%m-%d %H:%M:%S'))
${port}/T/O
EOF
                chmod 640 "$port_conf"
                chown root:nftban "$port_conf" 2>/dev/null || true
                _zabbix_print_success "Port configuration saved: $port_conf"
            fi
        fi

        # Apply runtime firewall rule (nft is live - no reload needed)
        if _zabbix_firewall_allow "$server" "$port"; then
            _zabbix_print_success "Firewall rule applied (live)"
        else
            _zabbix_print_warning "Could not apply firewall rule (manual setup may be required)"
        fi
    fi

    # Enable unified exporter timer
    _zabbix_print_info "Enabling unified exporter timer..."
    if systemctl enable --now nftban-unified-exporter.timer 2>/dev/null; then
        _zabbix_print_success "Timer enabled"
    else
        _zabbix_print_warning "Could not enable timer (run: systemctl enable --now nftban-unified-exporter.timer)"
    fi

    # Test connection
    echo ""
    _zabbix_print_info "Testing connection..."
    if _cmd_zabbix_test --quiet; then
        _zabbix_print_success "Zabbix integration configured successfully"
        echo ""
        echo "Configuration saved to: ${NFTBAN_CONFIG_DIR}/conf.d/zabbix.conf.local"
        echo ""
        echo "Next steps:"
        echo "  1. Import template: nftban zabbix template --version 6.0 --output /tmp/nftban.yaml"
        echo "  2. Link template to host in Zabbix UI"
        echo "  3. Verify: nftban zabbix status"
    else
        _zabbix_print_warning "Configuration saved but connection test failed"
        echo ""
        echo "Troubleshooting:"
        echo "  - Check server address and port"
        echo "  - Verify firewall allows port $port"
        echo "  - Ensure Zabbix server is running"
        echo "  - Run: nftban zabbix test --verbose"
    fi
}

# =============================================================================
# Command: nftban zabbix status
# =============================================================================
_cmd_zabbix_status() {
    local json="false"
    local verbose="false"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --json)    json="true"; shift ;;
            --verbose) verbose="true"; shift ;;
            *)         shift ;;
        esac
    done

    # Load config values
    local enabled server port hostname interval tls psk
    enabled=$(_zabbix_config_get "NFTBAN_ZABBIX_ENABLED" "false")
    server=$(_zabbix_config_get "NFTBAN_ZABBIX_SERVER" "")
    port=$(_zabbix_config_get "NFTBAN_ZABBIX_PORT" "10051")
    hostname=$(_zabbix_config_get "NFTBAN_ZABBIX_HOSTNAME" "auto")
    interval=$(_zabbix_config_get "NFTBAN_ZABBIX_INTERVAL" "60")
    tls=$(_zabbix_config_get "NFTBAN_ZABBIX_TLS_ENABLED" "false")
    psk=$(_zabbix_config_get "NFTBAN_ZABBIX_PSK_ENABLED" "false")

    # Get actual hostname if auto
    local actual_hostname="$hostname"
    if [[ "$hostname" == "auto" ]]; then
        actual_hostname=$(hostname -f 2>/dev/null || hostname)
    fi

    if [[ "$json" == "true" ]]; then
        cat <<EOF
{
  "enabled": $enabled,
  "server": "$server",
  "trapper_port": $port,
  "hostname": "$actual_hostname",
  "interval": $interval,
  "tls_enabled": $tls,
  "psk_enabled": $psk
}
EOF
        return 0
    fi

    _zabbix_print_header "NFTBan Zabbix Integration Status"

    echo "Configuration:"
    if [[ "$enabled" == "true" ]]; then
        echo "  Enabled:      ✅ true"
    else
        echo "  Enabled:      ❌ false"
    fi
    echo "  Server:       ${server:-not configured}"
    echo "  Hostname:     $actual_hostname"
    echo ""
    echo "Ports:"
    echo "  Trapper:      $port/tcp (outbound - push metrics to server)"
    echo ""
    echo "Options:"
    echo "  Interval:     ${interval}s"
    echo "  TLS:          $tls"
    echo "  PSK:          $psk"
    echo ""

    # Check exporter timer status
    echo "Exporter Service:"
    if systemctl is-active nftban-unified-exporter.timer &>/dev/null; then
        echo "  Timer:      ✅ Active"
        local last_run
        last_run=$(systemctl show nftban-unified-exporter.timer -p LastTriggerUSec --value 2>/dev/null || echo "n/a")
        if [[ -n "$last_run" ]] && [[ "$last_run" != "n/a" ]]; then
            echo "  Last run:   $(date -d "$last_run" '+%Y-%m-%d %H:%M:%S' 2>/dev/null || echo "$last_run")"
        fi
    elif systemctl list-unit-files nftban-unified-exporter.timer &>/dev/null 2>&1; then
        echo "  Timer:      ⚠️  Installed but not active"
        echo "              Enable with: systemctl enable --now nftban-unified-exporter.timer"
    else
        echo "  Timer:      ℹ️  Not installed (using bash fallback)"
    fi
    echo ""

    # Check zabbix_sender availability
    echo "Dependencies:"
    if command -v zabbix_sender &>/dev/null; then
        local sender_version
        sender_version=$(zabbix_sender -V 2>&1 | head -1 || echo "unknown")
        echo "  zabbix_sender: ✅ $sender_version"
    else
        echo "  zabbix_sender: ⚠️  Not installed (using native protocol)"
        echo "                 Install: apt install zabbix-sender  # or yum/dnf"
    fi
    echo ""

    # Show quick start guide if not configured
    if [[ "$enabled" != "true" ]] || [[ -z "$server" ]]; then
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "  Quick Start Guide"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "Step 1: Configure Zabbix server connection"
        echo "  nftban zabbix setup --server YOUR_ZABBIX_SERVER"
        echo ""
        echo "Step 2: Import template into Zabbix"
        echo "  # Export template file:"
        echo "  nftban zabbix template --version 7.0 --output /tmp/nftban.yaml"
        echo ""
        echo "  # In Zabbix UI: Data collection → Templates → Import"
        echo "  # Select the exported file and click Import"
        echo ""
        echo "Step 3: Link template to host"
        echo "  # In Zabbix UI: Data collection → Hosts → Your Host → Templates"
        echo "  # Link the 'NFTBan' template"
        echo ""
        echo "Step 4: Verify metrics are flowing"
        echo "  nftban zabbix test --verbose"
        echo "  nftban zabbix push"
        echo ""
        echo "For more help:"
        echo "  nftban zabbix help"
        echo "  https://nftban.com/docs/zabbix"
        echo ""
    else
        # Show operational info when configured
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "  Commands"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "  Test connection:     nftban zabbix test --verbose"
        echo "  Force push metrics:  nftban zabbix push"
        echo "  Reload config:       nftban zabbix reload"
        echo "  Export template:     nftban zabbix template --version 7.0 --output /tmp/nftban.yaml"
        echo "  View all targets:    nftban zabbix targets list"
        echo "  Full help:           nftban zabbix help"
        echo ""
    fi
}

# =============================================================================
# Command: nftban zabbix test
# =============================================================================
_cmd_zabbix_test() {
    local verbose="false"
    local dry_run="false"
    local quiet="false"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --verbose) verbose="true"; shift ;;
            --dry-run) dry_run="true"; shift ;;
            --quiet)   quiet="true"; shift ;;
            *)         shift ;;
        esac
    done

    local server port hostname
    server=$(_zabbix_config_get "NFTBAN_ZABBIX_SERVER" "")
    port=$(_zabbix_config_get "NFTBAN_ZABBIX_PORT" "10051")
    hostname=$(_zabbix_config_get "NFTBAN_ZABBIX_HOSTNAME" "auto")

    if [[ -z "$server" ]]; then
        [[ "$quiet" != "true" ]] && _zabbix_print_error "Zabbix server not configured"
        [[ "$quiet" != "true" ]] && echo "Run: nftban zabbix setup"
        return 1
    fi

    [[ "$quiet" != "true" ]] && _zabbix_print_info "Testing Zabbix connection to $server:$port..."

    # Step 1: DNS resolution
    [[ "$verbose" == "true" ]] && echo "[1/4] Resolving $server..."
    if ! host "$server" &>/dev/null && ! getent hosts "$server" &>/dev/null; then
        [[ "$quiet" != "true" ]] && _zabbix_print_error "Cannot resolve $server"
        return 1
    fi
    [[ "$verbose" == "true" ]] && echo "      ✅ OK"

    # Step 2: TCP connection
    [[ "$verbose" == "true" ]] && echo "[2/4] Connecting to $server:$port..."
    if ! timeout 5 bash -c "echo >/dev/tcp/$server/$port" 2>/dev/null; then
        [[ "$quiet" != "true" ]] && _zabbix_print_error "Cannot connect to $server:$port"
        [[ "$quiet" != "true" ]] && echo "Check: firewall, Zabbix server status, port configuration"
        return 1
    fi
    [[ "$verbose" == "true" ]] && echo "      ✅ OK"

    # Step 3: Send test metric
    if [[ "$dry_run" != "true" ]]; then
        [[ "$verbose" == "true" ]] && echo "[3/4] Sending test metric..."

        # Resolve hostname if auto
        if [[ "$hostname" == "auto" ]]; then
            hostname=$(hostname -f 2>/dev/null || hostname)
        fi

        if command -v zabbix_sender &>/dev/null; then
            local result
            result=$(zabbix_sender -z "$server" -p "$port" -s "$hostname" \
                -k "nftban.test" -o "1" 2>&1) || true

            if echo "$result" | grep -q "processed: 1"; then
                [[ "$verbose" == "true" ]] && echo "      ✅ OK (metric accepted)"
            elif echo "$result" | grep -q "failed: 0"; then
                [[ "$verbose" == "true" ]] && echo "      ⚠️  Sent (item may not exist in Zabbix)"
            else
                [[ "$quiet" != "true" ]] && _zabbix_print_warning "Test metric sent but may not be processed"
                [[ "$verbose" == "true" ]] && echo "      Response: $result" || true
            fi
        else
            [[ "$verbose" == "true" ]] && echo "      ⚠️  Skipped (zabbix_sender not installed)" || true
        fi
    else
        [[ "$verbose" == "true" ]] && echo "[3/4] Dry run - skipping metric send" || true
    fi

    [[ "$verbose" == "true" ]] && echo "[4/4] Test complete"

    [[ "$quiet" != "true" ]] && _zabbix_print_success "Zabbix connection test passed"
    return 0
}

# =============================================================================
# Command: nftban zabbix push
# =============================================================================
_cmd_zabbix_push() {
    local dry_run="false"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run) dry_run="true"; shift ;;
            *)         shift ;;
        esac
    done

    _zabbix_print_info "Forcing metric push to Zabbix..."

    # Check if configured
    local server hostname
    server=$(_zabbix_config_get "NFTBAN_ZABBIX_SERVER" "")
    hostname=$(_zabbix_config_get "NFTBAN_ZABBIX_HOSTNAME" "auto")

    if [[ -z "$server" ]]; then
        _zabbix_print_error "Zabbix not configured"
        echo "Run: nftban zabbix setup"
        return 1
    fi

    # Resolve hostname if auto
    if [[ "$hostname" == "auto" ]]; then
        hostname=$(hostname -f 2>/dev/null || hostname)
    fi

    # Use unified exporter (handles both Prometheus and Zabbix)
    local exporter="${NFTBAN_LIB_DIR}/exporters/nftban_unified_exporter.sh"

    if [[ -x "$exporter" ]]; then
        if [[ "$dry_run" == "true" ]]; then
            echo ""
            echo "Dry run - unified exporter would send to Zabbix"
            echo "Server: $server"
            echo "Hostname: $hostname"
            # Show what would be sent
            NFTBAN_ZABBIX_ENABLED=true "$exporter" --stdout 2>/dev/null | head -50
        else
            NFTBAN_ZABBIX_ENABLED=true "$exporter"
            local exit_code=$?
            if [[ $exit_code -eq 0 ]]; then
                _zabbix_print_success "Metrics pushed successfully"
            else
                _zabbix_print_error "Push failed (exit code: $exit_code)"
                return $exit_code
            fi
        fi
    else
        _zabbix_print_warning "Unified exporter not found: $exporter"
        echo "Creating basic metric push..."

        # Fallback: push basic metrics directly
        if command -v zabbix_sender &>/dev/null; then
            local port
            port=$(_zabbix_config_get "NFTBAN_ZABBIX_PORT" "10051")

            # Collect basic metrics
            local version bans_total
            version=$(cat /etc/nftban/VERSION 2>/dev/null || echo "unknown")
            bans_total=$(timeout 10s nft list set "${NFTBAN_TABLE_IPV4}" blacklist_ipv4 2>/dev/null | grep -c "elements" || true)
            bans_total=${bans_total:-0}

            echo "Sending basic metrics..."
            zabbix_sender -z "$server" -p "$port" -s "$hostname" \
                -k "nftban.version" -o "$version" \
                -k "nftban.active.count" -o "$bans_total"

            _zabbix_print_success "Basic metrics pushed"
        else
            _zabbix_print_error "zabbix_sender not installed and exporter not found"
            return 1
        fi
    fi
}

# =============================================================================
# Command: nftban zabbix template
# =============================================================================
_cmd_zabbix_template() {
    local format="xml"
    local version="5.0"
    local output=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --format)  format="$2"; shift 2 ;;
            --format=*) format="${1#*=}"; shift ;;
            --version) version="$2"; shift 2 ;;
            --version=*) version="${1#*=}"; shift ;;
            --output)  output="$2"; shift 2 ;;
            --output=*) output="${1#*=}"; shift ;;
            *)         shift ;;
        esac
    done

    local template_dir="${NFTBAN_SHARE_DIR}/templates/zabbix"
    local template_file=""

    # Determine template file based on version
    case "$version" in
        5.0|5.2|5.4)
            template_file="$template_dir/nftban_template_5x.xml"
            format="xml"  # Force XML for 5.x
            ;;
        6.0|6.2|6.4)
            if [[ "$format" == "yaml" ]]; then
                template_file="$template_dir/nftban_template_6x.yaml"
            else
                template_file="$template_dir/nftban_template_6x.xml"
            fi
            ;;
        7.0|7.2)
            # Zabbix 7.x uses template_groups instead of groups
            template_file="$template_dir/nftban_template_7x.yaml"
            format="yaml"  # 7.x only supports YAML
            ;;
        *)
            _zabbix_print_error "Unknown Zabbix version: $version"
            echo "Supported versions: 5.0, 5.2, 5.4, 6.0, 6.2, 6.4, 7.0, 7.2"
            return 1
            ;;
    esac

    if [[ ! -f "$template_file" ]]; then
        _zabbix_print_warning "Template not found: $template_file"
        echo ""
        echo "Templates will be available after HELPER-1 completes template creation."
        echo "Expected locations:"
        echo "  - $template_dir/nftban_template_5x.xml"
        echo "  - $template_dir/nftban_template_6x.yaml"
        echo ""
        echo "For now, you can:"
        echo "  1. Wait for template files to be created"
        echo "  2. Download from: https://nftban.com/downloads/zabbix/"
        return 1
    fi

    if [[ -n "$output" ]]; then
        cp "$template_file" "$output"
        _zabbix_print_success "Template exported to: $output"
        echo ""
        echo "Import this file in Zabbix UI:"
        echo "  Configuration → Templates → Import"
    else
        cat "$template_file"
    fi
}

# =============================================================================
# Command: nftban zabbix discover
# =============================================================================
_cmd_zabbix_discover() {
    local type="${1:-all}"

    case "$type" in
        modules)
            echo '{"data":['
            local first=true
            for module in login portscan ddos feeds geoban suricata; do
                local enabled="0"
                if [[ -f "${NFTBAN_CONFIG_DIR}/modules/${module}.conf" ]]; then
                    enabled="1"
                fi
                [[ "$first" != "true" ]] && echo ","
                echo "{\"{\#MODULE}\":\"$module\",\"{\#ENABLED}\":\"$enabled\"}"
                first=false
            done
            echo ']}'
            ;;
        interfaces)
            echo '{"data":['
            local first=true
            for iface in $(ip -o link show | awk -F': ' '{print $2}' | grep -v "^lo$"); do
                [[ "$first" != "true" ]] && echo ","
                echo "{\"{\#IFACE}\":\"$iface\"}"
                first=false
            done
            echo ']}'
            ;;
        countries)
            echo '{"data":['
            # Get blocked countries from geoban config
            # BUG-006 FIX: Corrected path from modules/geoban.conf to conf.d/geoban/main.conf
            if [[ -f "${NFTBAN_CONFIG_DIR}/conf.d/geoban/main.conf" ]]; then
                source "${NFTBAN_CONFIG_DIR}/conf.d/geoban/main.conf" || true
                local first=true
                # IFS-safe split: strict.sh sets IFS=$'\n\t', so space-separated vars need explicit splitting
                local _geoban_countries
                IFS=' ' read -ra _geoban_countries <<< "${NFTBAN_GEOBAN_COUNTRIES:-}"
                for country in "${_geoban_countries[@]}"; do
                    [[ "$first" != "true" ]] && echo ","
                    echo "{\"{\#COUNTRY}\":\"$country\",\"{\#BLOCKED}\":\"1\"}"
                    first=false
                done
            fi
            echo ']}'
            ;;
        feeds)
            echo '{"data":['
            local first=true
            if [[ -d "${NFTBAN_CONFIG_DIR}/feeds" ]]; then
                for feed_file in "${NFTBAN_CONFIG_DIR}/feeds"/*.conf; do
                    [[ -f "$feed_file" ]] || continue
                    local feed_name
                    feed_name=$(basename "$feed_file" .conf)
                    [[ "$first" != "true" ]] && echo ","
                    echo "{\"{\#FEED}\":\"$feed_name\",\"{\#ENABLED}\":\"1\"}"
                    first=false
                done
            fi
            echo ']}'
            ;;
        timers)
            echo '{"data":['
            local first=true
            for timer in 1h 6h 24h 7d 30d permanent; do
                [[ "$first" != "true" ]] && echo ","
                echo "{\"{\#TIMER}\":\"$timer\"}"
                first=false
            done
            echo ']}'
            ;;
        --all|all)
            echo "Available discovery types:"
            echo ""
            for t in modules interfaces countries feeds timers; do
                echo "=== $t ==="
                _cmd_zabbix_discover "$t"
                echo ""
            done
            ;;
        *)
            _zabbix_print_error "Unknown discovery type: $type"
            echo "Valid types: modules, interfaces, countries, feeds, timers, --all"
            return 1
            ;;
    esac
}

# =============================================================================
# Command: nftban zabbix targets
# =============================================================================
_cmd_zabbix_targets() {
    local action="${1:-list}"
    shift || true

    case "$action" in
        list)
            _zabbix_print_header "Zabbix Targets"
            printf "%-15s %-30s %-10s %-15s\n" "Name" "Server" "Status" "Filter"
            echo "─────────────────────────────────────────────────────────────────────"

            # Primary target
            local server port enabled
            server=$(_zabbix_config_get "NFTBAN_ZABBIX_SERVER" "")
            port=$(_zabbix_config_get "NFTBAN_ZABBIX_PORT" "10051")
            enabled=$(_zabbix_config_get "NFTBAN_ZABBIX_ENABLED" "false")

            if [[ -n "$server" ]]; then
                local status="disabled"
                [[ "$enabled" == "true" ]] && status="enabled"
                printf "%-15s %-30s %-10s %-15s\n" "primary" "${server}:${port}" "$status" "all"
            fi

            # Additional targets (multi-target support)
            local i=1
            while true; do
                local name target_server target_port target_enabled target_filter
                name=$(_zabbix_config_get "NFTBAN_ZABBIX_TARGET_${i}_NAME" "")
                [[ -z "$name" ]] && break

                target_server=$(_zabbix_config_get "NFTBAN_ZABBIX_TARGET_${i}_SERVER" "")
                target_port=$(_zabbix_config_get "NFTBAN_ZABBIX_TARGET_${i}_PORT" "10051")
                target_enabled=$(_zabbix_config_get "NFTBAN_ZABBIX_TARGET_${i}_ENABLED" "false")
                target_filter=$(_zabbix_config_get "NFTBAN_ZABBIX_TARGET_${i}_FILTER" "all")

                local status="disabled"
                [[ "$target_enabled" == "true" ]] && status="enabled"
                printf "%-15s %-30s %-10s %-15s\n" "$name" "${target_server}:${target_port}" "$status" "$target_filter"
                # v1.19.20 FIX
                ((i++)) || true
            done

            if [[ -z "$server" ]] && [[ $i -eq 1 ]]; then
                echo "No targets configured."
                echo ""
                echo "Setup primary target: nftban zabbix setup"
                echo "Add additional:       nftban zabbix targets add NAME --server HOST"
            fi
            echo ""
            ;;
        add)
            local name="$1"
            shift || { _zabbix_print_error "Target name required"; return 1; }

            # Find next available slot
            local i=1
            while [[ -n "$(_zabbix_config_get "NFTBAN_ZABBIX_TARGET_${i}_NAME" "")" ]]; do
                # v1.19.20 FIX
                ((i++)) || true
            done

            # Parse options
            local server="" port="10051" filter="all"
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    --server) server="$2"; shift 2 ;;
                    --server=*) server="${1#*=}"; shift ;;
                    --port)   port="$2"; shift 2 ;;
                    --port=*) port="${1#*=}"; shift ;;
                    --filter) filter="$2"; shift 2 ;;
                    --filter=*) filter="${1#*=}"; shift ;;
                    *)        shift ;;
                esac
            done

            [[ -z "$server" ]] && { _zabbix_print_error "--server required"; return 1; }

            _zabbix_config_set "NFTBAN_ZABBIX_TARGET_${i}_NAME" "$name"
            _zabbix_config_set "NFTBAN_ZABBIX_TARGET_${i}_SERVER" "$server"
            _zabbix_config_set "NFTBAN_ZABBIX_TARGET_${i}_PORT" "$port"
            _zabbix_config_set "NFTBAN_ZABBIX_TARGET_${i}_ENABLED" "true"
            _zabbix_config_set "NFTBAN_ZABBIX_TARGET_${i}_FILTER" "$filter"

            _zabbix_print_success "Added target: $name ($server:$port)"
            ;;
        enable|disable)
            local name="$1"
            [[ -z "$name" ]] && { _zabbix_print_error "Target name required"; return 1; }

            # Handle primary target
            if [[ "$name" == "primary" ]]; then
                local value="true"
                [[ "$action" == "disable" ]] && value="false"
                _zabbix_config_set "NFTBAN_ZABBIX_ENABLED" "$value"
                _zabbix_print_success "Primary target ${action}d"
                return 0
            fi

            # Handle additional targets
            local i=1
            while true; do
                local tname
                tname=$(_zabbix_config_get "NFTBAN_ZABBIX_TARGET_${i}_NAME" "")
                [[ -z "$tname" ]] && { _zabbix_print_error "Target not found: $name"; return 1; }

                if [[ "$tname" == "$name" ]]; then
                    local value="true"
                    [[ "$action" == "disable" ]] && value="false"
                    _zabbix_config_set "NFTBAN_ZABBIX_TARGET_${i}_ENABLED" "$value"
                    _zabbix_print_success "Target $name ${action}d"
                    return 0
                fi
                # v1.19.20 FIX
                ((i++)) || true
            done
            ;;
        remove)
            local name="$1"
            [[ -z "$name" ]] && { _zabbix_print_error "Target name required"; return 1; }

            _zabbix_print_warning "Target removal not yet implemented"
            echo "For now, disable the target: nftban zabbix targets disable $name"
            ;;
        *)
            _zabbix_print_error "Unknown action: $action"
            echo "Valid actions: list, add, enable, disable, remove"
            return 1
            ;;
    esac
}

# =============================================================================
# Command: nftban zabbix config
# =============================================================================
_cmd_zabbix_config() {
    local action="${1:-show}"
    shift || true

    case "$action" in
        show)
            _zabbix_print_header "Zabbix Configuration"
            grep -E "^NFTBAN_ZABBIX_" "${NFTBAN_CONFIG_DIR}/nftban.conf" 2>/dev/null || echo "No Zabbix configuration found"
            echo ""
            ;;
        set)
            local key="$1"
            local value="$2"
            [[ -z "$key" || -z "$value" ]] && { _zabbix_print_error "Usage: nftban zabbix config set KEY VALUE"; return 1; }

            # Prefix with NFTBAN_ZABBIX_ if not already
            [[ "$key" != NFTBAN_ZABBIX_* ]] && key="NFTBAN_ZABBIX_$key"

            _zabbix_config_set "$key" "$value"
            _zabbix_print_success "Set $key = $value"
            ;;
        enable)
            _zabbix_config_set "NFTBAN_ZABBIX_ENABLED" "true"
            _zabbix_print_success "Zabbix integration enabled"
            ;;
        disable)
            # Remove firewall rule if it was auto-configured
            local server port firewall_auto
            server=$(_zabbix_config_get "NFTBAN_ZABBIX_SERVER" "")
            port=$(_zabbix_config_get "NFTBAN_ZABBIX_PORT" "10051")
            firewall_auto=$(_zabbix_config_get "NFTBAN_ZABBIX_FIREWALL_AUTO" "true")

            if [[ "$firewall_auto" == "true" ]] && [[ -n "$server" ]]; then
                _zabbix_print_info "Removing firewall rule..."
                _zabbix_firewall_remove "$server" "$port" && _zabbix_print_success "Firewall rule removed"
            fi

            _zabbix_config_set "NFTBAN_ZABBIX_ENABLED" "false"
            _zabbix_print_success "Zabbix integration disabled"
            ;;
        *)
            _zabbix_print_error "Unknown action: $action"
            echo "Valid actions: show, set, enable, disable"
            return 1
            ;;
    esac
}

# =============================================================================
# Command: nftban zabbix reload
# =============================================================================
_cmd_zabbix_reload() {
    _zabbix_print_info "Reloading Zabbix configuration..."

    # Re-source config files to pick up changes
    source "${NFTBAN_CONFIG_DIR}/conf.d/zabbix.conf" 2>/dev/null || true
    source "${NFTBAN_CONFIG_DIR}/conf.d/zabbix.conf.local" 2>/dev/null || true

    local enabled server
    enabled=$(_zabbix_config_get "NFTBAN_ZABBIX_ENABLED" "false")
    server=$(_zabbix_config_get "NFTBAN_ZABBIX_SERVER" "")

    if [[ "$enabled" != "true" ]]; then
        _zabbix_print_warning "Zabbix integration is disabled"
        echo "Enable with: nftban zabbix config enable"
        return 0
    fi

    if [[ -z "$server" ]]; then
        _zabbix_print_error "Zabbix server not configured"
        echo "Configure with: nftban zabbix setup"
        return 1
    fi

    # Force immediate metric push with new config
    _zabbix_print_info "Pushing metrics with new configuration..."
    if _cmd_zabbix_push; then
        _zabbix_print_success "Configuration reloaded and metrics pushed"
    else
        _zabbix_print_error "Reload completed but push failed"
        return 1
    fi
}

# =============================================================================
# Command: nftban zabbix help
# =============================================================================
_cmd_zabbix_help() {
    cat <<'EOF'
NFTBan Zabbix Integration

USAGE:
    nftban zabbix <command> [options]

COMMANDS:
    setup               Interactive setup wizard
    status              Show integration status
    test                Test Zabbix connectivity
    push                Force immediate metric push
    reload              Re-read config and push metrics
    template            Export Zabbix template
    discover            Run LLD discovery
    targets             Manage multiple Zabbix targets
    config              Show/modify configuration
    help                Show this help

SETUP OPTIONS:
    --server HOST       Zabbix server address
    --port PORT         Zabbix trapper port (default: 10051)
    --hostname NAME     Hostname to report (default: auto)
    --ipv4              Enable IPv4 rules
    --ipv6              Enable IPv6 rules
    --no-ipv4           Disable IPv4 rules
    --no-ipv6           Disable IPv6 rules
    --tls               Enable TLS encryption
    --psk               Enable PSK authentication
    --non-interactive   Non-interactive mode (require --server)

STATUS OPTIONS:
    --json              Output in JSON format
    --verbose           Show detailed information

TEST OPTIONS:
    --verbose           Show step-by-step progress
    --dry-run           Don't send test metric
    --quiet             Suppress output (exit code only)

PUSH OPTIONS:
    --all               Push all metrics (including discovery)
    --dry-run           Show what would be sent

TEMPLATE OPTIONS:
    --format xml|yaml   Output format (default: xml)
    --version VER       Zabbix version (5.0, 6.0, 7.0, etc.)
    --output FILE       Save to file instead of stdout

DISCOVER TYPES:
    modules             Discover enabled modules
    interfaces          Discover network interfaces
    countries           Discover geo-blocked countries
    feeds               Discover threat feeds
    timers              Discover ban timer durations
    --all               Discover all types

TARGETS OPTIONS:
    list                List configured targets
    add NAME            Add new target (requires --server)
    enable NAME         Enable target
    disable NAME        Disable target
    remove NAME         Remove target

CONFIG OPTIONS:
    show                Show current Zabbix configuration
    set KEY VALUE       Set configuration value
    enable              Enable Zabbix integration
    disable             Disable Zabbix integration

EXAMPLES:
    # Interactive setup (prompts for all options)
    nftban zabbix setup

    # Non-interactive setup
    nftban zabbix setup --server zabbix.example.com --hostname myserver

    # Setup with custom port and IPv4+IPv6
    nftban zabbix setup --server zabbix.example.com --port 10051 --ipv4 --ipv6

    # Check status
    nftban zabbix status
    nftban zabbix status --json

    # Test connection
    nftban zabbix test --verbose

    # Export template for Zabbix 6.x
    nftban zabbix template --version 6.0 --format yaml --output /tmp/nftban.yaml

    # Run LLD discovery
    nftban zabbix discover modules
    nftban zabbix discover --all

    # Multi-target setup (DR/backup)
    nftban zabbix targets add backup --server zabbix-dr.example.com
    nftban zabbix targets list

    # Force metric push
    nftban zabbix push

    # After config change, reload immediately
    nftban zabbix reload

    # Or wait for next timer cycle (automatic)
    # Config is re-read on each exporter run

METRICS OVERVIEW:
    NFTBan exports 76 metrics to Zabbix including:
    - Daemon: status, version, uptime, pid, mode
    - Bans: active count, 24h/1h, rate, permanent, whitelist
    - Memory: RSS, file descriptors, threads, goroutines
    - Runtime: heap_mb, gc_cycles, gc_pause_ms (watchdog IPC)
    - Throughput: bans_total, unbans_total, bans_per_min
    - IPC: requests, latency_ms, errors
    - Health: status, passed, failed checks
    - Modules: enabled, active, failed
    - nftables: sets, elements, rules, packets blocked
    - Feeds: enabled, loaded, failed, total IPs
    - Network: connections (active, established, time_wait, close_wait)
    - System: load, memory%, iowait%, disk%
    - Server inventory: hostname, OS, kernel, IPs, MAC, networks
    - GeoIP: database age, countries blocked

    Architecture: Central Collector → JSON → Zabbix Protocol
    See: nftban zabbix template --version 7.0 --output /tmp/nftban.yaml

EOF
}

# =============================================================================
# Main Command Handler
# =============================================================================
nftban_cmd_zabbix() {
    local subcommand="${1:-help}"
    shift || true

    # Show banner for non-quiet commands
    if [[ "$subcommand" != "test" || ! "$*" =~ "--quiet" ]]; then
        if [[ $(type -t nftban_banner) == "function" ]]; then
            nftban_banner "zabbix"
        fi
    fi

    case "$subcommand" in
        setup)    _cmd_zabbix_setup "$@" ;;
        status)   _cmd_zabbix_status "$@" ;;
        test)     _cmd_zabbix_test "$@" ;;
        push)     _cmd_zabbix_push "$@" ;;
        reload)   _cmd_zabbix_reload "$@" ;;
        template) _cmd_zabbix_template "$@" ;;
        discover) _cmd_zabbix_discover "$@" ;;
        targets)  _cmd_zabbix_targets "$@" ;;
        config)   _cmd_zabbix_config "$@" ;;
        help|--help|-h) _cmd_zabbix_help ;;
        *)
            _zabbix_print_error "Unknown command: $subcommand"
            _cmd_zabbix_help
            return 1
            ;;
    esac
}

# Export main handler
export -f nftban_cmd_zabbix
