#!/usr/bin/env bash
# =============================================================================
# NFTBan v1.20.0 - HTTP Bot Guard CLI Handler
# =============================================================================
# SPDX-License-Identifier: MPL-2.0
# Purpose: CLI for HTTP Bot Guard — enable, disable, status, test
#
# meta:name="cmd_botguard"
# meta:type="cli"
# meta:header="Bot Guard CLI"
# meta:version="1.0.0"
# meta:owner="Antonios Voulvoulis <contact@nftban.com>"
# meta:homepage="https://nftban.com"
#
# meta:description="CLI handler for HTTP Bot Guard (crawler detection & protection)"
# meta:input="Command line arguments (enable, disable, status, test)"
# meta:output="Bot guard management output"
# meta:depends="bash"
#
# meta:inventory.files=""
# meta:inventory.binaries="nft"
# meta:inventory.env_vars=""
# meta:inventory.config_files="/etc/nftban/conf.d/botguard/main.conf"
# meta:inventory.systemd_units=""
# meta:inventory.network=""
# meta:inventory.privileges="root"
#
# meta:created_date="2026-03-14"
# =============================================================================

set -Eeuo pipefail

[[ -z "${NFTBAN_LIB_DIR:-}" ]] && readonly NFTBAN_LIB_DIR="/usr/lib/nftban"

# Load common CLI helpers (provides cmd_init, cmd_error, cmd_is_json_mode, etc.)
# shellcheck source=/dev/null
source "${NFTBAN_LIB_DIR}/lib/cmd_common.sh" || return 1

# Initialize CLI environment
cmd_init

# =============================================================================
# HELP TEXT
# =============================================================================

_nftban_botguard_help() {
    source "${NFTBAN_LIB_DIR}/core/nftban_output.sh" || return 1
    nftban_banner

    cat <<'HELP'

USAGE:
    nftban botguard <command> [options]

COMMANDS:
    enable              Enable HTTP Bot Guard protection
    disable             Disable HTTP Bot Guard protection
    status              Show bot guard status and statistics
    test <ip>           Test classification for a specific IP
    help                Show this help message

DESCRIPTION:
    HTTP Bot Guard provides intelligent crawler detection and protection
    using a three-clock hybrid architecture:

      Clock 1 (Kernel):  nft meter marks suspect IPs per-packet
      Clock 2 (Go 60s):  Classification loop reads suspects, classifies
      Clock 3 (Shell):   Botscan batch pattern matching (10 min)

    Bot Guard is a SEPARATE module from DDoS protection. Both can run
    independently. Bot Guard adds HTTP-specific bot classification on
    top of DDoS rate limiting.

CONFIGURATION:
    /etc/nftban/conf.d/botguard/main.conf
    /etc/nftban/conf.d/botguard/main.conf.local  (user overrides)

EXAMPLES:
    nftban botguard enable         # Enable bot guard
    nftban botguard status         # Show current status
    nftban botguard test 1.2.3.4   # Test IP classification
    nftban botguard status --json  # JSON output for scripting

HELP
}

# =============================================================================
# CONFIG HELPERS
# =============================================================================

_BOTGUARD_CONF="/etc/nftban/conf.d/botguard/main.conf"
_BOTGUARD_CONF_LOCAL="/etc/nftban/conf.d/botguard/main.conf.local"

# Read a config value (local override takes precedence)
_botguard_config_get() {
    local key="$1"
    local default="${2:-}"
    local value=""

    # Check local override first
    if [[ -f "$_BOTGUARD_CONF_LOCAL" ]]; then
        value=$(grep -m1 "^${key}=" "$_BOTGUARD_CONF_LOCAL" 2>/dev/null | cut -d'=' -f2- | tr -d '"' || true)
    fi

    # Fall back to main config
    if [[ -z "$value" && -f "$_BOTGUARD_CONF" ]]; then
        value=$(grep -m1 "^${key}=" "$_BOTGUARD_CONF" 2>/dev/null | cut -d'=' -f2- | tr -d '"' || true)
    fi

    echo "${value:-$default}"
}

# Write a config value to local override
_botguard_config_set() {
    local key="$1"
    local value="$2"

    # Ensure local config exists
    if [[ ! -f "$_BOTGUARD_CONF_LOCAL" ]]; then
        mkdir -p "$(dirname "$_BOTGUARD_CONF_LOCAL")"
        cat > "$_BOTGUARD_CONF_LOCAL" <<'HEADER'
# NFTBan HTTP Bot Guard - Local Overrides
# This file overrides values from main.conf
# Generated by: nftban botguard enable/disable
HEADER
    fi

    # Update or append the key
    if grep -q "^${key}=" "$_BOTGUARD_CONF_LOCAL" 2>/dev/null; then
        sed -i "s|^${key}=.*|${key}=\"${value}\"|" "$_BOTGUARD_CONF_LOCAL"
    else
        echo "${key}=\"${value}\"" >> "$_BOTGUARD_CONF_LOCAL"
    fi
}

# =============================================================================
# COMMANDS
# =============================================================================

_nftban_botguard_enable() {
    local json_mode="${1:-false}"

    _botguard_config_set "HTTP_BOTGUARD_ENABLED" "true"

    if [[ "$json_mode" == "true" ]]; then
        printf '{"status":"ok","message":"HTTP Bot Guard enabled","action":"restart_daemon"}\n'
    else
        echo "HTTP Bot Guard enabled."
        echo "Restart nftband to activate: systemctl restart nftband"
    fi
}

_nftban_botguard_disable() {
    local json_mode="${1:-false}"

    _botguard_config_set "HTTP_BOTGUARD_ENABLED" "false"

    if [[ "$json_mode" == "true" ]]; then
        printf '{"status":"ok","message":"HTTP Bot Guard disabled","action":"restart_daemon"}\n'
    else
        echo "HTTP Bot Guard disabled."
        echo "Restart nftband to deactivate: systemctl restart nftband"
    fi
}

_nftban_botguard_status() {
    local json_mode="${1:-false}"
    local enabled
    enabled=$(_botguard_config_get "HTTP_BOTGUARD_ENABLED" "false")

    local loop_interval
    loop_interval=$(_botguard_config_get "HTTP_BOT_FAST_LOOP_INTERVAL" "60")

    local pressure_interval
    pressure_interval=$(_botguard_config_get "HTTP_BOT_FAST_LOOP_PRESSURE_INTERVAL" "40")

    local suspect_rate
    suspect_rate=$(_botguard_config_get "HTTP_BOT_SUSPECT_RATE" "30/second")

    # Check if suspect sets exist
    local ipv4_suspects=0
    local ipv6_suspects=0
    if nft list set ip nftban http_bot_suspect &>/dev/null; then
        ipv4_suspects=$(nft list set ip nftban http_bot_suspect 2>/dev/null | grep -c "timeout" || echo "0")
    fi
    if nft list set ip6 nftban http_bot_suspect6 &>/dev/null; then
        ipv6_suspects=$(nft list set ip6 nftban http_bot_suspect6 2>/dev/null | grep -c "timeout" || echo "0")
    fi

    # Check daemon status via IPC
    local daemon_running="false"
    if systemctl is-active nftband &>/dev/null; then
        daemon_running="true"
    fi

    if [[ "$json_mode" == "true" ]]; then
        printf '{"enabled":%s,"daemon_running":%s,"loop_interval":%s,"pressure_interval":%s,"suspect_rate":"%s","ipv4_suspects":%s,"ipv6_suspects":%s}\n' \
            "$enabled" "$daemon_running" "$loop_interval" "$pressure_interval" \
            "$suspect_rate" "$ipv4_suspects" "$ipv6_suspects"
    else
        echo "=== HTTP Bot Guard Status ==="
        echo ""
        echo "  Enabled:            $enabled"
        echo "  Daemon running:     $daemon_running"
        echo "  Loop interval:      ${loop_interval}s (${pressure_interval}s under pressure)"
        echo "  Suspect rate:       $suspect_rate"
        echo "  IPv4 suspects:      $ipv4_suspects"
        echo "  IPv6 suspects:      $ipv6_suspects"
        echo ""
        echo "  Config:             $_BOTGUARD_CONF"
        if [[ -f "$_BOTGUARD_CONF_LOCAL" ]]; then
            echo "  Local overrides:    $_BOTGUARD_CONF_LOCAL"
        fi
    fi
}

_nftban_botguard_test() {
    local ip="${1:-}"
    local json_mode="${2:-false}"

    if [[ -z "$ip" ]]; then
        cmd_error "Usage: nftban botguard test <ip>" "$json_mode"
        return 1
    fi

    # Check if IP is in any bot guard set
    local found_in=""
    for set_name in http_bot_suspect http_bot_allow http_bot_ban http_bot_grey http_bot_emergency http_bot_pending; do
        local table="ip nftban"
        # Check if IPv6
        if [[ "$ip" == *":"* ]]; then
            table="ip6 nftban"
            set_name="${set_name}6"
        fi

        if nft list set $table "$set_name" 2>/dev/null | grep -q "$ip"; then
            found_in="$set_name"
            break
        fi
    done

    if [[ "$json_mode" == "true" ]]; then
        if [[ -n "$found_in" ]]; then
            printf '{"ip":"%s","found":true,"set":"%s"}\n' "$ip" "$found_in"
        else
            printf '{"ip":"%s","found":false,"set":null}\n' "$ip"
        fi
    else
        if [[ -n "$found_in" ]]; then
            echo "IP $ip found in set: $found_in"
        else
            echo "IP $ip not found in any bot guard set"
        fi
    fi
}

# =============================================================================
# MAIN DISPATCH
# =============================================================================

nftban_cmd_botguard() {
    local action="${1:-help}"
    shift || true

    # Detect JSON mode
    local json_mode="false"
    for arg in "$@"; do
        if [[ "$arg" == "--json" ]]; then
            json_mode="true"
            break
        fi
    done

    case "$action" in
        enable)
            _nftban_botguard_enable "$json_mode"
            ;;
        disable)
            _nftban_botguard_disable "$json_mode"
            ;;
        status)
            _nftban_botguard_status "$json_mode"
            ;;
        test)
            local ip="${1:-}"
            shift || true
            _nftban_botguard_test "$ip" "$json_mode"
            ;;
        help|--help|-h)
            _nftban_botguard_help
            ;;
        *)
            cmd_error "Unknown command: $action. Use: enable, disable, status, test, help" "$json_mode"
            return 1
            ;;
    esac
}

# =============================================================================
# EXPORT FOR MAIN CLI
# =============================================================================

export -f nftban_cmd_botguard
export -f _nftban_botguard_help
export -f _nftban_botguard_enable
export -f _nftban_botguard_disable
export -f _nftban_botguard_status
export -f _nftban_botguard_test
export -f _botguard_config_get
export -f _botguard_config_set

# Execute if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    nftban_cmd_botguard "$@"
fi
