// =============================================================================
// NFTBan - Suricata Rules Generator
// =============================================================================
// SPDX-License-Identifier: MPL-2.0
// meta:name="generator"
// meta:type="package"
// meta:version="1.0.0"
// meta:owner="Antonios Voulvoulis <contact@nftban.com>"
// meta:created_date="2025-10-26"
// meta:description="Generates enabled.list and custom.rules for Suricata"
// meta:input="Category configuration"
// meta:output="Rule files"
// meta:depends="github.com/itcmsgr/nftban/pkg/config,github.com/itcmsgr/nftban/pkg/suricata/config"
// meta:inventory.files="/var/lib/suricata/rules/*.rules"
// meta:inventory.binaries=""
// meta:inventory.env_vars=""
// meta:inventory.config_files=""
// meta:inventory.systemd_units=""
// meta:inventory.network=""
// meta:inventory.privileges="none"
// =============================================================================

package rules

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	nftbanConfig "github.com/itcmsgr/nftban/pkg/config"
	"github.com/itcmsgr/nftban/pkg/nftbanconf"
	"github.com/itcmsgr/nftban/pkg/safety"
	suricataConfig "github.com/itcmsgr/nftban/pkg/suricata/config"
	"github.com/itcmsgr/nftban/pkg/util"
)

// RulesDir contains paths to Suricata rules
type RulesDir struct {
	BaseDir     string // /var/lib/suricata/rules
	EnabledList string // /etc/nftban/suricata/rules/enabled.list
	CustomRules string // /etc/nftban/suricata/rules/custom.rules
}

// GetRulesPaths returns paths based on distro config
func GetRulesPaths() (*RulesDir, error) {
	// Get distro-specific Suricata rules directory
	distro, err := nftbanConfig.LoadDistroConfig()
	if err != nil {
		return nil, err
	}

	baseDir := distro.Paths["suricata_rules_dir"]
	if baseDir == "" {
		baseDir = "/var/lib/suricata/rules" // Fallback
	}

	// NFTBan config directory
	cfg := nftbanconf.MustLoad()
	nftbanConfigDir := filepath.Join(cfg.ConfigDir, "suricata")

	return &RulesDir{
		BaseDir:     baseDir,
		EnabledList: filepath.Join(nftbanConfigDir, "rules/enabled.list"),
		CustomRules: filepath.Join(nftbanConfigDir, "rules/custom.rules"),
	}, nil
}

// GenerateEnabledList creates enabled.list from effective config
// v1.19.21 FIX: Atomic write (GH#45) - write_temp -> validate -> mv temp final
func GenerateEnabledList() error {
	paths, err := GetRulesPaths()
	if err != nil {
		return err
	}

	configPaths, err := suricataConfig.GetConfigPaths()
	if err != nil {
		return err
	}

	// Ensure directories exist
	if err := os.MkdirAll(filepath.Dir(paths.EnabledList), 0755); err != nil {
		return fmt.Errorf("failed to create rules directory: %w", err)
	}

	// Load effective config
	effectiveConfig := suricataConfig.LoadConfig(configPaths.EffectiveConf)

	// Find all available rule files
	allRules, err := findAllRuleFiles(paths.BaseDir)
	if err != nil {
		return fmt.Errorf("failed to scan rules directory: %w", err)
	}

	// Filter rules based on enabled categories
	enabledRules := filterRulesByCategories(allRules, effectiveConfig.EnabledCategories)

	// v1.19.21 FIX: Atomic write (GH#45) - Validate rule files exist before enabling
	validatedRules := make([]string, 0, len(enabledRules))
	for _, rulePath := range enabledRules {
		if _, err := os.Stat(rulePath); err == nil {
			validatedRules = append(validatedRules, rulePath)
		} else {
			fmt.Printf("  Warning: Skipping missing rule file: %s\n", rulePath)
		}
	}
	enabledRules = validatedRules

	// Build enabled.list content
	var content strings.Builder
	content.WriteString("# NFTBan Suricata Enabled Rules List\n")
	content.WriteString(fmt.Sprintf("# Generated: %s\n", time.Now().Format(time.RFC3339)))
	content.WriteString("# DO NOT EDIT - This file is automatically generated\n")
	content.WriteString("#\n")
	content.WriteString(fmt.Sprintf("# Enabled categories: %d\n", len(effectiveConfig.EnabledCategories)))
	content.WriteString(fmt.Sprintf("# Enabled rule files: %d\n", len(enabledRules)))
	content.WriteString("#\n\n")

	// v1.19.21 FIX: Sorted rules (GH#46)
	// Sort for consistent, deterministic output - ensures stable diffs
	sort.Strings(enabledRules)

	for _, rule := range enabledRules {
		content.WriteString(rule + "\n")
	}

	// Always include custom rules if they exist
	if _, err := os.Stat(paths.CustomRules); err == nil {
		content.WriteString("\n# Custom Rules\n")
		content.WriteString(paths.CustomRules + "\n")
	}

	// v1.19.21 FIX: Atomic write (GH#45) - Use safety.SafeWriteFile for atomic write
	// Pattern: write_temp -> validate -> mv temp final (TOCTOU safe)
	if err := safety.SafeWriteFile(paths.EnabledList, []byte(content.String()), 0644); err != nil {
		return fmt.Errorf("failed to write enabled.list: %w", err)
	}

	fmt.Printf("Generated: %s\n", paths.EnabledList)
	fmt.Printf("  Enabled %d rule files from %d categories\n", len(enabledRules), len(effectiveConfig.EnabledCategories))

	return nil
}

// findAllRuleFiles scans the rules directory for .rules files
func findAllRuleFiles(rulesDir string) (map[string]string, error) {
	rules := make(map[string]string)

	// Check if directory exists
	if _, err := os.Stat(rulesDir); os.IsNotExist(err) {
		return rules, fmt.Errorf("rules directory not found: %s", rulesDir)
	}

	// Walk directory
	err := filepath.Walk(rulesDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Only process .rules files
		if !info.IsDir() && strings.HasSuffix(info.Name(), ".rules") {
			// Extract category from filename
			// Example: emerging-attack_response.rules -> emerging-attack_response
			category := strings.TrimSuffix(info.Name(), ".rules")
			rules[category] = path
		}

		return nil
	})

	if err != nil {
		return nil, err
	}

	return rules, nil
}

// filterRulesByCategories filters rule files by enabled categories
func filterRulesByCategories(allRules map[string]string, enabledCategories []string) []string {
	enabled := make([]string, 0)

	// Create map for fast lookup
	categoryMap := make(map[string]bool)
	for _, cat := range enabledCategories {
		categoryMap[cat] = true
	}

	// Filter rules
	for category, path := range allRules {
		if categoryMap[category] {
			enabled = append(enabled, path)
		}
	}

	return enabled
}

// InitializeCustomRules creates empty custom.rules if it doesn't exist
// v1.19.21 FIX: Atomic write (GH#45)
func InitializeCustomRules() error {
	paths, err := GetRulesPaths()
	if err != nil {
		return err
	}

	// Don't overwrite existing custom.rules
	if _, err := os.Stat(paths.CustomRules); err == nil {
		return nil
	}

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(paths.CustomRules), 0755); err != nil {
		return err
	}

	content := `# NFTBan Custom Suricata Rules
#
# SID Range: 9000000 - 9999999 (reserved for NFTBan custom rules)
#
# Rule Syntax:
#   alert <protocol> <source> <sport> -> <dest> <dport> (msg:"<message>"; <options>; sid:<SID>;)
#
# Examples:
#   alert http any any -> $HOME_NET any (msg:"SQL Injection Attempt"; content:"SELECT"; content:"FROM"; sid:9000001;)
#   alert tcp any any -> $HOME_NET 22 (msg:"SSH Brute Force"; threshold:type both, track by_src, count 5, seconds 60; sid:9000002;)
#
# Documentation:
#   https://suricata.readthedocs.io/en/latest/rules/
#

`

	// v1.19.21 FIX: Atomic write (GH#45) - Use safety.SafeWriteFile
	if err := safety.SafeWriteFile(paths.CustomRules, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to create custom.rules: %w", err)
	}

	fmt.Printf("Created: %s\n", paths.CustomRules)
	return nil
}

// GetRuleStats returns statistics about enabled rules
func GetRuleStats() (map[string]interface{}, error) {
	paths, err := GetRulesPaths()
	if err != nil {
		return nil, err
	}

	configPaths, err := suricataConfig.GetConfigPaths()
	if err != nil {
		return nil, err
	}

	// Load effective config
	effectiveConfig := suricataConfig.LoadConfig(configPaths.EffectiveConf)

	// Find all available rules
	allRules, err := findAllRuleFiles(paths.BaseDir)
	if err != nil {
		return nil, err
	}

	// Filter enabled rules
	enabledRules := filterRulesByCategories(allRules, effectiveConfig.EnabledCategories)

	stats := map[string]interface{}{
		"total_categories":   len(allRules),
		"enabled_categories": len(effectiveConfig.EnabledCategories),
		"enabled_rule_files": len(enabledRules),
		"custom_rules_exist": util.FileExists(paths.CustomRules),
		"enabled_list_path":  paths.EnabledList,
	}

	return stats, nil
}

