# nftban-managed: yes
# nftban-templates-version: 1
# Basic DA brute indicators; adjust to your DA log format.

[Definition]
failregex = ^.*login\sattempt\sfailed\sfor\suser\s.*\sfrom\s<HOST>.*$
            ^.*excessive\slogin\sattempts\sfrom\s<HOST>.*$
ignoreregex =
