#!/bin/bash
# Smart Fail2ban Migration to NFTBan Integration
# Preserves existing customizations, only updates banaction
#
# Author: NFTBan Project
# Date: 2025-10-30

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Files
JAIL_LOCAL="/etc/fail2ban/jail.local"
JAIL_LOCAL_BACKUP="/etc/fail2ban/jail.local.backup-$(date +%Y%m%d-%H%M%S)"
NFTBAN_ACTION="/etc/fail2ban/action.d/nftban.conf"

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}NFTBan Fail2ban Migration - Smart Update${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ═══════════════════════════════════════════════════════════════════
# Step 1: Pre-flight Checks
# ═══════════════════════════════════════════════════════════════════

echo -e "${YELLOW}[1/7] Running pre-flight checks...${NC}"

# Check if fail2ban is installed
if ! command -v fail2ban-client >/dev/null 2>&1; then
    echo -e "${RED}❌ fail2ban is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓${NC} fail2ban is installed"

# Check if NFTBan action exists
if [[ ! -f "$NFTBAN_ACTION" ]]; then
    echo -e "${RED}❌ NFTBan action not found: $NFTBAN_ACTION${NC}"
    echo -e "   Please install NFTBan first"
    exit 1
fi
echo -e "${GREEN}✓${NC} NFTBan action exists"

# Check if nftban-complete exists
if [[ ! -x "/usr/sbin/nftban-complete" ]]; then
    echo -e "${RED}❌ nftban-complete not found or not executable${NC}"
    exit 1
fi
echo -e "${GREEN}✓${NC} nftban-complete is available"

# Check if nftban_runtime table exists
if ! nft list table inet nftban_runtime &>/dev/null; then
    echo -e "${YELLOW}⚠️  nftban_runtime table not found${NC}"
    echo -e "   Creating it now..."
    if [[ -f "/usr/lib/nftban/nft-runtime.nft" ]]; then
        nft -f /usr/lib/nftban/nft-runtime.nft
        echo -e "${GREEN}✓${NC} nftban_runtime table created"
    else
        echo -e "${RED}❌ Runtime table template not found${NC}"
        exit 1
    fi
else
    echo -e "${GREEN}✓${NC} nftban_runtime table exists"
fi

echo ""

# ═══════════════════════════════════════════════════════════════════
# Step 2: Backup Current Configuration
# ═══════════════════════════════════════════════════════════════════

echo -e "${YELLOW}[2/7] Backing up current configuration...${NC}"

if [[ -f "$JAIL_LOCAL" ]]; then
    cp "$JAIL_LOCAL" "$JAIL_LOCAL_BACKUP"
    echo -e "${GREEN}✓${NC} Backup created: $JAIL_LOCAL_BACKUP"
else
    echo -e "${YELLOW}⚠️  No jail.local found (will use jail.d configs)${NC}"
fi

echo ""

# ═══════════════════════════════════════════════════════════════════
# Step 3: Analyze Current Configuration
# ═══════════════════════════════════════════════════════════════════

echo -e "${YELLOW}[3/7] Analyzing current configuration...${NC}"

# Check current default banaction
if [[ -f "$JAIL_LOCAL" ]]; then
    CURRENT_BANACTION=$(grep -E '^\s*banaction\s*=' "$JAIL_LOCAL" | grep -v '^#' | head -1 | sed 's/.*=\s*//' | tr -d ' ')
    if [[ -n "$CURRENT_BANACTION" ]]; then
        echo -e "   Current banaction: ${BLUE}$CURRENT_BANACTION${NC}"

        if [[ "$CURRENT_BANACTION" == "nftban" ]]; then
            echo -e "${GREEN}✓${NC} Already using nftban action"
            NEEDS_UPDATE=false
        else
            echo -e "${YELLOW}⚠️  Using old action, needs update${NC}"
            NEEDS_UPDATE=true
        fi
    else
        echo -e "${YELLOW}⚠️  No default banaction set${NC}"
        NEEDS_UPDATE=true
    fi
else
    NEEDS_UPDATE=true
fi

# Check for jail.d overrides
JAILS_WITH_NFTBAN=$(grep -r "action.*nftban" /etc/fail2ban/jail.d/*.conf 2>/dev/null | wc -l)
if [[ $JAILS_WITH_NFTBAN -gt 0 ]]; then
    echo -e "${GREEN}✓${NC} Found $JAILS_WITH_NFTBAN jail(s) already using nftban action"
fi

echo ""

# ═══════════════════════════════════════════════════════════════════
# Step 4: Update Configuration (if needed)
# ═══════════════════════════════════════════════════════════════════

if [[ "$NEEDS_UPDATE" == "true" ]]; then
    echo -e "${YELLOW}[4/7] Updating banaction to nftban...${NC}"

    if [[ -f "$JAIL_LOCAL" ]]; then
        # Update existing jail.local
        sed -i.pre-nftban 's/^\(\s*banaction\s*=\s*\)nftables-multiport/\1nftban/' "$JAIL_LOCAL"
        sed -i 's/^\(\s*banaction\s*=\s*\)nftables-allports/\1nftban/' "$JAIL_LOCAL"
        echo -e "${GREEN}✓${NC} Updated jail.local"
    else
        # Create minimal jail.local
        cat > "$JAIL_LOCAL" <<EOF
# NFTBan Fail2ban Integration
# Auto-generated by migration script

[DEFAULT]
# Use NFTBan unified banning
banaction = nftban

# Default settings
bantime = 1h
findtime = 10m
maxretry = 5

# Ignore local networks
ignoreip = 127.0.0.1/8 ::1

# Note: Individual jails are configured in /etc/fail2ban/jail.d/
EOF
        echo -e "${GREEN}✓${NC} Created new jail.local"
    fi
else
    echo -e "${YELLOW}[4/7] Configuration already up-to-date${NC}"
fi

echo ""

# ═══════════════════════════════════════════════════════════════════
# Step 5: Restart Fail2ban
# ═══════════════════════════════════════════════════════════════════

echo -e "${YELLOW}[5/7] Restarting fail2ban...${NC}"

systemctl restart fail2ban
sleep 3

if systemctl is-active --quiet fail2ban; then
    echo -e "${GREEN}✓${NC} fail2ban restarted successfully"
else
    echo -e "${RED}❌ fail2ban failed to start${NC}"
    echo -e "   Check logs: journalctl -u fail2ban -n 50"
    exit 1
fi

echo ""

# ═══════════════════════════════════════════════════════════════════
# Step 6: Verify Migration
# ═══════════════════════════════════════════════════════════════════

echo -e "${YELLOW}[6/7] Verifying migration...${NC}"

# Get list of enabled jails
mapfile -t JAILS < <(fail2ban-client status 2>/dev/null | grep "Jail list" | cut -d: -f2 | tr ',' '\n' | xargs)

if [[ ${#JAILS[@]} -eq 0 ]]; then
    echo -e "${YELLOW}⚠️  No jails are currently enabled${NC}"
else
    echo -e "   Checking ${#JAILS[@]} enabled jail(s)..."

    NFTBAN_COUNT=0
    for jail in "${JAILS[@]}"; do
        ACTIONS=$(fail2ban-client get "$jail" actions 2>/dev/null || echo "")
        if echo "$ACTIONS" | grep -q "nftban"; then
            echo -e "   ${GREEN}✓${NC} $jail: using nftban"
            ((NFTBAN_COUNT++))
        else
            echo -e "   ${YELLOW}⚠️${NC} $jail: $ACTIONS"
        fi
    done

    if [[ $NFTBAN_COUNT -eq ${#JAILS[@]} ]]; then
        echo -e "${GREEN}✓${NC} All jails using nftban action"
    else
        echo -e "${YELLOW}⚠️  Some jails not using nftban (may be intentional)${NC}"
    fi
fi

echo ""

# ═══════════════════════════════════════════════════════════════════
# Step 7: Test Ban System
# ═══════════════════════════════════════════════════════════════════

echo -e "${YELLOW}[7/7] Testing ban system...${NC}"

# Check if temp_ban sets exist and are accessible
if nft list set inet nftban_runtime temp_ban_v4 &>/dev/null; then
    echo -e "${GREEN}✓${NC} temp_ban_v4 set is accessible"
else
    echo -e "${RED}❌ Cannot access temp_ban_v4 set${NC}"
fi

if nft list set inet nftban_runtime temp_ban_v6 &>/dev/null; then
    echo -e "${GREEN}✓${NC} temp_ban_v6 set is accessible"
else
    echo -e "${YELLOW}⚠️  Cannot access temp_ban_v6 set (may not be created yet)${NC}"
fi

echo ""

# ═══════════════════════════════════════════════════════════════════
# Summary
# ═══════════════════════════════════════════════════════════════════

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Migration Complete!${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}Summary:${NC}"
echo -e "  • Backup: $JAIL_LOCAL_BACKUP"
echo -e "  • Banaction: nftban (NFTBan integration)"
echo -e "  • Enabled jails: ${#JAILS[@]}"
echo -e "  • Using nftban: $NFTBAN_COUNT"
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo -e "  1. Test a ban:"
echo -e "     ${GREEN}fail2ban-client set sshd banip 1.2.3.4${NC}"
echo ""
echo -e "  2. Verify ban in NFTBan:"
echo -e "     ${GREEN}nft list set inet nftban_runtime temp_ban_v4${NC}"
echo ""
echo -e "  3. Check NFTBan stats:"
echo -e "     ${GREEN}nftban stats${NC}"
echo ""
echo -e "  4. Monitor activity:"
echo -e "     ${GREEN}tail -f /var/log/fail2ban.log${NC}"
echo ""
echo -e "  5. Check persistent offenders:"
echo -e "     ${GREEN}cat /etc/nftban/blacklist.d/30-persistent-offenders.conf${NC}"
echo ""
echo -e "${YELLOW}Remember:${NC} Persistent offender detection is automatic!"
echo -e "  • 3+ bans in 24h = permanent blacklist"
echo -e "  • No separate jail needed (built into NFTBan)"
echo ""

# Optional: Remove old f2b-table
if nft list table inet f2b-table &>/dev/null; then
    echo -e "${YELLOW}Note:${NC} Old f2b-table still exists"
    echo -e "  To remove it after testing:"
    echo -e "  ${GREEN}nft delete table inet f2b-table${NC}"
    echo ""
fi

echo -e "${GREEN}Migration successful!${NC} 🎉"
echo ""
