#!/usr/bin/env bash
# =============================================================================
# NFTBan — UNINSTALL-PR2: RPM preserve-by-default + operator-config ownership
# =============================================================================
# SPDX-License-Identifier: MPL-2.0
# meta:name="operator-config-not-package-owned-v1229-test"
# meta:type="test"
# meta:owner="Antonios Voulvoulis <contact@nftban.com>"
# meta:created_date="2026-08-12"
# meta:description="Locks UNINSTALL-PR2 D1+D3: RPM standard erase preserves /etc/nftban, /var/lib/nftban and /var/log/nftban; 99-manual.conf is not package-owned in either family (no %config, not in the generated DEB conffiles); both families seed it only when absent and never overwrite an existing operator file."
# meta:inventory.files="packaging/build_nftban.sh,packaging/deb/postinst,packaging/deb/postrm"
# meta:inventory.privileges="none"
# meta:ta.id="operator_config_not_package_owned_v1229_test"
# meta:ta.owner="packaging"
# meta:ta.module="uninstall-lifecycle"
# meta:ta.execution_class="CI_HERMETIC_SHELL"
# meta:ta.gate="ci-bash"
# meta:ta.hermetic="true"
# meta:ta.requires_root="false"
# meta:ta.requires_network="false"
# meta:ta.requires_systemd="false"
# meta:ta.requires_nftables="false"
# meta:ta.requires_package="false"
# =============================================================================
#
# D1  `dnf remove nftban-core` IS the $1 -eq 0 final-erase path — RPM has no
#     purge verb — and %postun STEP 6 rm -rf'd /etc/nftban, /var/lib/nftban and
#     /var/log/nftban. DEB confined that to postrm purge). RPM was the outlier.
#         RPM STANDARD REMOVE != PURGE
#
# D3  99-manual.conf shipped as %config(noreplace) (RPM) and was staged under
#     etc/ so the generated DEB conffiles glob claimed it too. Package ownership
#     is what creates loader-invisible restore state: on erase rpm renames the
#     operator file to 99-manual.conf.rpmsave, and every loader globs
#     whitelist.d/*.conf — which .rpmsave cannot match. Fixing D1 without D3
#     would CONVERT DATA LOSS INTO SILENT NON-ENFORCEMENT, because preserving
#     /etc/nftban makes the .rpmsave survive instead of being erased.
#
# The spec is generated by a heredoc, so these assertions run against the
# GENERATED spec, not against the generator's source text.
# =============================================================================
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
BUILD="$REPO_ROOT/packaging/build_nftban.sh"
POSTINST="$REPO_ROOT/packaging/deb/postinst"

PASS=0; FAIL=0
ok(){ echo "  ✅ $1"; PASS=$((PASS+1)); }
no(){ echo "  ❌ $1"; [ -n "${2:-}" ] && echo "       $2"; FAIL=$((FAIL+1)); }

W=$(mktemp -d)
_owner=$$
trap '[ "$$" = "$_owner" ] && rm -rf "$W"' EXIT

# ---- Generate the real spec from the real generator -------------------------
awk '/^create_rpm_spec_nftban_core\(\) *\{/{n=1}
     n && /<<EOF$/{h=1}
     n && h && /^EOF$/{h=0; print; next}
     n{print}
     n && !h && /^\}$/{exit}' "$BUILD" > "$W/gen.sh"
mkdir -p "$W/SPECS"
(
    set +e
    export BUILD_DIR="$W" PROJECT_ROOT="$REPO_ROOT"
    export PKG_VERSION="0.0.0-test" PKG_RELEASE="1" PKG_VERSION_DATE="2026-01-01"
    log_info(){ :; }; log_error(){ :; }; log_warn(){ :; }; log_success(){ :; }
    # shellcheck disable=SC1090
    . "$W/gen.sh"
    create_rpm_spec_nftban_core
) >"$W/gen.out" 2>"$W/gen.err"
SPEC="$W/SPECS/nftban-core.spec"

echo "── T0  the generated spec is the test subject ─────────────────────────"
if [ -s "$SPEC" ]; then
    ok "spec generated from packaging/build_nftban.sh ($(wc -l < "$SPEC") lines)"
else
    no "spec generation failed — every arm below would be vacuous" "$(head -3 "$W/gen.err")"
    echo "══ RESULT: PASS=$PASS FAIL=$FAIL ══"; exit 1
fi

# The spec heredoc is unquoted, so an unescaped $( ) or backtick in it EXECUTES
# on the build host at generation time. A prose comment must never do that.
GENERR=$(grep -vF 'log_success' "$W/gen.err" | grep -v '^[[:space:]]*$' || true)
[ -z "$GENERR" ] && ok "spec generation ran no stray commands (heredoc is inert)" \
                 || no "spec generation executed something — unescaped \$( ) or backtick in the heredoc" "$GENERR"

# %postun scriptlet, comments stripped: prose must not satisfy or break an arm.
POSTUN=$(awk '/^%postun/{n=1;next} n && /^%[a-z]+$/{exit} n{print}' "$SPEC" | sed 's|#.*||')

echo "── T1  RPM standard erase does NOT rm -rf the preserved trees ─────────"
for tree in /etc/nftban /var/lib/nftban /var/log/nftban; do
    HIT=$(printf '%s\n' "$POSTUN" | grep -F "rm -rf $tree" || true)
    [ -z "$HIT" ] && ok "%postun does not rm -rf $tree" \
                  || no "%postun still destroys $tree on standard remove (D1)" "$HIT"
done
# The fix must not have gutted cleanup of genuinely regenerable paths.
CACHE=$(printf '%s\n' "$POSTUN" | grep -F 'rm -rf /var/cache/nftban' || true)
[ -n "$CACHE" ] && ok "regenerable cache is still cleaned (fix is scoped, not blanket)" \
                || no "cache cleanup was removed too — over-broad change" ""

echo "── T2  NEGATIVE CONTROL: the T1 detector can see a destructive line ───"
# If this fixture does not trip the same grep T1 uses, T1 proves nothing.
FIX='    rm -rf /etc/nftban 2>/dev/null || true'
SEEN=$(printf '%s\n' "$FIX" | grep -F 'rm -rf /etc/nftban' || true)
[ -n "$SEEN" ] && ok "pre-fix destructive shape IS detected — T1 non-vacuous" \
               || no "detector blind to the pre-fix shape" "T1 would be vacuous"

echo "── T3  99-manual.conf is NOT package-owned ────────────────────────────"
# Comments stripped FIRST: the rationale comments in the spec literally contain
# the words "99-manual.conf" and "config", and would satisfy a raw grep.
# GUARD_SUBJECT == GUARD_INPUT.
SPEC_CODE=$(sed 's|#.*||' "$SPEC")
CFG=$(printf '%s\n' "$SPEC_CODE" | grep -F '99-manual.conf' | grep -F '%config' || true)
[ -z "$CFG" ] && ok "RPM: no %config entry claims 99-manual.conf" \
              || no "RPM still owns operator state as %config (D3)" "$CFG"
GHOST=$(printf '%s\n' "$SPEC_CODE" | grep -F '99-manual.conf' | grep -F '%ghost' || true)
[ -z "$GHOST" ] && ok "RPM: not %ghost either (rpm removes %ghost paths on erase)" \
                || no "%ghost still lets rpm remove operator state" "$GHOST"
# The only /etc path for 99-manual.conf anywhere in %files must be NONE.
FILES=$(printf '%s\n' "$SPEC_CODE" | awk '/^%files/{n=1;next} n && /^%[a-z]+$/{exit} n{print}')
ETCOWN=$(printf '%s\n' "$FILES" | grep -F '/etc/nftban/whitelist.d/99-manual.conf' || true)
[ -z "$ETCOWN" ] && ok "%files does not list the /etc path at all (rpm owns nothing there)" \
                 || no "%files still owns the /etc operator path" "$ETCOWN"
# Templates must actually ship, or the seed has no source.
TPL=$(grep -c 'templates/[a-z]*list\.d/99-manual\.conf' "$SPEC" || true)
[ "${TPL:-0}" -ge 2 ] && ok "RPM ships both templates ($TPL references)" \
                      || no "templates missing from the spec — seed source absent" "count=$TPL"

# DEB: prove the GENERATED conffiles list does not claim the file.
echo "── T3b DEB generated conffiles must not claim operator state ──────────"
# The function body contains a nested line that is exactly "}", so stop at the
# LAST such line before the next top-level definition, not the first.
DEBFN=$(awk '/^create_deb_control\(\) *\{/{n=1}
             n{buf=buf $0 "\n"}
             n && /^\}$/{last=buf}
             n && /^[a-zA-Z_]+\(\) *\{/ && !/^create_deb_control/{exit}
             END{printf "%s", last}' "$BUILD")
if [ -z "$DEBFN" ]; then
    no "create_deb_control not found — cannot prove the DEB half" ""
else
    # ARM A — the real staging code must not put 99-manual.conf under etc/.
    # Ownership on DEB is decided by WHERE build_deb stages the file, because
    # create_deb_control globs the staged tree. Comments stripped so the
    # rationale prose cannot satisfy this.
    DEBSTAGE=$(awk '/^build_deb\(\) *\{/{n=1} n{print} n && /^\}$/{exit}' "$BUILD" | sed 's|#.*||')
    # Only the DESTINATION matters. The source argument is legitimately
    # "${PROJECT_ROOT}/etc/nftban/..." — reading from the repo is not ownership.
    # Match the staging root only, or this arm fires on the source path.
    BADSTAGE=$(printf '%s\n' "$DEBSTAGE" | grep -F '99-manual.conf' | grep -E '\$\{?deb_root\}?/etc' || true)
    [ -z "$BADSTAGE" ] && ok "build_deb does not stage 99-manual.conf under etc/" \
                       || no "build_deb still stages operator state into etc/ (D3)" "$BADSTAGE"
    GOODSTAGE=$(printf '%s\n' "$DEBSTAGE" | grep -F '99-manual.conf' | grep -F 'templates' || true)
    [ -n "$GOODSTAGE" ] && ok "build_deb stages both files as templates instead" \
                        || no "build_deb no longer ships them at all — seed source would be absent" ""

    run_conffiles() { # $1 = staging root; echoes the generated conffiles
        rm -rf "$1"; mkdir -p "$1/DEBIAN" "$1/etc/nftban/whitelist.d" "$1/etc/nftban/conf.d"
        echo "x" > "$1/etc/nftban/nftban.conf"
        shift
        for extra in "$@"; do mkdir -p "$(dirname "$1/$extra")" 2>/dev/null; done
        return 0
    }

    # ARM B — with the CORRECTED staging (no 99-manual under etc/), the
    # generated conffiles must not claim it. Positive control first: a genuine
    # operator config must appear, or "absence" would prove nothing.
    rm -rf "$W/deb"; mkdir -p "$W/deb/DEBIAN" "$W/deb/etc/nftban/whitelist.d" "$W/deb/etc/nftban/conf.d"
    echo "x" > "$W/deb/etc/nftban/nftban.conf"
    mkdir -p "$W/deb/usr/share/nftban/templates/whitelist.d"
    echo "x" > "$W/deb/usr/share/nftban/templates/whitelist.d/99-manual.conf"
    gen_conffiles() {
        (
            set +e
            export BUILD_DIR="$W" PROJECT_ROOT="$REPO_ROOT"
            export PKG_VERSION="0.0.0-test" PKG_RELEASE="1" BUILD_DISTRO="deb"
            export ID="ubuntu" VERSION_ID="24.04"
            log_info(){ :; }; log_error(){ :; }; log_warn(){ :; }; log_success(){ :; }
            eval "$DEBFN"
            create_deb_control
        ) >"$W/deb.out" 2>"$W/deb.err"
    }
    gen_conffiles
    CONFF="$W/deb/DEBIAN/conffiles"
    if [ -f "$CONFF" ]; then
        REAL=$(grep -F '/etc/nftban/nftban.conf' "$CONFF" || true)
        [ -n "$REAL" ] && ok "conffiles generator produced a real list (detector sighted)" \
                       || no "conffiles list degenerate — absence proves nothing" "$(head -3 "$CONFF")"
        CLAIM=$(grep -F '99-manual.conf' "$CONFF" || true)
        [ -z "$CLAIM" ] && ok "DEB conffiles does NOT claim 99-manual.conf (D3)" \
                        || no "dpkg still owns operator state via conffiles (D3)" "$CLAIM"
    else
        no "conffiles not generated — cannot prove the DEB half" "$(head -3 "$W/deb.err")"
    fi

    # ARM C — NEGATIVE CONTROL. Staging the file under etc/ MUST make the
    # generator claim it. This proves ARM A is load-bearing: the absence in
    # ARM B is caused by the staging fix, not by a glob that never matches.
    echo "x" > "$W/deb/etc/nftban/whitelist.d/99-manual.conf"
    gen_conffiles
    CTRL=$(grep -F '99-manual.conf' "$W/deb/DEBIAN/conffiles" 2>/dev/null || true)
    [ -n "$CTRL" ] && ok "staging under etc/ DOES cause ownership — ARM A is load-bearing" \
                   || no "conffiles glob never claims it regardless — ARM B is vacuous" ""
fi

echo "── T4  install seeds 99-manual.conf when ABSENT ───────────────────────"
# Execute the RPM seed loop for real against a sandbox root.
seed_rpm() { # $1 = root
    local root="$1"
    mkdir -p "$root/usr/share/nftban/templates/whitelist.d" \
             "$root/usr/share/nftban/templates/blacklist.d" "$root/etc/nftban"
    echo "TEMPLATE-CONTENT" > "$root/usr/share/nftban/templates/whitelist.d/99-manual.conf"
    echo "TEMPLATE-CONTENT" > "$root/usr/share/nftban/templates/blacklist.d/99-manual.conf"
    # Extract the seed loop from the generated spec and re-root it.
    awk '/D3 \(UNINSTALL-PR2\): seed operator state/{n=1}
         n{print}
         n && /^done$/{exit}' "$SPEC" \
      | sed "s|/etc/nftban/|${root}/etc/nftban/|g; s|/usr/share/nftban/|${root}/usr/share/nftban/|g" \
      > "$root/seed.sh"
    ( set +e; chown(){ :; }; . "$root/seed.sh" ) >/dev/null 2>&1
}
R1="$W/r1"; seed_rpm "$R1"
if [ -f "$R1/etc/nftban/whitelist.d/99-manual.conf" ]; then
    ok "RPM seed created whitelist.d/99-manual.conf when absent"
    grep -qF 'TEMPLATE-CONTENT' "$R1/etc/nftban/whitelist.d/99-manual.conf" \
        && ok "seeded content came from the shipped template" \
        || no "seeded file has unexpected content" ""
else
    no "RPM seed did not create the file (T4)" "$(ls -R "$R1/etc" 2>&1 | head -5)"
fi
[ -f "$R1/etc/nftban/blacklist.d/99-manual.conf" ] && ok "RPM seed created blacklist.d/99-manual.conf" \
                                                   || no "blacklist half not seeded" ""

echo "── T5  an EXISTING operator file stays byte-identical ─────────────────"
R2="$W/r2"
mkdir -p "$R2/etc/nftban/whitelist.d" "$R2/etc/nftban/blacklist.d"
printf '# operator wrote this\n203.0.113.7\n198.51.100.0/24\n' > "$R2/etc/nftban/whitelist.d/99-manual.conf"
BEFORE=$(sha256sum "$R2/etc/nftban/whitelist.d/99-manual.conf" | cut -d' ' -f1)
seed_rpm "$R2"
AFTER=$(sha256sum "$R2/etc/nftban/whitelist.d/99-manual.conf" | cut -d' ' -f1)
[ "$BEFORE" = "$AFTER" ] && ok "existing operator file untouched (sha ${BEFORE:0:12} preserved)" \
                         || no "seed OVERWROTE operator state (T5)" "$BEFORE -> $AFTER"
# And it must not have written a sidecar next to it either.
SIDE=$(find "$R2/etc/nftban" -name '99-manual.conf.*' 2>/dev/null | head -3)
[ -z "$SIDE" ] && ok "no .rpmsave/.dpkg-* style sidecar created beside it" \
               || no "a sidecar appeared next to operator state" "$SIDE"

echo "── T6  NEGATIVE CONTROL: re-adding package ownership fails T3 ─────────"
FIXTURE='%config(noreplace) %attr(640,root,nftban) /etc/nftban/whitelist.d/99-manual.conf'
CHK=$(printf '%s\n' "$FIXTURE" | grep -F '99-manual.conf' | grep -F 'config' || true)
[ -n "$CHK" ] && ok "the %config shape IS detected — T3 non-vacuous" \
              || no "detector blind to %config ownership" "T3 would be vacuous"

echo "── T7  DEB postinst seeds with the same create-if-absent contract ─────"
PI=$(sed 's|#.*||' "$POSTINST")
case "$PI" in
    *'_nftban_seed_operator_manual'*) ok "DEB postinst defines the seeding function";;
    *) no "DEB postinst has no seeding — DEB installs would ship no 99-manual.conf" "";;
esac
case "$PI" in
    *'[ -e "$_seed_dst" ] && return 0'*) ok "DEB seed returns early when the file exists (never overwrites)";;
    *) no "DEB seed lacks an existence guard — upgrade could clobber operator state" "";;
esac
for rel in 'whitelist.d/99-manual.conf' 'blacklist.d/99-manual.conf'; do
    case "$PI" in
        *"$rel"*) ok "DEB postinst seeds $rel";;
        *) no "DEB postinst does not seed $rel" "";;
    esac
done

echo "── T8  call-site wiring: the seed must actually be invoked ────────────"
# A defined-but-uncalled function ships as dead code.
CALLS=$(printf '%s\n' "$PI" | grep -c '_nftban_seed_operator_manual "' || true)
[ "${CALLS:-0}" -ge 2 ] && ok "DEB seed invoked at $CALLS call sites (not dead code)" \
                        || no "DEB seed defined but not invoked" "calls=$CALLS"
SEEDCALL=$(printf '%s\n' "$POSTUN" | grep -c '_seed_dst' || true)
RPMSEED=$(awk '/D3 \(UNINSTALL-PR2\): seed operator state/{n=1} n{print} n && /^done$/{exit}' "$SPEC" | grep -c '_seed_dst' || true)
[ "${RPMSEED:-0}" -ge 1 ] && ok "RPM seed loop present in the generated %post" \
                          || no "RPM seed loop absent from the generated spec" "count=$RPMSEED"
[ "${SEEDCALL:-0}" -eq 0 ] && ok "seed lives in %post, not %postun (install-time, not removal)" \
                           || no "seed logic leaked into %postun" "count=$SEEDCALL"

echo
echo "══ RESULT: PASS=$PASS FAIL=$FAIL ══"
[ "$FAIL" -eq 0 ] || exit 1
exit 0
