#!/usr/bin/env bash
# =============================================================================
# NFTBan v1.229.4 P1 — A SHRINKING TEST ESTATE MUST NOT BE SILENT
# =============================================================================
# SPDX-License-Identifier: MPL-2.0
# meta:name="test-count-floor-v1229-4-test"
# meta:type="test"
# meta:owner="Antonios Voulvoulis <contact@nftban.com>"
# meta:created_date="2026-08-18"
# meta:description="P1. Proves the hand-maintained test-count floor catches the delete-then-regenerate hole the generated index cannot close, that it is not derived from the index it constrains, that index/disk domains are compared only after being made comparable, and that a bare floor without justification is rejected."
# meta:inventory.files="scripts/ci/check-test-count-floor.sh,scripts/ci/data/test-count-floor.tsv"
# meta:inventory.privileges="none"
# meta:ta.id="test_count_floor_v1229_4_test"
# meta:ta.owner="cross-cutting"
# meta:ta.module="core"
# meta:ta.execution_class="CI_HERMETIC_SHELL"
# meta:ta.gate="ci-bash"
# meta:ta.hermetic="true"
# meta:ta.requires_root="false"
# meta:ta.requires_network="false"
# meta:ta.requires_systemd="false"
# meta:ta.requires_nftables="false"
# meta:ta.requires_package="false"
# =============================================================================
#
#   THE HOLE:  delete a test              -> index freshness FAILS
#              delete a test + regenerate -> index tracks the smaller reality, SILENTLY
#
#   ⛔ THE FLOOR MUST NOT DERIVE FROM THE INDEX IT CONSTRAINS — otherwise
#      delete -> regenerate index -> regenerate floor -> green.
#   ⛔ COUNT MISMATCH != MISSING TEST. The index carries a non-comment TSV header;
#      counting non-comment lines yields data+1 and mimics an off-by-one defect.
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
CHK="$ROOT/scripts/ci/check-test-count-floor.sh"
FLOOR_FILE="$ROOT/scripts/ci/data/test-count-floor.tsv"
FAIL=0
pass(){ echo "  PASS  $1"; }
fail(){ echo "  FAIL  $1"; FAIL=1; }
echo "=== test-count floor (v1.229.4 P1) ==="
for f in "$CHK" "$FLOOR_FILE"; do [[ -f "$f" ]] || { echo "  SUBJECT_NOT_FOUND: $f"; exit 1; }; done
TMP="$(mktemp -d)"; trap 'rm -rf "${TMP:?}"' EXIT
cp -a "$FLOOR_FILE" "$TMP/floor.orig"
SUM="$(sha256sum "$FLOOR_FILE" | cut -d" " -f1)"

# --- F1 · live state passes ----------------------------------------------------
bash "$CHK" >/dev/null 2>&1 && pass "F1 current estate satisfies the floor" \
                            || fail "F1 current estate does not satisfy its own floor"

# --- F2 · the floor is READ, not computed --------------------------------------
if grep -qE 'floor=\$\(.*(wc -l|find|test-authority)' "$CHK"; then
    fail "F2 the floor appears to be COMPUTED — it must be read from the hand-maintained file"
else
    pass "F2 the floor is read from file, never computed"
fi

# --- F3 · not generated by the index authority ---------------------------------
if grep -q 'test-count-floor' "$ROOT/scripts/ci/test-authority.py" 2>/dev/null; then
    fail "F3 the index generator writes the floor — the control would be tautological"
else
    pass "F3 the index generator does not write the floor"
fi

# --- F4 · INVERSION: raise the floor above reality -> must FAIL -----------------
sed -i 's/^floor\t[0-9]*/floor\t99999/' "$FLOOR_FILE"
if bash "$CHK" >/dev/null 2>&1; then
    fail "F4 a floor above the real population still PASSED — the floor is not enforced"
else
    pass "F4 INVERSION: population below the floor is detected"
fi
cp -a "$TMP/floor.orig" "$FLOOR_FILE"

# --- F5 · a bare floor with no justification is rejected -----------------------
grep -v '^justification' "$TMP/floor.orig" > "$FLOOR_FILE"
# ⛔ CAPTURE FIRST. `producer | grep -q` under `set -o pipefail` returns the PRODUCER's
# status, so a correctly-failing check makes the match look absent. Caught here in this
# very test: the arm reported "unjustified floor accepted" while the check was rejecting
# it exactly as designed.
f5_out="$(bash "$CHK" 2>&1)"
if grep -q 'no justification' <<<"$f5_out"; then
    pass "F5 a floor without a justification is rejected (a bare number is not a decision)"
else
    fail "F5 an unjustified floor was accepted"
fi
cp -a "$TMP/floor.orig" "$FLOOR_FILE"

# --- F6 · a non-numeric floor cannot silently disable the control --------------
sed -i 's/^floor\t[0-9]*/floor\tNaN/' "$FLOOR_FILE"
bash "$CHK" >/dev/null 2>&1 && fail "F6 a non-numeric floor PASSED — control silently disabled" \
                            || pass "F6 a non-numeric floor fails loudly"
cp -a "$TMP/floor.orig" "$FLOOR_FILE"

# --- F7 · restore proof --------------------------------------------------------
[[ "$(sha256sum "$FLOOR_FILE" | cut -d" " -f1)" == "$SUM" ]] \
  && pass "F7 floor file restored byte-identical after the inversions" \
  || fail "F7 the inversions leaked into the production floor file"

# --- F8 · the header is excluded POSITIVELY, not by line position --------------
if grep -q '\$1!="id"' "$CHK"; then
    pass "F8 the TSV header is excluded by its first field, not by position"
else
    fail "F8 header exclusion is positional — fragile to column/row reordering"
fi
echo
[[ $FAIL -eq 0 ]] && { echo "RESULT: PASS"; exit 0; }
echo "RESULT: FAIL"; exit 1
