// =============================================================================
// NFTBan v1.79.0 - HTTP Bot Guard: Signal Types
// =============================================================================
// SPDX-License-Identifier: MPL-2.0
// Package: botguard
// Purpose: Signal types for profile-based scoring system (v2)
//
// meta:name="botguard_signals"
// meta:type="package"
// meta:version="1.79.0"
// meta:package="botguard"
// meta:owner="Antonios Voulvoulis <contact@nftban.com>"
// meta:created_date="2026-04-08"
// meta:description="Signal types for v2 profile-based BotGuard scoring"
//
// NOTE: All v1.79 features are DISABLED by default.
// This file ships the types; activation happens in v1.80+.
//
// meta:inventory.files="signals.go"
// meta:inventory.binaries=""
// meta:inventory.env_vars=""
// meta:inventory.config_files=""
// meta:inventory.systemd_units=""
// meta:inventory.network=""
// meta:inventory.privileges=""
// =============================================================================

package botguard

import (
	"net/netip"
	"time"
)

// SignalType identifies the detection mechanism that generated a signal.
// v1.79: Types defined, not yet active in scoring.
type SignalType string

const (
	// SignalPerIPRate is triggered when a single IP exceeds request rate threshold.
	SignalPerIPRate SignalType = "per_ip_rate"

	// SignalGlobalPressure is triggered when server-wide request rate is elevated.
	SignalGlobalPressure SignalType = "global_pressure"

	// SignalPrefixHot is triggered when multiple IPs in same /24 (v4) or /64 (v6) are active.
	SignalPrefixHot SignalType = "prefix_hot"

	// SignalPathMatch is triggered when request path matches a rule pattern.
	SignalPathMatch SignalType = "path_match"

	// SignalEvasion is triggered when raw request path differs from normalized (encoding tricks).
	SignalEvasion SignalType = "evasion"

	// Signal404Burst is triggered when IP generates high rate of 404 responses.
	Signal404Burst SignalType = "404_burst"

	// SignalMethodAbuse is triggered for unusual HTTP method usage (e.g., TRACE, OPTIONS flood).
	SignalMethodAbuse SignalType = "method_abuse"

	// SignalVerifyFail is triggered when FCrDNS verification fails.
	SignalVerifyFail SignalType = "verify_fail"
)

// String returns the signal type as a string.
func (s SignalType) String() string {
	return string(s)
}

// Signal represents a detection event that contributes to an IP's score.
// Signals are generated by various detection mechanisms and aggregated
// by the scoring engine to determine state transitions.
type Signal struct {
	Type      SignalType     // Detection mechanism
	IP        netip.Addr     // Source IP address
	Score     int            // Score contribution from this signal
	Rule      *Rule          // Rule that triggered this signal (if path-based)
	Timestamp time.Time      // When signal was generated
	Metadata  map[string]any // Additional context (path, method, status, etc.)
}

// NewSignal creates a new signal with the current timestamp.
func NewSignal(typ SignalType, ip netip.Addr, score int) *Signal {
	return &Signal{
		Type:      typ,
		IP:        ip,
		Score:     score,
		Timestamp: time.Now(),
		Metadata:  make(map[string]any),
	}
}

// WithRule attaches a rule to the signal.
func (s *Signal) WithRule(r *Rule) *Signal {
	s.Rule = r
	return s
}

// WithMeta adds metadata to the signal.
func (s *Signal) WithMeta(key string, value any) *Signal {
	if s.Metadata == nil {
		s.Metadata = make(map[string]any)
	}
	s.Metadata[key] = value
	return s
}

// RuleGroup classifies rules by their protection domain.
// Groups can have different scoring multipliers and modes.
type RuleGroup string

const (
	// GroupAuth protects authentication endpoints (login, admin, etc.).
	GroupAuth RuleGroup = "auth"

	// GroupRPC protects RPC endpoints (xmlrpc.php, wp-json, etc.).
	GroupRPC RuleGroup = "rpc"

	// GroupEnum protects against enumeration attacks (user discovery, etc.).
	GroupEnum RuleGroup = "enum"

	// GroupCommerce protects e-commerce endpoints (cart, checkout, etc.).
	GroupCommerce RuleGroup = "commerce"

	// GroupHeavy protects resource-intensive endpoints (search, export, etc.).
	GroupHeavy RuleGroup = "heavy"

	// GroupProbe detects scanning and probing behavior.
	GroupProbe RuleGroup = "probe"

	// GroupEvasion detects path obfuscation and encoding tricks.
	GroupEvasion RuleGroup = "evasion"

	// GroupGeneric is the default catch-all group.
	GroupGeneric RuleGroup = "generic"
)

// String returns the group as a string.
func (g RuleGroup) String() string {
	return string(g)
}

// Action defines what happens when a rule matches.
type Action string

const (
	// ActionScore adds score points (default behavior).
	ActionScore Action = "score"

	// ActionBan immediately bans the IP.
	ActionBan Action = "ban"

	// ActionGrey immediately moves IP to grey state.
	ActionGrey Action = "grey"

	// ActionAllow marks IP as allowed (e.g., verified crawler).
	ActionAllow Action = "allow"

	// ActionLog logs the match without affecting score.
	ActionLog Action = "log"

	// ActionExempt exempts the IP from further scoring for this request.
	ActionExempt Action = "exempt"
)

// Rule defines a detection pattern with its scoring and action.
// Rules are loaded from YAML profile files.
type Rule struct {
	ID          string    `yaml:"id"`           // Unique rule identifier
	Profile     string    `yaml:"profile"`      // Which profile owns this rule
	Group       RuleGroup `yaml:"group"`        // Protection domain
	Pattern     string    `yaml:"pattern"`      // Regex pattern to match
	MatchTarget string    `yaml:"match_target"` // raw_target/normalized_path/decoded_path/query_string
	Methods     []string  `yaml:"methods"`      // HTTP methods (empty = all)
	StatusCodes []int     `yaml:"status_codes"` // Response codes to match (empty = all)
	Score       int       `yaml:"score"`        // Base score for this rule
	RateLimit   string    `yaml:"rate_limit"`   // nft rate string (e.g., "10/minute")
	Burst       int       `yaml:"burst"`        // nft burst value
	Action      Action    `yaml:"action"`       // What to do on match
	Exempt      bool      `yaml:"exempt"`       // If true, exempts from further scoring
	Description string    `yaml:"description"`  // Human-readable description
}

// MatchTargetType identifies which part of the request to match against.
type MatchTargetType string

const (
	// MatchRawTarget matches the raw request target (for evasion detection).
	MatchRawTarget MatchTargetType = "raw_target"

	// MatchNormalizedPath matches the normalized path (default).
	MatchNormalizedPath MatchTargetType = "normalized_path"

	// MatchDecodedPath matches the URL-decoded path.
	MatchDecodedPath MatchTargetType = "decoded_path"

	// MatchQueryString matches the query string only.
	MatchQueryString MatchTargetType = "query_string"
)
