#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Antonios Voulvoulis <contact@nftban.com>
#
# gen-pipefail-epipe-inventory.sh — regenerate the recorded per-file inventory of
# `producer | grep -q` sites in the BLOCKING shell-test corpus (v1.231.0 D4).
#
# The inventory is the ratchet baseline consumed by
# scripts/ci/check-pipefail-epipe-shortcircuit.sh. It is GENERATED so it cannot
# drift into a hand-curated list, and so "fix a file, regenerate" is a mechanical
# step rather than an editorial one.
#
# The matcher here MUST stay identical to count_sites() in the guard. It is
# duplicated rather than sourced because the guard is a standalone merge gate
# that must not depend on a generator being present; the falsifiability suite
# asserts the two agree.
set -Eeuo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"
OUT="scripts/ci/data/pipefail-epipe-test-corpus-inventory.tsv"

count_sites() {
    local f="$1" n=0 ln line _stripped
    grep -qE '^[[:space:]]*set[[:space:]]+-[A-Za-z]*o?[[:space:]]*pipefail|set[[:space:]]+-o[[:space:]]+pipefail' "$f" || { printf '0'; return; }
    while IFS=: read -r ln _; do
        [[ -z "$ln" ]] && continue
        line="$(sed -n "${ln}p" "$f")"
        _stripped="${line#"${line%%[![:space:]]*}"}"
        case "$_stripped" in \#*) continue ;; esac
        case "$line" in *"# epipe-ok"*) continue ;; esac
        n=$((n + 1))
    done < <(grep -nE '[^|]\|[[:space:]]*grep[[:space:]]+-[a-zA-Z]*q' "$f" \
             | grep -vE '(^|[^A-Za-z_])(echo|printf)[^|]*\|[[:space:]]*grep' || true)
    printf '%d' "$n"
}

{
    echo "# GENERATED by scripts/ci/gen-pipefail-epipe-inventory.sh — do not hand-edit."
    echo "# Per-file count of timing-dependent \`producer | grep -q\` sites in the"
    echo "# BLOCKING shell-test corpus (test-authority-index gate = ci-bash|policy-gates)."
    echo "# Ratchet: a count may only go DOWN, and a decrease must be recorded here."
    while IFS= read -r f; do
        [[ -f "$f" ]] || continue
        n="$(count_sites "$f")"
        [[ "$n" -gt 0 ]] && printf '%s\t%s\n' "$f" "$n"
    done < <(awk -F'\t' '$7=="ci-bash" || $7=="policy-gates" { print $2 }' \
                 scripts/ci/test-authority-index.tsv | sort -u)
} > "$OUT"
printf 'wrote %s (%d files, %d sites)\n' "$OUT" \
    "$(grep -vc '^#' "$OUT")" \
    "$(awk -F'\t' '!/^#/{s+=$2} END{print s+0}' "$OUT")"
