// =============================================================================
// NFTBan v1.106 - paths.go ↔ fhs-spec.yaml parity test (MFST-C4)
// =============================================================================
// SPDX-License-Identifier: MPL-2.0
// meta:name="installer-fhs-paths-yaml-parity-test"
// meta:type="test"
// meta:header="paths.go ↔ fhs-spec.yaml parity test"
// meta:version="1.106.0"
// meta:owner="Antonios Voulvoulis <contact@nftban.com>"
// meta:homepage="https://nftban.com"
//
// meta:description="Assert RequiredDirs paths are declared in build/fhs-spec.yaml via the C0a-generated JSON mirror"
// meta:inventory.files="cli/lib/nftban/data/fhs_directories.json"
// meta:inventory.binaries=""
// meta:inventory.env_vars=""
// meta:inventory.config_files=""
// meta:inventory.systemd_units=""
// meta:inventory.network=""
// meta:inventory.privileges="user"
//
// meta:created_date="2026-05-06"
// meta:updated_date="2026-05-06"
//
// Closes drift D4 (paths.go ↔ fhs-spec.yaml parity). Future RequiredDirs
// additions must either appear in build/fhs-spec.yaml (and propagate via
// build/generate-fhs-outputs.sh into the JSON mirror) or be added to the
// requiredDirsYamlExemptions map with documented rationale.
//
// Reads cli/lib/nftban/data/fhs_directories.json (generated by
// build/generate-fhs-outputs.sh from build/fhs-spec.yaml; freshness is
// CI-enforced by the existing FHS --check step).
// =============================================================================

package fhs

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// requiredDirsYamlExemptions lists RequiredDirs paths that are intentionally
// NOT declared in build/fhs-spec.yaml. Each entry must include rationale.
//
// Adding to this map should be rare. Prefer adding the path to
// build/fhs-spec.yaml instead. An exemption is appropriate only when a
// RequiredDirs path is a runtime-only subdirectory of an externally-owned
// parent that nftban does not package or own.
var requiredDirsYamlExemptions = map[string]string{
	"/var/lib/node_exporter/textfile_collector": "Runtime-only subdir of /var/lib/node_exporter (declared in fhs-spec.yaml under conditional.metrics with note 'External service - only create if node_exporter installed'). The deeper textfile_collector subdir is where nftban deposits Prometheus textfile metrics; node_exporter package owns the parent.",
}

// fhsDirectoriesJSON mirrors cli/lib/nftban/data/fhs_directories.json shape.
// Categories under "directories" are merged into a single path set.
type fhsDirectoriesJSON struct {
	Directories map[string][]struct {
		Path string `json:"path"`
	} `json:"directories"`
}

// loadFHSPaths reads the C0a-generated JSON mirror and returns the set of
// paths declared in fhs-spec.yaml. Any failure here is a hard test failure
// because it indicates a missing or stale generator output (which CI's FHS
// --check step would catch separately).
func loadFHSPaths(t *testing.T) map[string]bool {
	t.Helper()
	_, filename, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(filename), "..", "..", "..")
	jsonPath := filepath.Join(repoRoot, "cli", "lib", "nftban", "data", "fhs_directories.json")

	data, err := os.ReadFile(jsonPath) // #nosec G304 — fixed test-time path under repo root
	if err != nil {
		t.Fatalf("read %s: %v\n(generator output missing or stale; run: bash build/generate-fhs-outputs.sh)", jsonPath, err)
	}

	var spec fhsDirectoriesJSON
	if err := json.Unmarshal(data, &spec); err != nil {
		t.Fatalf("parse %s: %v", jsonPath, err)
	}

	yamlPaths := make(map[string]bool)
	for _, entries := range spec.Directories {
		for _, entry := range entries {
			yamlPaths[entry.Path] = true
		}
	}
	if len(yamlPaths) == 0 {
		t.Fatalf("%s contains zero directory entries (likely a generator regression)", jsonPath)
	}
	return yamlPaths
}

// TestRequiredDirsYamlParity asserts every RequiredDirs path is either:
//  (a) declared in build/fhs-spec.yaml (via the JSON mirror), or
//  (b) explicitly exempted in requiredDirsYamlExemptions with rationale.
//
// On failure, the error message lists the missing paths and tells the
// reader how to remediate (add to yaml or add to exemption map).
func TestRequiredDirsYamlParity(t *testing.T) {
	yamlPaths := loadFHSPaths(t)

	var missing []string
	var exempted []string
	for _, dir := range RequiredDirs {
		if yamlPaths[dir.Path] {
			continue
		}
		if reason, ok := requiredDirsYamlExemptions[dir.Path]; ok {
			exempted = append(exempted, dir.Path+" — "+reason)
			continue
		}
		missing = append(missing, dir.Path)
	}

	sort.Strings(exempted)
	for _, e := range exempted {
		t.Logf("EXEMPT: %s", e)
	}

	if len(missing) > 0 {
		sort.Strings(missing)
		t.Errorf(`RequiredDirs ↔ fhs-spec.yaml parity failed.
The following %d path(s) are in internal/installer/fhs/paths.go::RequiredDirs
but are NOT declared in build/fhs-spec.yaml directories: section
(verified via cli/lib/nftban/data/fhs_directories.json):

%s

Remediation (pick one):
  (a) Add the path to build/fhs-spec.yaml under the appropriate category, then
      run: bash build/generate-fhs-outputs.sh   (regenerates the JSON mirror)
  (b) Add the path to requiredDirsYamlExemptions in this test file with a
      one-line rationale describing why the path is runtime-only and not
      part of package-territory.`,
			len(missing), strings.Join(missing, "\n"))
	}
}

// =============================================================================
// AUTH-HARDENING (v1.107): paths.go ↔ tmpfiles.d mode/owner parity (D-NEW-8)
// =============================================================================
// Closes drift class D-NEW-8 (rows 1-7 in V107_AUTH_HARDENING_SCOPE.md §3).
// Asserts that for every shared path, paths.go RequiredDirs mode + owner
// matches install/systemd/tmpfiles.d/nftban.conf (which is generated from
// build/fhs-spec.yaml — verified by FHS --check).
//
// Drift here means a future paths.go edit re-introduced an authority-surface
// disagreement; the test names the path + the divergent value pair so the
// remediation is obvious.

// tmpfilesEntry captures one parsed tmpfiles.d directive.
type tmpfilesEntry struct {
	path  string
	mode  uint32
	owner string
	group string
}

// loadTmpfilesEntries parses install/systemd/tmpfiles.d/nftban.conf and
// returns a path -> entry map for `d` (directory) directives only.
func loadTmpfilesEntries(t *testing.T) map[string]tmpfilesEntry {
	t.Helper()
	_, filename, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(filename), "..", "..", "..")
	tmpfilesPath := filepath.Join(repoRoot, "install", "systemd", "tmpfiles.d", "nftban.conf")

	f, err := os.Open(tmpfilesPath) // #nosec G304 — fixed test-time path under repo root
	if err != nil {
		t.Fatalf("read %s: %v\n(generator output missing or stale; run: bash build/generate-fhs-outputs.sh)", tmpfilesPath, err)
	}
	defer f.Close()

	out := make(map[string]tmpfilesEntry)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Format: <type> <path> <mode> <owner> <group> <age> <argument>
		fields := strings.Fields(line)
		if len(fields) < 5 {
			continue
		}
		if fields[0] != "d" {
			continue
		}
		mode, err := strconv.ParseUint(fields[2], 8, 32)
		if err != nil {
			t.Fatalf("parse mode %q on line %q in %s: %v", fields[2], line, tmpfilesPath, err)
		}
		out[fields[1]] = tmpfilesEntry{
			path:  fields[1],
			mode:  uint32(mode),
			owner: fields[3],
			group: fields[4],
		}
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan %s: %v", tmpfilesPath, err)
	}
	if len(out) == 0 {
		t.Fatalf("%s contained zero `d` directives (likely generator regression)", tmpfilesPath)
	}
	return out
}

// TestRequiredDirsModesAndOwnersMatchTmpfiles asserts mode/owner parity
// between paths.go::RequiredDirs and tmpfiles.d/nftban.conf for every
// path that appears in both surfaces. Paths only in one surface are
// ignored (covered by TestRequiredDirsYamlParity above + the FHS --check
// gate); this test catches *value* drift, not *presence* drift.
func TestRequiredDirsModesAndOwnersMatchTmpfiles(t *testing.T) {
	tmpfiles := loadTmpfilesEntries(t)

	type mismatch struct {
		path     string
		paths_go string
		tmpfiles string
	}
	var mismatches []mismatch

	for _, dir := range RequiredDirs {
		entry, ok := tmpfiles[dir.Path]
		if !ok {
			continue // path is package-territory or feature-gated; not in tmpfiles
		}
		expected := fmt.Sprintf("%s:%s", entry.owner, entry.group)
		if dir.Owner != expected || dir.Mode != entry.mode {
			mismatches = append(mismatches, mismatch{
				path:     dir.Path,
				paths_go: fmt.Sprintf("%04o %s", dir.Mode, dir.Owner),
				tmpfiles: fmt.Sprintf("%04o %s", entry.mode, expected),
			})
		}
	}

	if len(mismatches) > 0 {
		sort.Slice(mismatches, func(i, j int) bool { return mismatches[i].path < mismatches[j].path })
		var msg strings.Builder
		fmt.Fprintf(&msg, "RequiredDirs ↔ tmpfiles.d mode/owner parity failed (%d mismatches)\n\n", len(mismatches))
		fmt.Fprintf(&msg, "%-50s  %-22s  %-22s\n", "PATH", "paths.go", "tmpfiles.d (SoT)")
		fmt.Fprintf(&msg, "%-50s  %-22s  %-22s\n", strings.Repeat("-", 50), strings.Repeat("-", 22), strings.Repeat("-", 22))
		for _, m := range mismatches {
			fmt.Fprintf(&msg, "%-50s  %-22s  %-22s\n", m.path, m.paths_go, m.tmpfiles)
		}
		fmt.Fprintf(&msg, "\nRemediation: align paths.go::RequiredDirs to tmpfiles.d (which is generated from build/fhs-spec.yaml).\n")
		fmt.Fprintf(&msg, "Do NOT edit tmpfiles.d directly — edit fhs-spec.yaml + regen.\n")
		t.Errorf("%s", msg.String())
	}
}

// TestSuricataLogIsFeatureGated asserts paths.go does NOT eagerly create
// /var/log/nftban/suricata. Per build/fhs-spec.yaml the directory is
// `created_by: feature_enable` (via `nftban suricata enable`) with owner
// suricata:nftban. Eager creation by paths.go conflicts with the
// feature-gate contract (D8.7 in V107 scope §3).
func TestSuricataLogIsFeatureGated(t *testing.T) {
	const suricataLog = "/var/log/nftban/suricata"
	for _, dir := range RequiredDirs {
		if dir.Path == suricataLog {
			t.Errorf(`paths.go RequiredDirs eagerly creates %s.
This conflicts with the feature_enable contract in build/fhs-spec.yaml
(directory is created by 'nftban suricata enable' as suricata:nftban 0770).
Remove the entry from RequiredDirs.`, suricataLog)
		}
	}
}
