// =============================================================================
// NFTBan v1.106 - paths.go ↔ fhs-spec.yaml parity test (MFST-C4)
// =============================================================================
// SPDX-License-Identifier: MPL-2.0
// meta:name="installer-fhs-paths-yaml-parity-test"
// meta:type="test"
// meta:header="paths.go ↔ fhs-spec.yaml parity test"
// meta:version="1.106.0"
// meta:owner="Antonios Voulvoulis <contact@nftban.com>"
// meta:homepage="https://nftban.com"
//
// meta:description="Assert RequiredDirs paths are declared in build/fhs-spec.yaml via the C0a-generated JSON mirror"
// meta:inventory.files="cli/lib/nftban/data/fhs_directories.json"
// meta:inventory.binaries=""
// meta:inventory.env_vars=""
// meta:inventory.config_files=""
// meta:inventory.systemd_units=""
// meta:inventory.network=""
// meta:inventory.privileges="user"
//
// meta:created_date="2026-05-06"
// meta:updated_date="2026-05-06"
//
// Closes drift D4 (paths.go ↔ fhs-spec.yaml parity). Future RequiredDirs
// additions must either appear in build/fhs-spec.yaml (and propagate via
// build/generate-fhs-outputs.sh into the JSON mirror) or be added to the
// requiredDirsYamlExemptions map with documented rationale.
//
// Reads cli/lib/nftban/data/fhs_directories.json (generated by
// build/generate-fhs-outputs.sh from build/fhs-spec.yaml; freshness is
// CI-enforced by the existing FHS --check step).
// =============================================================================

package fhs

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"
)

// requiredDirsYamlExemptions lists RequiredDirs paths that are intentionally
// NOT declared in build/fhs-spec.yaml. Each entry must include rationale.
//
// Adding to this map should be rare. Prefer adding the path to
// build/fhs-spec.yaml instead. An exemption is appropriate only when a
// RequiredDirs path is a runtime-only subdirectory of an externally-owned
// parent that nftban does not package or own.
var requiredDirsYamlExemptions = map[string]string{
	"/var/lib/node_exporter/textfile_collector": "Runtime-only subdir of /var/lib/node_exporter (declared in fhs-spec.yaml under conditional.metrics with note 'External service - only create if node_exporter installed'). The deeper textfile_collector subdir is where nftban deposits Prometheus textfile metrics; node_exporter package owns the parent.",
}

// fhsDirectoriesJSON mirrors cli/lib/nftban/data/fhs_directories.json shape.
// Categories under "directories" are merged into a single path set.
type fhsDirectoriesJSON struct {
	Directories map[string][]struct {
		Path string `json:"path"`
	} `json:"directories"`
}

// loadFHSPaths reads the C0a-generated JSON mirror and returns the set of
// paths declared in fhs-spec.yaml. Any failure here is a hard test failure
// because it indicates a missing or stale generator output (which CI's FHS
// --check step would catch separately).
func loadFHSPaths(t *testing.T) map[string]bool {
	t.Helper()
	_, filename, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(filename), "..", "..", "..")
	jsonPath := filepath.Join(repoRoot, "cli", "lib", "nftban", "data", "fhs_directories.json")

	data, err := os.ReadFile(jsonPath) // #nosec G304 — fixed test-time path under repo root
	if err != nil {
		t.Fatalf("read %s: %v\n(generator output missing or stale; run: bash build/generate-fhs-outputs.sh)", jsonPath, err)
	}

	var spec fhsDirectoriesJSON
	if err := json.Unmarshal(data, &spec); err != nil {
		t.Fatalf("parse %s: %v", jsonPath, err)
	}

	yamlPaths := make(map[string]bool)
	for _, entries := range spec.Directories {
		for _, entry := range entries {
			yamlPaths[entry.Path] = true
		}
	}
	if len(yamlPaths) == 0 {
		t.Fatalf("%s contains zero directory entries (likely a generator regression)", jsonPath)
	}
	return yamlPaths
}

// TestRequiredDirsYamlParity asserts every RequiredDirs path is either:
//  (a) declared in build/fhs-spec.yaml (via the JSON mirror), or
//  (b) explicitly exempted in requiredDirsYamlExemptions with rationale.
//
// On failure, the error message lists the missing paths and tells the
// reader how to remediate (add to yaml or add to exemption map).
func TestRequiredDirsYamlParity(t *testing.T) {
	yamlPaths := loadFHSPaths(t)

	var missing []string
	var exempted []string
	for _, dir := range RequiredDirs {
		if yamlPaths[dir.Path] {
			continue
		}
		if reason, ok := requiredDirsYamlExemptions[dir.Path]; ok {
			exempted = append(exempted, dir.Path+" — "+reason)
			continue
		}
		missing = append(missing, dir.Path)
	}

	sort.Strings(exempted)
	for _, e := range exempted {
		t.Logf("EXEMPT: %s", e)
	}

	if len(missing) > 0 {
		sort.Strings(missing)
		t.Errorf(`RequiredDirs ↔ fhs-spec.yaml parity failed.
The following %d path(s) are in internal/installer/fhs/paths.go::RequiredDirs
but are NOT declared in build/fhs-spec.yaml directories: section
(verified via cli/lib/nftban/data/fhs_directories.json):

%s

Remediation (pick one):
  (a) Add the path to build/fhs-spec.yaml under the appropriate category, then
      run: bash build/generate-fhs-outputs.sh   (regenerates the JSON mirror)
  (b) Add the path to requiredDirsYamlExemptions in this test file with a
      one-line rationale describing why the path is runtime-only and not
      part of package-territory.`,
			len(missing), strings.Join(missing, "\n"))
	}
}
