// =============================================================================
// NFTBan v1.100 PR-22A — runUninstallDryRun Purity Test (Boundary Repair)
// =============================================================================
// SPDX-License-Identifier: MPL-2.0
// meta:name="nftban-installer-uninstall-dryrun-test"
// meta:type="test"
// meta:owner="Antonios Voulvoulis <contact@nftban.com>"
// meta:created_date="2026-04-19"
// meta:description="Falsifiable purity test: runUninstallDryRun must not mutate"
// meta:inventory.files="cmd/nftban-installer/uninstall_dryrun_test.go"
// meta:inventory.binaries=""
// meta:inventory.env_vars=""
// meta:inventory.config_files=""
// meta:inventory.systemd_units=""
// meta:inventory.network=""
// meta:inventory.privileges="none"
// =============================================================================
//
// Closes audit R4: the original PR-22 test suite verified shapes
// (classifier states, probe states, plan render) but never exercised
// the orchestrator runUninstallDryRun itself.
//
// PR-22B follow-up (audit N-2): migrated from a local forbidden-pattern
// list to the shared audit.PurityHarness so future mutation patterns
// added to one list propagate to all three lifecycle modes' tests.
//
// =============================================================================
package main

import (
	"context"
	"testing"

	"github.com/itcmsgr/nftban/internal/installer/audit"
	"github.com/itcmsgr/nftban/internal/installer/executor"
	"github.com/itcmsgr/nftban/internal/installer/logging"
	"github.com/itcmsgr/nftban/internal/installer/state"
)

// TestRunUninstallDryRun_Purity_NoMutation is the R4 falsifiable guard.
//
// Calls runUninstallDryRun with a MockExecutor + real temp directory as
// stateDir, then asserts via audit.PurityHarness that:
//
//  1. zero executor writes (WriteFileAtomic)
//  2. zero executor MkdirAll calls
//  3. zero mutation-flavored commands (nft add/flush/delete, systemctl
//     lifecycle verbs, ufw/firewall-cmd/iptables-restore, package-manager
//     removal, userdel/groupdel)
//  4. zero files on disk under temp stateDir — catches direct os.*
//     filesystem writes that bypass the executor
func TestRunUninstallDryRun_Purity_NoMutation(t *testing.T) {
	tmp := t.TempDir()

	mock := executor.NewMockExecutor()
	mock.RunResults["iptables-save"] = executor.Result{
		ExitCode: 0,
		Stdout:   "# Generated by iptables-save\n*filter\n:INPUT ACCEPT\nCOMMIT\n",
	}

	sf := state.NewStateFile(tmp)
	sf.DryRun = true
	log := logging.New("/dev/null", false)

	cfg := &config{
		mode:     "uninstall",
		dryRun:   true,
		stateDir: tmp,
	}

	rc := runUninstallDryRun(context.Background(), mock, sf, cfg, log)
	if rc != state.ExitCommitted {
		t.Fatalf("runUninstallDryRun rc = %d; want %d (ExitCommitted)", rc, state.ExitCommitted)
	}

	audit.NewPurityHarness(mock, tmp).AssertAllPurity(t)
}

// TestRunUninstallDryRun_Purity_WithAmbiguousHost covers the repaired
// classifier path: partial nftban (table only) with no external must
// route through AuthorityAmbiguous, and the run must still be pure.
func TestRunUninstallDryRun_Purity_WithAmbiguousHost(t *testing.T) {
	tmp := t.TempDir()

	mock := executor.NewMockExecutor()
	// Partial nftban: table in kernel, daemon down.
	mock.NftTables["ip:nftban"] = true
	mock.Services["nftband.service"] = false
	mock.RunResults["iptables-save"] = executor.Result{
		ExitCode: 0,
		Stdout:   "# Generated by iptables-save\n*filter\n:INPUT ACCEPT\nCOMMIT\n",
	}

	sf := state.NewStateFile(tmp)
	sf.DryRun = true
	log := logging.New("/dev/null", false)
	cfg := &config{mode: "uninstall", dryRun: true, stateDir: tmp}

	rc := runUninstallDryRun(context.Background(), mock, sf, cfg, log)
	if rc != state.ExitCommitted {
		t.Fatalf("dry-run rc = %d; want ExitCommitted even for Ambiguous host", rc)
	}

	audit.NewPurityHarness(mock, tmp).AssertAllPurity(t)
}
