// =============================================================================
// NFTBan - Suricata Rule Configuration Generator
// =============================================================================
// SPDX-License-Identifier: MPL-2.0
// meta:name="generator"
// meta:type="package"
// meta:version="1.0.0"
// meta:owner="Antonios Voulvoulis <contact@nftban.com>"
// meta:created_date="2025-10-26"
// meta:description="Generates auto.conf and effective.conf for Suricata rules"
// meta:input="Service detection, local config"
// meta:output="Configuration files"
// meta:depends="github.com/itcmsgr/nftban/pkg/nftbanconf,github.com/itcmsgr/nftban/pkg/suricata/scanner"
// meta:inventory.files="/etc/nftban/suricata/rules/*.conf"
// meta:inventory.binaries=""
// meta:inventory.env_vars=""
// meta:inventory.config_files=""
// meta:inventory.systemd_units=""
// meta:inventory.network=""
// meta:inventory.privileges="none"
// =============================================================================

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/itcmsgr/nftban/pkg/nftbanconf"
	"github.com/itcmsgr/nftban/pkg/suricata/scanner"
)

// Config represents Suricata rule configuration
type Config struct {
	EnabledCategories []string
	DisabledCategories []string
	EnabledSIDs       []string
	DisabledSIDs      []string
	DropSIDs          []string // IPS mode SIDs
}

// ConfigPaths contains paths to config files
type ConfigPaths struct {
	LocalConf     string // User manual config (never overwritten)
	AutoConf      string // Auto-detected config (generated)
	EffectiveConf string // Merged result (generated)
	WhitelistGroups string
	BlacklistGroups string
	WhitelistSIDs   string
	BlacklistSIDs   string
	DropSIDs        string
}

// GetConfigPaths returns paths based on central NFTBan config
func GetConfigPaths() (*ConfigPaths, error) {
	cfg := nftbanconf.MustLoad()
	configDir := filepath.Join(cfg.ConfigDir, "suricata/config")

	return &ConfigPaths{
		LocalConf:       filepath.Join(configDir, "suricata.local.conf"),
		AutoConf:        filepath.Join(configDir, "suricata.auto.conf"),
		EffectiveConf:   filepath.Join(configDir, "suricata.effective.conf"),
		WhitelistGroups: filepath.Join(configDir, "whitelist-groups.conf"),
		BlacklistGroups: filepath.Join(configDir, "blacklist-groups.conf"),
		WhitelistSIDs:   filepath.Join(configDir, "whitelist-sids.conf"),
		BlacklistSIDs:   filepath.Join(configDir, "blacklist-sids.conf"),
		DropSIDs:        filepath.Join(configDir, "drop-sids.conf"),
	}, nil
}

// GenerateAutoConf creates auto.conf from scan results
func GenerateAutoConf(scanResult *scanner.ScanResult) error {
	paths, err := GetConfigPaths()
	if err != nil {
		return err
	}

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(paths.AutoConf), 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Build auto.conf content
	var content strings.Builder
	content.WriteString("# NFTBan Suricata Auto-Detected Configuration\n")
	content.WriteString(fmt.Sprintf("# Generated: %s\n", time.Now().Format(time.RFC3339)))
	content.WriteString("# DO NOT EDIT - This file is automatically generated\n")
	content.WriteString("#\n")
	content.WriteString("# To override these settings, edit suricata.local.conf\n")
	content.WriteString("#\n\n")

	// Detected services
	content.WriteString("# Detected Services:\n")
	for _, svc := range scanResult.Services {
		content.WriteString(fmt.Sprintf("#   %s (port %d)\n", svc.Name, svc.Port))
	}
	content.WriteString("\n")

	// Enabled categories
	content.WriteString("# Auto-Enabled Rule Categories\n")
	sort.Strings(scanResult.RuleCategories)
	for _, cat := range scanResult.RuleCategories {
		content.WriteString(fmt.Sprintf("ENABLE_CATEGORY=%s\n", cat))
	}

	// Write file
	if err := os.WriteFile(paths.AutoConf, []byte(content.String()), 0644); err != nil {
		return fmt.Errorf("failed to write auto.conf: %w", err)
	}

	fmt.Printf("Generated: %s\n", paths.AutoConf)
	return nil
}

// MergeConfigs creates effective.conf from local + auto
func MergeConfigs() error {
	paths, err := GetConfigPaths()
	if err != nil {
		return err
	}

	// Load configurations
	localConfig := loadConfig(paths.LocalConf)
	autoConfig := loadConfig(paths.AutoConf)
	whitelistGroups := loadList(paths.WhitelistGroups)
	blacklistGroups := loadList(paths.BlacklistGroups)
	whitelistSIDs := loadList(paths.WhitelistSIDs)
	blacklistSIDs := loadList(paths.BlacklistSIDs)
	dropSIDs := loadList(paths.DropSIDs)

	// Merge: local overrides auto
	effective := &Config{
		EnabledCategories:  mergeUnique(autoConfig.EnabledCategories, localConfig.EnabledCategories),
		DisabledCategories: localConfig.DisabledCategories,
		EnabledSIDs:        mergeUnique(autoConfig.EnabledSIDs, localConfig.EnabledSIDs),
		DisabledSIDs:       localConfig.DisabledSIDs,
		DropSIDs:           dropSIDs,
	}

	// Apply whitelist/blacklist
	effective.EnabledCategories = applyFilters(effective.EnabledCategories, whitelistGroups, blacklistGroups)
	effective.EnabledSIDs = applyFilters(effective.EnabledSIDs, whitelistSIDs, blacklistSIDs)

	// Build effective.conf content
	var content strings.Builder
	content.WriteString("# NFTBan Suricata Effective Configuration\n")
	content.WriteString(fmt.Sprintf("# Generated: %s\n", time.Now().Format(time.RFC3339)))
	content.WriteString("# DO NOT EDIT - This file is automatically generated\n")
	content.WriteString("#\n")
	content.WriteString("# This is the merged result of:\n")
	content.WriteString("#   1. suricata.auto.conf (auto-detected)\n")
	content.WriteString("#   2. suricata.local.conf (user manual overrides)\n")
	content.WriteString("#   3. whitelist/blacklist filters\n")
	content.WriteString("#\n\n")

	// Enabled categories
	if len(effective.EnabledCategories) > 0 {
		content.WriteString("# Enabled Rule Categories\n")
		sort.Strings(effective.EnabledCategories)
		for _, cat := range effective.EnabledCategories {
			content.WriteString(fmt.Sprintf("ENABLE_CATEGORY=%s\n", cat))
		}
		content.WriteString("\n")
	}

	// Disabled categories
	if len(effective.DisabledCategories) > 0 {
		content.WriteString("# Disabled Rule Categories\n")
		sort.Strings(effective.DisabledCategories)
		for _, cat := range effective.DisabledCategories {
			content.WriteString(fmt.Sprintf("DISABLE_CATEGORY=%s\n", cat))
		}
		content.WriteString("\n")
	}

	// Enabled SIDs
	if len(effective.EnabledSIDs) > 0 {
		content.WriteString("# Enabled Specific SIDs\n")
		sort.Strings(effective.EnabledSIDs)
		for _, sid := range effective.EnabledSIDs {
			content.WriteString(fmt.Sprintf("ENABLE_SID=%s\n", sid))
		}
		content.WriteString("\n")
	}

	// Disabled SIDs
	if len(effective.DisabledSIDs) > 0 {
		content.WriteString("# Disabled Specific SIDs\n")
		sort.Strings(effective.DisabledSIDs)
		for _, sid := range effective.DisabledSIDs {
			content.WriteString(fmt.Sprintf("DISABLE_SID=%s\n", sid))
		}
		content.WriteString("\n")
	}

	// DROP mode SIDs (IPS)
	if len(effective.DropSIDs) > 0 {
		content.WriteString("# IPS Mode - DROP SIDs\n")
		sort.Strings(effective.DropSIDs)
		for _, sid := range effective.DropSIDs {
			content.WriteString(fmt.Sprintf("DROP_SID=%s\n", sid))
		}
		content.WriteString("\n")
	}

	// Summary
	content.WriteString(fmt.Sprintf("# Summary: %d categories, %d SIDs enabled\n",
		len(effective.EnabledCategories), len(effective.EnabledSIDs)))

	// Write file
	if err := os.WriteFile(paths.EffectiveConf, []byte(content.String()), 0644); err != nil {
		return fmt.Errorf("failed to write effective.conf: %w", err)
	}

	fmt.Printf("Generated: %s\n", paths.EffectiveConf)
	return nil
}

// LoadConfig reads a config file (exported for rules package)
func LoadConfig(path string) *Config {
	return loadConfig(path)
}

// loadConfig reads a config file
func loadConfig(path string) *Config {
	config := &Config{
		EnabledCategories:  make([]string, 0),
		DisabledCategories: make([]string, 0),
		EnabledSIDs:        make([]string, 0),
		DisabledSIDs:       make([]string, 0),
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return config // File doesn't exist yet
	}

	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		if strings.HasPrefix(line, "ENABLE_CATEGORY=") {
			cat := strings.TrimPrefix(line, "ENABLE_CATEGORY=")
			config.EnabledCategories = append(config.EnabledCategories, cat)
		} else if strings.HasPrefix(line, "DISABLE_CATEGORY=") {
			cat := strings.TrimPrefix(line, "DISABLE_CATEGORY=")
			config.DisabledCategories = append(config.DisabledCategories, cat)
		} else if strings.HasPrefix(line, "ENABLE_SID=") {
			sid := strings.TrimPrefix(line, "ENABLE_SID=")
			config.EnabledSIDs = append(config.EnabledSIDs, sid)
		} else if strings.HasPrefix(line, "DISABLE_SID=") {
			sid := strings.TrimPrefix(line, "DISABLE_SID=")
			config.DisabledSIDs = append(config.DisabledSIDs, sid)
		}
	}

	return config
}

// loadList reads a simple list file
func loadList(path string) []string {
	data, err := os.ReadFile(path)
	if err != nil {
		return []string{}
	}

	list := make([]string, 0)
	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "#") {
			list = append(list, line)
		}
	}
	return list
}

// mergeUnique merges two slices and removes duplicates
func mergeUnique(a, b []string) []string {
	seen := make(map[string]bool)
	result := make([]string, 0)

	for _, item := range a {
		if !seen[item] {
			seen[item] = true
			result = append(result, item)
		}
	}
	for _, item := range b {
		if !seen[item] {
			seen[item] = true
			result = append(result, item)
		}
	}

	return result
}

// applyFilters applies whitelist/blacklist to a list
func applyFilters(items, whitelist, blacklist []string) []string {
	// If whitelist exists, only include whitelisted items
	if len(whitelist) > 0 {
		whitelistMap := make(map[string]bool)
		for _, item := range whitelist {
			whitelistMap[item] = true
		}

		filtered := make([]string, 0)
		for _, item := range items {
			if whitelistMap[item] {
				filtered = append(filtered, item)
			}
		}
		items = filtered
	}

	// Remove blacklisted items
	if len(blacklist) > 0 {
		blacklistMap := make(map[string]bool)
		for _, item := range blacklist {
			blacklistMap[item] = true
		}

		filtered := make([]string, 0)
		for _, item := range items {
			if !blacklistMap[item] {
				filtered = append(filtered, item)
			}
		}
		items = filtered
	}

	return items
}

// InitializeLocalConf creates default local.conf if it doesn't exist
func InitializeLocalConf() error {
	paths, err := GetConfigPaths()
	if err != nil {
		return err
	}

	// Don't overwrite existing local.conf
	if _, err := os.Stat(paths.LocalConf); err == nil {
		return nil
	}

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(paths.LocalConf), 0755); err != nil {
		return err
	}

	content := `# NFTBan Suricata Local Configuration
#
# This file is for MANUAL user overrides and is NEVER overwritten.
#
# Use this to:
#   - Enable/disable specific rule categories
#   - Enable/disable specific SIDs
#   - Override auto-detected settings
#
# Examples:
#   ENABLE_CATEGORY=emerging-malware
#   DISABLE_CATEGORY=emerging-policy
#   ENABLE_SID=2024218
#   DISABLE_SID=2019401
#
# After editing, run: nftban suricata rules generate
#

`

	if err := os.WriteFile(paths.LocalConf, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to create local.conf: %w", err)
	}

	fmt.Printf("Created: %s\n", paths.LocalConf)
	return nil
}
