# =============================================================================
# NFTBan v0.10.0 - RPM Spec File
# =============================================================================
# SPDX-License-Identifier: MPL-2.0
# Purpose: RPM package specification for Red Hat-based distributions
# Supported: Rocky Linux 9+, AlmaLinux 9+, Fedora 38+
# =============================================================================

# Disable debuginfo package generation (shell scripts don't need debug symbols)
%global debug_package %{nil}

Name:           nftban
Version:        0.10.0
Release:        1%{?dist}
Summary:        Modern nftables firewall management with commit-confirm recovery

License:        MPL-2.0
URL:            https://nftban.com
Source0:        %{name}-%{version}.tar.gz

# Build requirements
BuildArch:      x86_64 aarch64
BuildRequires:  systemd-rpm-macros

# Runtime requirements - Core dependencies
Requires:       nftables >= 1.0.0
Requires:       systemd >= 250
Requires:       bash >= 5.0
Requires:       jq >= 1.6
Requires:       curl
Requires:       shadow-utils
Requires:       coreutils
Requires:       gzip
Requires:       tar
Requires:       grep
Requires:       sed
Requires:       gawk
Requires:       findutils
Requires:       util-linux
Requires:       iproute
Requires:       ipset
Requires:       git
Requires:       polkit
Recommends:     fail2ban >= 0.11
Recommends:     logrotate

# Conflicts
Conflicts:      firewalld
Conflicts:      iptables-services
Conflicts:      iptables

%description
NFTBan is a modern, high-performance firewall management system for Linux
servers using nftables. Features include:

- Commit-confirm recovery (prevents lockout)
- Go binaries for 10-60x faster feed processing
- 8 security layers (DDoS, port scan, geo-blocking, threat feeds)
- FHS-compliant with auto-healing health system
- Integration with Fail2Ban for automatic banning
- Stats & metrics with HTML/JSON/CSV reporting

%prep
%setup -q

%build
# Go binaries are prebuilt and included in source tarball
# No compilation needed

%install
# Install from src/ directory structure
cp -a src/* %{buildroot}/

# Create FHS directories
install -d -m 0755 %{buildroot}/var/lib/nftban/{state,snapshots,feeds,keyring,backup,reports,metrics,config}
install -d -m 0755 %{buildroot}/var/cache/nftban/{geoip,tmp}
install -d -m 0750 %{buildroot}/var/log/nftban
install -d -m 0755 %{buildroot}/run/nftban

# Install systemd units
install -d -m 0755 %{buildroot}%{_unitdir}
install -m 0644 src/usr/lib/systemd/system/*.service %{buildroot}%{_unitdir}/
install -m 0644 src/usr/lib/systemd/system/*.timer %{buildroot}%{_unitdir}/

# Install sysusers.d
install -d -m 0755 %{buildroot}%{_sysusersdir}
install -m 0644 packaging/sysusers.d/nftban.conf %{buildroot}%{_sysusersdir}/nftban.conf

# Install tmpfiles.d
install -d -m 0755 %{buildroot}%{_tmpfilesdir}
install -m 0644 packaging/tmpfiles.d/nftban.conf %{buildroot}%{_tmpfilesdir}/nftban.conf

# Install logrotate
install -d -m 0755 %{buildroot}%{_sysconfdir}/logrotate.d
install -m 0644 src/etc/logrotate.d/nftban %{buildroot}%{_sysconfdir}/logrotate.d/nftban

# Install bash completion
install -d -m 0755 %{buildroot}%{_datadir}/bash-completion/completions
install -m 0644 src/usr/share/nftban/completions/nftban.bash \
    %{buildroot}%{_datadir}/bash-completion/completions/nftban

# Install Polkit rules
install -d -m 0755 %{buildroot}%{_datadir}/polkit-1/rules.d
install -m 0644 packaging/polkit-1/rules.d/60-nftban-cli.rules \
    %{buildroot}%{_datadir}/polkit-1/rules.d/60-nftban-cli.rules

%pre
# Create nftban user and nftban-cli group (via sysusers.d)
%sysusers_create_compat packaging/sysusers.d/nftban.conf

%post
# Generate system.conf with UID/GID
NFTBAN_UID=$(id -u nftban)
NFTBAN_GID=$(id -g nftban)
NFTBAN_CLI_GID=$(getent group nftban-cli | cut -d: -f3)

mkdir -p /var/lib/nftban/config
cat > /var/lib/nftban/config/system.conf <<EOF
# =============================================================================
# NFTBan System Configuration (AUTO-GENERATED - DO NOT EDIT)
# =============================================================================
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Hostname: $(hostname)
#
# ⚠️  WARNING: DO NOT EDIT THIS FILE MANUALLY
# This file MUST stay aligned with actual system UID/GID values.
# =============================================================================

NFTBAN_USER="nftban"
NFTBAN_UID=${NFTBAN_UID}
NFTBAN_GROUP="nftban"
NFTBAN_GID=${NFTBAN_GID}
NFTBAN_CLI_GROUP="nftban-cli"
NFTBAN_CLI_GID=${NFTBAN_CLI_GID}
EOF

chmod 0644 /var/lib/nftban/config/system.conf

# Reload systemd
%systemd_post nftban.timer nftban-health.timer nftban-permissions-audit.timer

# Print installation message
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  NFTBan v0.10.0 Installation Complete!                    ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo "  1. Review config: /etc/nftban/nftban.conf"
echo "  2. Customize (optional): /etc/nftban/nftban.conf.local"
echo "  3. Enable service: systemctl enable --now nftban.timer"
echo "  4. Check health: nftban health check"
echo ""

%preun
%systemd_preun nftban.timer nftban-health.timer nftban-permissions-audit.timer

%postun
%systemd_postun_with_restart nftban.timer nftban-health.timer nftban-permissions-audit.timer

# Only remove nftables config if package is being completely removed (not upgraded)
if [ $1 -eq 0 ]; then
    # Remove nftables table if empty
    nft list table inet nftban >/dev/null 2>&1 && nft delete table inet nftban || true
fi

%files
# Binaries
/usr/sbin/nftban
/usr/lib/nftban/bin/nftban-feeds
/usr/lib/nftban/bin/nftban-geoip

# Libraries and modules
/usr/lib/nftban/core/*.sh
/usr/lib/nftban/cli/*.sh

# Shared data
/usr/share/nftban/

# Configuration
%config(noreplace) /etc/nftban/nftban.conf
/etc/nftban/baseline.nft
/etc/nftban/conf.d/*.conf
%dir /etc/nftban/feeds.d
/etc/nftban/feeds.d/.gitkeep
%dir /etc/nftban/rules.d
/etc/nftban/rules.d/.gitkeep
%dir %attr(0700,root,root) /etc/nftban/secrets.d
/etc/nftban/secrets.d/.gitkeep

# Systemd units
%{_unitdir}/*.service
%{_unitdir}/*.timer

# Sysusers and tmpfiles
%{_sysusersdir}/nftban.conf
%{_tmpfilesdir}/nftban.conf

# Logrotate
/etc/logrotate.d/nftban

# Bash completion
/usr/share/bash-completion/completions/nftban

# Polkit rules
/usr/share/polkit-1/rules.d/60-nftban-cli.rules

# Runtime directories (created by tmpfiles.d)
%dir %attr(0755,nftban,nftban) /var/lib/nftban
%dir %attr(0750,nftban,nftban) /var/lib/nftban/*
%dir %attr(0755,nftban,nftban) /var/cache/nftban
%dir %attr(0750,nftban,nftban) /var/log/nftban

# Documentation
%doc README.md CHANGELOG.md
%license LICENSE

%changelog
* Wed Oct 30 2025 Antonios Voulvoulis <contact@nftban.com> - 0.10.0-1
- Complete rewrite for v0.10.0
- Add commit-confirm recovery system
- Add Go binaries for 10-60x faster processing
- Add FHS-compliant structure with auto-healing
- Add stats & metrics system
- Add dynamic UID/GID tracking
- Add Polkit integration for group-based service management
- Add permission hardening system with audit logging
- Improve security with 8 protection layers
