#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Antonios Voulvoulis <contact@nftban.com>
#
# generate-botscan-legacy-shipped.sh: build cli/lib/nftban/data/botscan_legacy_shipped.list
#
# The v1.234 pattern migration (nftban_botscan_migrate_legacy_patterns) must tell an
# operator-EDITED legacy definition from an UNEDITED one that a previous release
# shipped. Comparing only against the v1.234 defaults reported every definition that
# v1.234 itself changed (url-* -> distinct-*, regex hardening) as an operator edit:
# "82 edited definition(s) NOT applied" on every rollout host
# (BUG-BOTSCAN-PATTERN-MIGRATION-NOT-APPLIED-DEFINITIONS-SILENT).
#
# This tool collects every definition that a RELEASED version shipped, from the
# release tags' legacy files etc/nftban/patterns.d/botscan/<category>.patterns, parsed
# with the module's own _botscan_parse_record (so the key is byte-identical to what
# the migration computes). Output, one per line, sorted, unique:
#     name|pattern|match_type|threshold|window|ban|enabled
# Dev-time only: it needs the git history (release tags). The output is committed and
# shipped; it is append-only by nature (released history does not change).
#
# Usage (repo root, full clone with tags): scripts/generate-botscan-legacy-shipped.sh [--check]
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
OUT="cli/lib/nftban/data/botscan_legacy_shipped.list"
MOD="cli/lib/nftban/core/nftban_botscan.sh"
CATS="aibots badbots exploit scanner webshell"

tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
# The real parser + its two constants, extracted by name from the module.
{
    grep -E '^readonly _BS_US=|^readonly _BS_VALID_MATCH_TYPES=' "$MOD"
    echo '_botscan_warn_bad_record(){ :; }'
    awk '/^_botscan_parse_record\(\) *\{/{f=1} f{print} f && /^}/{exit}' "$MOD"
} > "$tmp/parser.sh"
grep -q '_botscan_parse_record' "$tmp/parser.sh" || { echo "parser not found in $MOD" >&2; exit 2; }

ntags=0
while IFS= read -r t; do
    have=0
    for c in $CATS; do
        p="etc/nftban/patterns.d/botscan/${c}.patterns"
        git cat-file -e "${t}:${p}" 2>/dev/null || continue
        have=1
        git show "${t}:${p}" > "$tmp/f"
        bash -c '
            set -u
            . "$1"
            while IFS= read -r l || [[ -n "$l" ]]; do
                _botscan_parse_record "$l" 2>/dev/null || continue
                printf "%s|%s|%s|%s|%s|%s|%s\n" "$_BSREC_name" "$_BSREC_pattern" "$_BSREC_match_type" \
                    "$_BSREC_threshold" "$_BSREC_window" "$_BSREC_ban" "$_BSREC_enabled"
            done < "$2"
        ' _ "$tmp/parser.sh" "$tmp/f" >> "$tmp/all"
    done
    (( have )) && ntags=$((ntags + 1))
done < <(git tag -l 'v1.*' | sort -V)
(( ntags > 0 )) || { echo "no release tag carries a legacy pattern file — is this a full clone with tags?" >&2; exit 2; }

{
    echo "# GENERATED by scripts/generate-botscan-legacy-shipped.sh — do not hand-edit."
    echo "# Every botscan definition a RELEASED version shipped in the legacy files"
    echo "# etc/nftban/patterns.d/botscan/<category>.patterns ($ntags release tags)."
    echo "# Format: name|pattern|match_type|threshold|window|ban|enabled (parsed by"
    echo "# _botscan_parse_record). Used by nftban_botscan_migrate_legacy_patterns to tell"
    echo "# an unedited old shipped definition from an operator edit."
    sort -u "$tmp/all"
} > "$tmp/out"

if [[ "${1:-}" == "--check" ]]; then
    if cmp -s "$tmp/out" "$OUT"; then echo "botscan_legacy_shipped.list: up to date"; exit 0; fi
    echo "botscan_legacy_shipped.list: STALE — re-run scripts/generate-botscan-legacy-shipped.sh" >&2; exit 1
fi
mv "$tmp/out" "$OUT"
echo "wrote $OUT: $(grep -vc '^#' "$OUT") definitions from $ntags release tags"
