// =============================================================================
// NFTBan v1.100 PR-22 — Uninstall Scaffold Tests
// =============================================================================
// SPDX-License-Identifier: MPL-2.0
// meta:name="installer-uninstall-test"
// meta:type="test"
// meta:owner="Antonios Voulvoulis <contact@nftban.com>"
// meta:created_date="2026-04-19"
// meta:description="PR-22 scaffold: authority classifier + prior probe + plan render"
// meta:inventory.files="internal/installer/uninstall/uninstall_test.go"
// meta:inventory.binaries=""
// meta:inventory.env_vars=""
// meta:inventory.config_files=""
// meta:inventory.systemd_units=""
// meta:inventory.network=""
// meta:inventory.privileges="none"
// =============================================================================
package uninstall

import (
	"bytes"
	"strings"
	"testing"
	"time"

	"github.com/itcmsgr/nftban/internal/installer/executor"
	"github.com/itcmsgr/nftban/internal/installer/logging"
)

// ptrBool / ptrTime — tiny helpers for writing PR-P2-1 record fixtures
// that need pointer fields (nil-vs-explicit distinction).
func ptrBool(v bool) *bool         { return &v }
func ptrTime(v time.Time) *time.Time { return &v }

// sampleRecordedAt is a fixed, known-good timestamp for fixture records.
// Using a package-level constant keeps fixtures reproducible and makes
// the "missing recorded_at" test distinct from the "zero time" path.
var sampleRecordedAt = time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)

func newTestLogger() *logging.Logger {
	return logging.New("/dev/null", false)
}

// ---------------------------------------------------------------------------
// Classify — 4-state authority classifier
// ---------------------------------------------------------------------------

func TestClassify_NFTBan(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true
	mock.Services["nftband.service"] = true

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityNFTBan {
		t.Errorf("State = %q; want %q", res.State, AuthorityNFTBan)
	}
	if res.External != "" {
		t.Errorf("External = %q; want empty", res.External)
	}
}

func TestClassify_External_UFW(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Services["ufw"] = true

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityExternal {
		t.Errorf("State = %q; want %q", res.State, AuthorityExternal)
	}
	if res.External != "ufw" {
		t.Errorf("External = %q; want ufw", res.External)
	}
}

func TestClassify_External_Firewalld(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Services["firewalld.service"] = true

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityExternal {
		t.Errorf("State = %q; want %q", res.State, AuthorityExternal)
	}
	if res.External != "firewalld" {
		t.Errorf("External = %q; want firewalld", res.External)
	}
}

func TestClassify_None(t *testing.T) {
	mock := executor.NewMockExecutor()
	// Explicitly mark iptables-save as returning no rules (heuristic < 3).
	mock.RunResults["iptables-save"] = executor.Result{
		ExitCode: 0,
		Stdout:   "# Generated by iptables-save\n*filter\n:INPUT ACCEPT\nCOMMIT\n",
	}

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityNone {
		t.Errorf("State = %q; want %q", res.State, AuthorityNone)
	}
}

func TestClassify_Ambiguous_NFTBanPlusUFW(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true
	mock.Services["nftband.service"] = true
	mock.Services["ufw"] = true

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityAmbiguous {
		t.Errorf("State = %q; want %q (both nftban + ufw present)", res.State, AuthorityAmbiguous)
	}
	if res.External != "ufw" {
		t.Errorf("External = %q; want ufw", res.External)
	}
}

func TestClassify_NoteOnPartialNFTBan(t *testing.T) {
	// ip nftban table present but daemon NOT active → should note the
	// inconsistency but not claim authority.
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true

	res := Classify(mock, newTestLogger())
	// Classification must not be AuthorityNFTBan (daemon is down).
	if res.State == AuthorityNFTBan {
		t.Error("partial nftban should NOT classify as AuthorityNFTBan")
	}
	// A note must surface the partial state.
	var found bool
	for _, n := range res.Notes {
		if strings.Contains(n, "nftband.service inactive") {
			found = true
		}
	}
	if !found {
		t.Error("partial-nftban warning note missing; operator must see the inconsistency")
	}
}

// Audit D.1 regression guard: partial nftban presence MUST prefer
// ambiguous/degraded over a false "no authority" claim. The reviewer's
// concern: later PRs will build mutation decisions on top of this
// detector, so any overstatement here poisons the whole chain.
func TestClassify_PartialNFTBan_WithExternal_IsAmbiguous(t *testing.T) {
	// ip nftban table present + daemon DOWN + UFW active = the classic
	// half-installed / mid-transition state. Classifier must not silently
	// claim "external is authoritative" because the nftban table is
	// still sitting in the kernel.
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true   // table still in kernel
	mock.Services["nftband.service"] = false // daemon inactive
	mock.Services["ufw"] = true               // external present

	res := Classify(mock, newTestLogger())
	if res.State == AuthorityExternal {
		t.Errorf("partial-nftban + external MUST NOT claim external authority outright; nftban table in kernel means state is ambiguous. got %q", res.State)
	}
	// The notes should surface BOTH the partial-nftban issue AND the
	// external-firewall presence so the operator has full context.
	haveNftbanNote := false
	haveExternalNote := false
	for _, n := range res.Notes {
		if strings.Contains(n, "nftband.service inactive") {
			haveNftbanNote = true
		}
		if strings.Contains(n, "ufw") || strings.Contains(n, "external") {
			haveExternalNote = true
		}
	}
	if !haveNftbanNote {
		t.Error("partial-nftban note missing — operator cannot see the half-installed state")
	}
	if !haveExternalNote {
		t.Error("external-firewall note missing — operator cannot see the ambient firewall")
	}
}

// PR-22A audit fix: partial nftban WITHOUT external must classify as
// Ambiguous, NOT None. The previous switch fell through to the
// !nftbanPresent && !extPresent case and returned AuthorityNone while
// the nftban table was still in the kernel — a silent false-negative
// that would teach PR-23's release logic to skip cleanup of the orphan
// table. This test is the regression guard.
func TestClassify_PartialNFTBan_NoExternal_IsAmbiguous(t *testing.T) {
	// Table present in kernel, daemon down, no external firewall.
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true
	mock.Services["nftband.service"] = false
	mock.RunResults["iptables-save"] = executor.Result{
		ExitCode: 0,
		Stdout:   "# Generated by iptables-save\n*filter\n:INPUT ACCEPT\nCOMMIT\n",
	}

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityAmbiguous {
		t.Errorf("partial-nftban + no external MUST classify as Ambiguous; kernel still holds nftban table. got %q", res.State)
	}
	var haveAmbigNote bool
	for _, n := range res.Notes {
		if strings.Contains(n, "indeterminate transition") {
			haveAmbigNote = true
		}
	}
	if !haveAmbigNote {
		t.Errorf("ambiguous-state note missing — operator must see why classification is ambiguous; got notes: %v", res.Notes)
	}
}

// Symmetric case for the other partial shape: daemon up without the
// nftban table. Same reasoning — authority is ambiguous, not None.
func TestClassify_DaemonUpNoTable_NoExternal_IsAmbiguous(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Services["nftband.service"] = true
	mock.RunResults["iptables-save"] = executor.Result{
		ExitCode: 0,
		Stdout:   "# Generated by iptables-save\n*filter\n:INPUT ACCEPT\nCOMMIT\n",
	}

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityAmbiguous {
		t.Errorf("daemon-up-no-table + no external MUST classify as Ambiguous. got %q", res.State)
	}
}

// ---------------------------------------------------------------------------
// Probe — 3-state prior-authority record detector
// ---------------------------------------------------------------------------

func TestProbe_NoRecord(t *testing.T) {
	mock := executor.NewMockExecutor()

	res := Probe(mock, newTestLogger())
	if res.State != PriorNoRecord {
		t.Errorf("State = %q; want %q", res.State, PriorNoRecord)
	}
	if res.Record != nil {
		t.Errorf("Record should be nil for NoRecord, got %+v", res.Record)
	}
}

// A complete PR-P2-1 record. All subsequent "missing X" tests derive
// from this by removing exactly one field — keeps failure attribution
// unambiguous.
const fullRecordJSON = `{` +
	`"schema_version":"1.100.0",` +
	`"firewall_type":"ufw",` +
	`"recorded_at":"2026-01-01T00:00:00Z",` +
	`"installer_version":"1.100.0",` +
	`"active_at_install":true}`

func TestProbe_RecordUsableActive(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(fullRecordJSON)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordUsableActive {
		t.Errorf("State = %q; want %q", res.State, PriorRecordUsableActive)
	}
	if res.Record == nil {
		t.Fatal("Record must be populated for Usable state")
	}
	if res.Record.FirewallType != "ufw" {
		t.Errorf("FirewallType = %q; want ufw", res.Record.FirewallType)
	}
	if res.Record.ActiveAtInstall == nil || !*res.Record.ActiveAtInstall {
		t.Error("ActiveAtInstall must be explicitly true for UsableActive")
	}
}

// PR-P2-1: active_at_install=false is explicitly distinguished from
// missing. Both paths are "usable" but they mean different things.
func TestProbe_RecordUsableInactive(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{` +
		`"schema_version":"1.100.0",` +
		`"firewall_type":"csf",` +
		`"recorded_at":"2026-01-01T00:00:00Z",` +
		`"installer_version":"1.100.0",` +
		`"active_at_install":false}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordUsableInactive {
		t.Errorf("State = %q; want %q (active_at_install=false is usable-but-inactive)", res.State, PriorRecordUsableInactive)
	}
	if res.Record == nil || res.Record.ActiveAtInstall == nil {
		t.Fatal("Record.ActiveAtInstall must be non-nil for UsableInactive (explicit false)")
	}
	if *res.Record.ActiveAtInstall {
		t.Error("ActiveAtInstall must be explicitly false for UsableInactive")
	}
}

func TestProbe_RecordMalformed_BadJSON(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{not valid json`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordMalformed {
		t.Errorf("State = %q; want %q (PR-P2-1 distinguishes malformed JSON from incomplete)", res.State, PriorRecordMalformed)
	}
}

func TestProbe_RecordIncomplete_MissingFirewallType(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"1.100.0","recorded_at":"2026-01-01T00:00:00Z","installer_version":"1.100.0","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (missing firewall_type)", res.State, PriorRecordIncomplete)
	}
	if res.IncompleteReason != IncompleteReasonMissingFirewallType {
		t.Errorf("IncompleteReason = %q; want %q", res.IncompleteReason, IncompleteReasonMissingFirewallType)
	}
}

func TestProbe_RecordIncomplete_UnknownFirewallType(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"1.100.0","firewall_type":"pf","recorded_at":"2026-01-01T00:00:00Z","installer_version":"1.100.0","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (unknown firewall_type)", res.State, PriorRecordIncomplete)
	}
	if res.IncompleteReason != IncompleteReasonUnknownFirewallType {
		t.Errorf("IncompleteReason = %q; want %q", res.IncompleteReason, IncompleteReasonUnknownFirewallType)
	}
}

func TestProbe_RecordIncomplete_SchemaMismatch(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"0.9.0","firewall_type":"ufw","recorded_at":"2026-01-01T00:00:00Z","installer_version":"1.100.0","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (schema mismatch — no migration in v1.100)", res.State, PriorRecordIncomplete)
	}
	if res.IncompleteReason != IncompleteReasonSchemaMismatch {
		t.Errorf("IncompleteReason = %q; want %q", res.IncompleteReason, IncompleteReasonSchemaMismatch)
	}
}

// PR-P2-1 new required field: recorded_at.
func TestProbe_RecordIncomplete_MissingRecordedAt(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"1.100.0","firewall_type":"ufw","installer_version":"1.100.0","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (PR-P2-1 requires recorded_at)", res.State, PriorRecordIncomplete)
	}
	if res.IncompleteReason != IncompleteReasonMissingRecordedAt {
		t.Errorf("IncompleteReason = %q; want %q", res.IncompleteReason, IncompleteReasonMissingRecordedAt)
	}
}

// PR-P2-1 new required field: installer_version.
func TestProbe_RecordIncomplete_MissingInstallerVersion(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"1.100.0","firewall_type":"ufw","recorded_at":"2026-01-01T00:00:00Z","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (PR-P2-1 requires installer_version)", res.State, PriorRecordIncomplete)
	}
	if res.IncompleteReason != IncompleteReasonMissingInstallerVersion {
		t.Errorf("IncompleteReason = %q; want %q", res.IncompleteReason, IncompleteReasonMissingInstallerVersion)
	}
}

// PR-P2-1: active_at_install MUST be explicitly present. A record that
// omits the field entirely is Incomplete — distinguishing "writer
// committed to false" from "writer forgot to commit."
func TestProbe_RecordIncomplete_MissingActiveAtInstall(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"1.100.0","firewall_type":"ufw","recorded_at":"2026-01-01T00:00:00Z","installer_version":"1.100.0"}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (PR-P2-1 requires explicit active_at_install)", res.State, PriorRecordIncomplete)
	}
	if res.IncompleteReason != IncompleteReasonMissingActiveAtInstall {
		t.Errorf("IncompleteReason = %q; want %q", res.IncompleteReason, IncompleteReasonMissingActiveAtInstall)
	}
}

// PR-P2-1 backward-safety: records written by pre-P2-1 installers that
// lack recorded_at + installer_version + explicit active_at_install
// MUST be reclassified as Incomplete. Migration-style silent upgrade
// is forbidden.
func TestProbe_OldStyleRecord_DegradesToIncomplete(t *testing.T) {
	mock := executor.NewMockExecutor()
	// Exact shape that pre-P2-1 tests used: schema + firewall + active.
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"1.100.0","firewall_type":"ufw","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State == PriorRecordUsableActive || res.State == PriorRecordUsableInactive {
		t.Errorf("PR-P2-1 safety regression: old-style record silently upgraded to %q — must be Incomplete", res.State)
	}
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (old record must degrade safely)", res.State, PriorRecordIncomplete)
	}
	// The first missing field encountered by Probe is recorded_at, so
	// that is the expected reason.
	if res.IncompleteReason != IncompleteReasonMissingRecordedAt {
		t.Errorf("IncompleteReason = %q; want %q (first missing field)", res.IncompleteReason, IncompleteReasonMissingRecordedAt)
	}
}

// ---------------------------------------------------------------------------
// BuildPlan + Render — contract-language output
// ---------------------------------------------------------------------------

func happyClassify() *ClassifyResult {
	return &ClassifyResult{State: AuthorityNFTBan}
}

func noPriorProbe() *ProbeResult {
	return &ProbeResult{State: PriorNoRecord}
}

func usablePriorProbe() *ProbeResult {
	return &ProbeResult{
		State: PriorRecordUsableActive,
		Record: &PriorRecord{
			SchemaVersion:    PlanSchemaVersion,
			FirewallType:     "ufw",
			RecordedAt:       ptrTime(sampleRecordedAt),
			InstallerVersion: "1.100.0",
			ActiveAtInstall:  ptrBool(true),
		},
	}
}

// usableInactivePriorProbe is the PR-P2-1 companion: all fields present
// but active_at_install is explicitly false. BuildPlan should still
// authorize restore (IsUsable returns true) but render/warnings must
// surface the active=false distinction.
func usableInactivePriorProbe() *ProbeResult {
	return &ProbeResult{
		State: PriorRecordUsableInactive,
		Record: &PriorRecord{
			SchemaVersion:    PlanSchemaVersion,
			FirewallType:     "csf",
			RecordedAt:       ptrTime(sampleRecordedAt),
			InstallerVersion: "1.100.0",
			ActiveAtInstall:  ptrBool(false),
		},
	}
}

func TestBuildPlan_Remove_Defaults(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), noPriorProbe(), false)
	if p.RequestedMode != ModeRemove {
		t.Errorf("RequestedMode = %q; want %q", p.RequestedMode, ModeRemove)
	}
	if p.TargetAuthority != AuthorityNone {
		t.Errorf("TargetAuthority = %q; want %q (Q2=C default is None)", p.TargetAuthority, AuthorityNone)
	}
	if p.RestoreRequested || p.RestoreAuthorized {
		t.Error("restore flags must be false by default")
	}
}

func TestBuildPlan_Purge_PreservesConfLocal_ArtifactPolicy(t *testing.T) {
	p := BuildPlan(ModePurge, happyClassify(), noPriorProbe(), false)
	if !strings.Contains(p.ArtifactPolicy, "preserve .conf.local") {
		t.Errorf("purge ArtifactPolicy must mention .conf.local preservation (Q3=B); got: %s", p.ArtifactPolicy)
	}
}

func TestBuildPlan_PurgeForceDOC_DescribesConfLocalDelete(t *testing.T) {
	p := BuildPlan(ModePurgeForceDOC, happyClassify(), noPriorProbe(), false)
	if !strings.Contains(p.ArtifactPolicy, "delete .conf.local") {
		t.Errorf("purge+force ArtifactPolicy must describe .conf.local deletion; got: %s", p.ArtifactPolicy)
	}
}

func TestBuildPlan_Restore_UsableRecord_Authorized(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), usablePriorProbe(), true)
	if !p.RestoreAuthorized {
		t.Error("restore must be authorized when prior record is usable AND flag is set (Q4=B)")
	}
	if p.TargetAuthority != CurrentAuthority("ufw") {
		t.Errorf("TargetAuthority = %q; want ufw (restored prior)", p.TargetAuthority)
	}
	// PR-P2-1: UsableActive must surface active=true in the plan.
	if p.PriorActiveAtInstall == nil || !*p.PriorActiveAtInstall {
		t.Errorf("PriorActiveAtInstall must be explicit true for UsableActive prior")
	}
}

// PR-P2-1: UsableInactive is still authorized (record is usable) but
// the plan must surface the active=false distinction AND warn the
// operator that restoration would re-enable a firewall that was not
// active at install time.
func TestBuildPlan_Restore_UsableInactive_AuthorizedButWarned(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), usableInactivePriorProbe(), true)
	if !p.RestoreAuthorized {
		t.Error("restore must be authorized for UsableInactive — inactive is still a usable record")
	}
	if p.PriorActiveAtInstall == nil || *p.PriorActiveAtInstall {
		t.Errorf("PriorActiveAtInstall must be explicit false for UsableInactive prior")
	}
	var haveInactiveWarning bool
	for _, w := range p.Warnings {
		if strings.Contains(w, "NOT active at install time") {
			haveInactiveWarning = true
		}
	}
	if !haveInactiveWarning {
		t.Errorf("plan must warn that restoration re-enables a non-active firewall; got warnings: %v", p.Warnings)
	}
}

func TestBuildPlan_Restore_NoRecord_NotAuthorized(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), noPriorProbe(), true)
	if p.RestoreAuthorized {
		t.Error("restore must NOT be authorized when no prior record exists (Q4=B + §10.2 B-UN-restore-norecord)")
	}
	// A warning must surface for the operator.
	var found bool
	for _, w := range p.Warnings {
		if strings.Contains(w, "no prior-authority record") {
			found = true
		}
	}
	if !found {
		t.Error("plan must warn when restore requested but no record exists; PR-24 will enforce")
	}
}

func TestBuildPlan_Restore_IncompleteRecord_NotAuthorized(t *testing.T) {
	prior := &ProbeResult{State: PriorRecordIncomplete}
	p := BuildPlan(ModeRemove, happyClassify(), prior, true)
	if p.RestoreAuthorized {
		t.Error("restore must NOT be authorized when prior record is incomplete")
	}
	var found bool
	for _, w := range p.Warnings {
		if strings.Contains(w, "incomplete") {
			found = true
		}
	}
	if !found {
		t.Error("plan must warn when restore requested but record is incomplete")
	}
}

// Audit F — the critical semantic edge case for PR-22: with
// --restore-prior-authority set AND PriorRecordIncomplete, the plan
// must satisfy ALL THREE properties:
//
//  1. does NOT promise restoration (TargetAuthority is not the prior
//     firewall type)
//  2. does NOT silently downgrade to AuthorityNone without the operator
//     seeing why (warning + RestoreRequested=true must both surface)
//  3. explicitly reports restore requested but NOT authorized from
//     available evidence
//
// This is the exact contract surface that PR-24 will inherit. Muddy
// semantics here = poisoned contract downstream.
func TestBuildPlan_Restore_IncompleteRecord_SemanticEdge_Audit_F(t *testing.T) {
	prior := &ProbeResult{State: PriorRecordIncomplete}
	p := BuildPlan(ModeRemove, happyClassify(), prior, true)

	// Property 1: no restoration promise.
	if p.TargetAuthority != AuthorityNone {
		t.Errorf("TargetAuthority = %q; incomplete record must NOT promise restoration (Q4=B + audit F)", p.TargetAuthority)
	}

	// Property 2a: restore request is visible (not silent).
	if !p.RestoreRequested {
		t.Error("RestoreRequested must remain true so the operator SEES their request was heard — not silently dropped")
	}
	// Property 2b: not-authorized is also visible.
	if p.RestoreAuthorized {
		t.Error("RestoreAuthorized must be false because the record cannot be trusted")
	}

	// Property 3: warnings explicitly pair "requested" with "not authorized
	// from available evidence". A reader of the plan alone (without
	// reading the code) must see that the request exists but failed
	// authorization, NOT infer silently.
	var explicitWarning string
	for _, w := range p.Warnings {
		if strings.Contains(w, "restore") && strings.Contains(w, "incomplete") {
			explicitWarning = w
		}
	}
	if explicitWarning == "" {
		t.Errorf("plan must have an explicit warning tying 'restore requested' to 'record incomplete'; got warnings: %v", p.Warnings)
	}

	// Rendered output must also carry all three properties in human form
	// so operator audit at read-time catches the edge.
	var buf bytes.Buffer
	p.Render(&buf)
	rendered := buf.String()
	for _, needle := range []string{
		"Restore requested           : yes",
		"Restore authorized          : no",
		"Prior-authority record      : record_incomplete",
	} {
		if !strings.Contains(rendered, needle) {
			t.Errorf("render output missing semantic-edge line %q — operator must see the full picture:\n%s", needle, rendered)
		}
	}
}

// Render output — contract-language structural checks

func TestRender_HasMandatoryFieldsAndScopeBoundary(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), noPriorProbe(), false)
	var buf bytes.Buffer
	p.Render(&buf)
	out := buf.String()

	mustHave := []string{
		"NFTBan Uninstall — Plan",
		"Requested mode",
		"Artifact policy",
		"Current authority",
		"Target authority",
		"Restore requested",
		"Restore authorized",
		"Prior-authority record",
		"Phases that would mutate (NOT IMPLEMENTED in PR-22):",
		"Scope boundary:",
		"Running this command does NOT uninstall nftban",
		// Render wraps the sentence across lines; match a substring that
		// fits within a single printed line.
		"PRs in the v1.100 track must land first",
	}
	for _, needle := range mustHave {
		if !strings.Contains(out, needle) {
			t.Errorf("Render output missing mandatory contract-language element %q", needle)
		}
	}
}

func TestRender_ScopeBoundaryBlock_AlwaysPresent_AllModes(t *testing.T) {
	// The scope-boundary block is MANDATORY regardless of mode; a future
	// change that branches it away for certain modes would violate the
	// PR-22 contract.
	for _, mode := range []Mode{ModeRemove, ModePurge, ModePurgeForceDOC} {
		p := BuildPlan(mode, happyClassify(), noPriorProbe(), false)
		var buf bytes.Buffer
		p.Render(&buf)
		if !strings.Contains(buf.String(), "Scope boundary:") {
			t.Errorf("mode %q: scope-boundary block missing", mode)
		}
	}
}

func TestPlan_JSON_RoundTrip_KeyFields(t *testing.T) {
	p := BuildPlan(ModePurge, happyClassify(), usablePriorProbe(), true)
	data, err := p.JSON()
	if err != nil {
		t.Fatalf("JSON encode: %v", err)
	}
	out := string(data)
	for _, needle := range []string{
		`"schema_version"`,
		`"requested_mode": "purge"`,
		`"restore_requested": true`,
		`"restore_authorized": true`,
		`"prior_state": "record_usable_active"`,
		`"prior_active_at_install": true`,
		`"phases_that_would_mutate"`,
	} {
		if !strings.Contains(out, needle) {
			t.Errorf("JSON output missing %s:\n%s", needle, out)
		}
	}
}

// PR-22B audit item 11 (render ↔ JSON equivalence): prove that core
// facts surface in BOTH human text and JSON. A future drift (render
// grows a line with no JSON backing, or JSON grows a field that's never
// rendered) fails here.
func TestPlan_RenderAndJSON_ExposeSameCoreFacts(t *testing.T) {
	grid := []struct {
		name         string
		mode         Mode
		restore      bool
		priorState   PriorRecordState
		authState    CurrentAuthority
		wantInRender []string
		wantInJSON   []string
	}{
		{
			name:       "remove/no-restore/no-record/nftban",
			mode:       ModeRemove,
			restore:    false,
			priorState: PriorNoRecord,
			authState:  AuthorityNFTBan,
			wantInRender: []string{
				"Requested mode              : remove",
				"Current authority           : nftban",
				"Restore requested           : no",
				"Restore authorized          : no",
				"Prior-authority record      : no_record",
			},
			wantInJSON: []string{
				`"requested_mode": "remove"`,
				`"current_authority": "nftban"`,
				`"restore_requested": false`,
				`"restore_authorized": false`,
				`"prior_state": "no_record"`,
				`"no_mutation_performed": true`,
			},
		},
		{
			name:       "purge/restore-requested/record-incomplete/ambiguous",
			mode:       ModePurge,
			restore:    true,
			priorState: PriorRecordIncomplete,
			authState:  AuthorityAmbiguous,
			wantInRender: []string{
				"Requested mode              : purge",
				"Current authority           : ambiguous",
				"Restore requested           : yes",
				"Restore authorized          : no",
				"Prior-authority record      : record_incomplete",
			},
			wantInJSON: []string{
				`"requested_mode": "purge"`,
				`"current_authority": "ambiguous"`,
				`"restore_requested": true`,
				`"restore_authorized": false`,
				`"prior_state": "record_incomplete"`,
			},
		},
	}
	for _, tc := range grid {
		t.Run(tc.name, func(t *testing.T) {
			auth := &ClassifyResult{State: tc.authState}
			prior := &ProbeResult{State: tc.priorState}
			p := BuildPlan(tc.mode, auth, prior, tc.restore)

			var buf bytes.Buffer
			p.Render(&buf)
			rendered := buf.String()
			for _, needle := range tc.wantInRender {
				if !strings.Contains(rendered, needle) {
					t.Errorf("render missing %q:\n%s", needle, rendered)
				}
			}

			data, err := p.JSON()
			if err != nil {
				t.Fatalf("JSON: %v", err)
			}
			jsonOut := string(data)
			for _, needle := range tc.wantInJSON {
				if !strings.Contains(jsonOut, needle) {
					t.Errorf("JSON missing %q:\n%s", needle, jsonOut)
				}
			}

			// Scope-boundary invariant must appear in BOTH forms.
			if !strings.Contains(rendered, "Scope boundary:") {
				t.Errorf("render missing scope-boundary block")
			}
			if !strings.Contains(jsonOut, `"scope_boundary"`) {
				t.Errorf("JSON missing scope_boundary field")
			}
			if !strings.Contains(jsonOut, `"no_mutation_performed": true`) {
				t.Errorf("JSON missing no_mutation_performed=true invariant")
			}
		})
	}
}
