// =============================================================================
// NFTBan v1.100 PR-22 — Uninstall Scaffold Tests
// =============================================================================
// SPDX-License-Identifier: MPL-2.0
// meta:name="installer-uninstall-test"
// meta:type="test"
// meta:owner="Antonios Voulvoulis <contact@nftban.com>"
// meta:created_date="2026-04-19"
// meta:description="PR-22 scaffold: authority classifier + prior probe + plan render"
// meta:inventory.files="internal/installer/uninstall/uninstall_test.go"
// meta:inventory.binaries=""
// meta:inventory.env_vars=""
// meta:inventory.config_files=""
// meta:inventory.systemd_units=""
// meta:inventory.network=""
// meta:inventory.privileges="none"
// =============================================================================
package uninstall

import (
	"bytes"
	"strings"
	"testing"

	"github.com/itcmsgr/nftban/internal/installer/executor"
	"github.com/itcmsgr/nftban/internal/installer/logging"
)

func newTestLogger() *logging.Logger {
	return logging.New("/dev/null", false)
}

// ---------------------------------------------------------------------------
// Classify — 4-state authority classifier
// ---------------------------------------------------------------------------

func TestClassify_NFTBan(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true
	mock.Services["nftband.service"] = true

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityNFTBan {
		t.Errorf("State = %q; want %q", res.State, AuthorityNFTBan)
	}
	if res.External != "" {
		t.Errorf("External = %q; want empty", res.External)
	}
}

func TestClassify_External_UFW(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Services["ufw"] = true

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityExternal {
		t.Errorf("State = %q; want %q", res.State, AuthorityExternal)
	}
	if res.External != "ufw" {
		t.Errorf("External = %q; want ufw", res.External)
	}
}

func TestClassify_External_Firewalld(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Services["firewalld.service"] = true

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityExternal {
		t.Errorf("State = %q; want %q", res.State, AuthorityExternal)
	}
	if res.External != "firewalld" {
		t.Errorf("External = %q; want firewalld", res.External)
	}
}

func TestClassify_None(t *testing.T) {
	mock := executor.NewMockExecutor()
	// Explicitly mark iptables-save as returning no rules (heuristic < 3).
	mock.RunResults["iptables-save"] = executor.Result{
		ExitCode: 0,
		Stdout:   "# Generated by iptables-save\n*filter\n:INPUT ACCEPT\nCOMMIT\n",
	}

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityNone {
		t.Errorf("State = %q; want %q", res.State, AuthorityNone)
	}
}

func TestClassify_Ambiguous_NFTBanPlusUFW(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true
	mock.Services["nftband.service"] = true
	mock.Services["ufw"] = true

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityAmbiguous {
		t.Errorf("State = %q; want %q (both nftban + ufw present)", res.State, AuthorityAmbiguous)
	}
	if res.External != "ufw" {
		t.Errorf("External = %q; want ufw", res.External)
	}
}

func TestClassify_NoteOnPartialNFTBan(t *testing.T) {
	// ip nftban table present but daemon NOT active → should note the
	// inconsistency but not claim authority.
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true

	res := Classify(mock, newTestLogger())
	// Classification must not be AuthorityNFTBan (daemon is down).
	if res.State == AuthorityNFTBan {
		t.Error("partial nftban should NOT classify as AuthorityNFTBan")
	}
	// A note must surface the partial state.
	var found bool
	for _, n := range res.Notes {
		if strings.Contains(n, "nftband.service inactive") {
			found = true
		}
	}
	if !found {
		t.Error("partial-nftban warning note missing; operator must see the inconsistency")
	}
}

// ---------------------------------------------------------------------------
// Probe — 3-state prior-authority record detector
// ---------------------------------------------------------------------------

func TestProbe_NoRecord(t *testing.T) {
	mock := executor.NewMockExecutor()

	res := Probe(mock, newTestLogger())
	if res.State != PriorNoRecord {
		t.Errorf("State = %q; want %q", res.State, PriorNoRecord)
	}
	if res.Record != nil {
		t.Errorf("Record should be nil for NoRecord, got %+v", res.Record)
	}
}

func TestProbe_RecordUsable(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"1.100.0","firewall_type":"ufw","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordUsable {
		t.Errorf("State = %q; want %q", res.State, PriorRecordUsable)
	}
	if res.Record == nil {
		t.Fatal("Record must be populated for Usable state")
	}
	if res.Record.FirewallType != "ufw" {
		t.Errorf("FirewallType = %q; want ufw", res.Record.FirewallType)
	}
}

func TestProbe_RecordIncomplete_MalformedJSON(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{not valid json`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (malformed JSON)", res.State, PriorRecordIncomplete)
	}
}

func TestProbe_RecordIncomplete_MissingFirewallType(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"1.100.0","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (missing firewall_type)", res.State, PriorRecordIncomplete)
	}
}

func TestProbe_RecordIncomplete_UnknownFirewallType(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"1.100.0","firewall_type":"pf","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (unknown firewall_type)", res.State, PriorRecordIncomplete)
	}
}

func TestProbe_RecordIncomplete_SchemaMismatch(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"0.9.0","firewall_type":"ufw","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (schema mismatch — no migration in v1.100)", res.State, PriorRecordIncomplete)
	}
}

// ---------------------------------------------------------------------------
// BuildPlan + Render — contract-language output
// ---------------------------------------------------------------------------

func happyClassify() *ClassifyResult {
	return &ClassifyResult{State: AuthorityNFTBan}
}

func noPriorProbe() *ProbeResult {
	return &ProbeResult{State: PriorNoRecord}
}

func usablePriorProbe() *ProbeResult {
	return &ProbeResult{
		State:  PriorRecordUsable,
		Record: &PriorRecord{SchemaVersion: PlanSchemaVersion, FirewallType: "ufw", ActiveAtInstall: true},
	}
}

func TestBuildPlan_Remove_Defaults(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), noPriorProbe(), false)
	if p.RequestedMode != ModeRemove {
		t.Errorf("RequestedMode = %q; want %q", p.RequestedMode, ModeRemove)
	}
	if p.TargetAuthority != AuthorityNone {
		t.Errorf("TargetAuthority = %q; want %q (Q2=C default is None)", p.TargetAuthority, AuthorityNone)
	}
	if p.RestoreRequested || p.RestoreAuthorized {
		t.Error("restore flags must be false by default")
	}
}

func TestBuildPlan_Purge_PreservesConfLocal_ArtifactPolicy(t *testing.T) {
	p := BuildPlan(ModePurge, happyClassify(), noPriorProbe(), false)
	if !strings.Contains(p.ArtifactPolicy, "preserve .conf.local") {
		t.Errorf("purge ArtifactPolicy must mention .conf.local preservation (Q3=B); got: %s", p.ArtifactPolicy)
	}
}

func TestBuildPlan_PurgeForceDOC_DescribesConfLocalDelete(t *testing.T) {
	p := BuildPlan(ModePurgeForceDOC, happyClassify(), noPriorProbe(), false)
	if !strings.Contains(p.ArtifactPolicy, "delete .conf.local") {
		t.Errorf("purge+force ArtifactPolicy must describe .conf.local deletion; got: %s", p.ArtifactPolicy)
	}
}

func TestBuildPlan_Restore_UsableRecord_Authorized(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), usablePriorProbe(), true)
	if !p.RestoreAuthorized {
		t.Error("restore must be authorized when prior record is usable AND flag is set (Q4=B)")
	}
	if p.TargetAuthority != CurrentAuthority("ufw") {
		t.Errorf("TargetAuthority = %q; want ufw (restored prior)", p.TargetAuthority)
	}
}

func TestBuildPlan_Restore_NoRecord_NotAuthorized(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), noPriorProbe(), true)
	if p.RestoreAuthorized {
		t.Error("restore must NOT be authorized when no prior record exists (Q4=B + §10.2 B-UN-restore-norecord)")
	}
	// A warning must surface for the operator.
	var found bool
	for _, w := range p.Warnings {
		if strings.Contains(w, "no prior-authority record") {
			found = true
		}
	}
	if !found {
		t.Error("plan must warn when restore requested but no record exists; PR-24 will enforce")
	}
}

func TestBuildPlan_Restore_IncompleteRecord_NotAuthorized(t *testing.T) {
	prior := &ProbeResult{State: PriorRecordIncomplete}
	p := BuildPlan(ModeRemove, happyClassify(), prior, true)
	if p.RestoreAuthorized {
		t.Error("restore must NOT be authorized when prior record is incomplete")
	}
	var found bool
	for _, w := range p.Warnings {
		if strings.Contains(w, "incomplete") {
			found = true
		}
	}
	if !found {
		t.Error("plan must warn when restore requested but record is incomplete")
	}
}

// Render output — contract-language structural checks

func TestRender_HasMandatoryFieldsAndScopeBoundary(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), noPriorProbe(), false)
	var buf bytes.Buffer
	p.Render(&buf)
	out := buf.String()

	mustHave := []string{
		"NFTBan Uninstall — Plan",
		"Requested mode",
		"Artifact policy",
		"Current authority",
		"Target authority",
		"Restore requested",
		"Restore authorized",
		"Prior-authority record",
		"Phases that would mutate (NOT IMPLEMENTED in PR-22):",
		"Scope boundary:",
		"Running this command does NOT uninstall nftban",
		"later PRs in the v1.100 track must land first",
	}
	for _, needle := range mustHave {
		if !strings.Contains(out, needle) {
			t.Errorf("Render output missing mandatory contract-language element %q", needle)
		}
	}
}

func TestRender_ScopeBoundaryBlock_AlwaysPresent_AllModes(t *testing.T) {
	// The scope-boundary block is MANDATORY regardless of mode; a future
	// change that branches it away for certain modes would violate the
	// PR-22 contract.
	for _, mode := range []Mode{ModeRemove, ModePurge, ModePurgeForceDOC} {
		p := BuildPlan(mode, happyClassify(), noPriorProbe(), false)
		var buf bytes.Buffer
		p.Render(&buf)
		if !strings.Contains(buf.String(), "Scope boundary:") {
			t.Errorf("mode %q: scope-boundary block missing", mode)
		}
	}
}

func TestPlan_JSON_RoundTrip_KeyFields(t *testing.T) {
	p := BuildPlan(ModePurge, happyClassify(), usablePriorProbe(), true)
	data, err := p.JSON()
	if err != nil {
		t.Fatalf("JSON encode: %v", err)
	}
	out := string(data)
	for _, needle := range []string{
		`"schema_version"`,
		`"requested_mode": "purge"`,
		`"restore_requested": true`,
		`"restore_authorized": true`,
		`"prior_state": "record_usable"`,
		`"phases_that_would_mutate"`,
	} {
		if !strings.Contains(out, needle) {
			t.Errorf("JSON output missing %s:\n%s", needle, out)
		}
	}
}
