// =============================================================================
// NFTBan v1.100 PR-22 — Uninstall Scaffold Tests
// =============================================================================
// SPDX-License-Identifier: MPL-2.0
// meta:name="installer-uninstall-test"
// meta:type="test"
// meta:owner="Antonios Voulvoulis <contact@nftban.com>"
// meta:created_date="2026-04-19"
// meta:description="PR-22 scaffold: authority classifier + prior probe + plan render"
// meta:inventory.files="internal/installer/uninstall/uninstall_test.go"
// meta:inventory.binaries=""
// meta:inventory.env_vars=""
// meta:inventory.config_files=""
// meta:inventory.systemd_units=""
// meta:inventory.network=""
// meta:inventory.privileges="none"
// =============================================================================
package uninstall

import (
	"bytes"
	"strings"
	"testing"

	"github.com/itcmsgr/nftban/internal/installer/executor"
	"github.com/itcmsgr/nftban/internal/installer/logging"
)

func newTestLogger() *logging.Logger {
	return logging.New("/dev/null", false)
}

// ---------------------------------------------------------------------------
// Classify — 4-state authority classifier
// ---------------------------------------------------------------------------

func TestClassify_NFTBan(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true
	mock.Services["nftband.service"] = true

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityNFTBan {
		t.Errorf("State = %q; want %q", res.State, AuthorityNFTBan)
	}
	if res.External != "" {
		t.Errorf("External = %q; want empty", res.External)
	}
}

func TestClassify_External_UFW(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Services["ufw"] = true

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityExternal {
		t.Errorf("State = %q; want %q", res.State, AuthorityExternal)
	}
	if res.External != "ufw" {
		t.Errorf("External = %q; want ufw", res.External)
	}
}

func TestClassify_External_Firewalld(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Services["firewalld.service"] = true

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityExternal {
		t.Errorf("State = %q; want %q", res.State, AuthorityExternal)
	}
	if res.External != "firewalld" {
		t.Errorf("External = %q; want firewalld", res.External)
	}
}

func TestClassify_None(t *testing.T) {
	mock := executor.NewMockExecutor()
	// Explicitly mark iptables-save as returning no rules (heuristic < 3).
	mock.RunResults["iptables-save"] = executor.Result{
		ExitCode: 0,
		Stdout:   "# Generated by iptables-save\n*filter\n:INPUT ACCEPT\nCOMMIT\n",
	}

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityNone {
		t.Errorf("State = %q; want %q", res.State, AuthorityNone)
	}
}

func TestClassify_Ambiguous_NFTBanPlusUFW(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true
	mock.Services["nftband.service"] = true
	mock.Services["ufw"] = true

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityAmbiguous {
		t.Errorf("State = %q; want %q (both nftban + ufw present)", res.State, AuthorityAmbiguous)
	}
	if res.External != "ufw" {
		t.Errorf("External = %q; want ufw", res.External)
	}
}

func TestClassify_NoteOnPartialNFTBan(t *testing.T) {
	// ip nftban table present but daemon NOT active → should note the
	// inconsistency but not claim authority.
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true

	res := Classify(mock, newTestLogger())
	// Classification must not be AuthorityNFTBan (daemon is down).
	if res.State == AuthorityNFTBan {
		t.Error("partial nftban should NOT classify as AuthorityNFTBan")
	}
	// A note must surface the partial state.
	var found bool
	for _, n := range res.Notes {
		if strings.Contains(n, "nftband.service inactive") {
			found = true
		}
	}
	if !found {
		t.Error("partial-nftban warning note missing; operator must see the inconsistency")
	}
}

// Audit D.1 regression guard: partial nftban presence MUST prefer
// ambiguous/degraded over a false "no authority" claim. The reviewer's
// concern: later PRs will build mutation decisions on top of this
// detector, so any overstatement here poisons the whole chain.
func TestClassify_PartialNFTBan_WithExternal_IsAmbiguous(t *testing.T) {
	// ip nftban table present + daemon DOWN + UFW active = the classic
	// half-installed / mid-transition state. Classifier must not silently
	// claim "external is authoritative" because the nftban table is
	// still sitting in the kernel.
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true   // table still in kernel
	mock.Services["nftband.service"] = false // daemon inactive
	mock.Services["ufw"] = true               // external present

	res := Classify(mock, newTestLogger())
	if res.State == AuthorityExternal {
		t.Errorf("partial-nftban + external MUST NOT claim external authority outright; nftban table in kernel means state is ambiguous. got %q", res.State)
	}
	// The notes should surface BOTH the partial-nftban issue AND the
	// external-firewall presence so the operator has full context.
	haveNftbanNote := false
	haveExternalNote := false
	for _, n := range res.Notes {
		if strings.Contains(n, "nftband.service inactive") {
			haveNftbanNote = true
		}
		if strings.Contains(n, "ufw") || strings.Contains(n, "external") {
			haveExternalNote = true
		}
	}
	if !haveNftbanNote {
		t.Error("partial-nftban note missing — operator cannot see the half-installed state")
	}
	if !haveExternalNote {
		t.Error("external-firewall note missing — operator cannot see the ambient firewall")
	}
}

// PR-22A audit fix: partial nftban WITHOUT external must classify as
// Ambiguous, NOT None. The previous switch fell through to the
// !nftbanPresent && !extPresent case and returned AuthorityNone while
// the nftban table was still in the kernel — a silent false-negative
// that would teach PR-23's release logic to skip cleanup of the orphan
// table. This test is the regression guard.
func TestClassify_PartialNFTBan_NoExternal_IsAmbiguous(t *testing.T) {
	// Table present in kernel, daemon down, no external firewall.
	mock := executor.NewMockExecutor()
	mock.NftTables["ip:nftban"] = true
	mock.Services["nftband.service"] = false
	mock.RunResults["iptables-save"] = executor.Result{
		ExitCode: 0,
		Stdout:   "# Generated by iptables-save\n*filter\n:INPUT ACCEPT\nCOMMIT\n",
	}

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityAmbiguous {
		t.Errorf("partial-nftban + no external MUST classify as Ambiguous; kernel still holds nftban table. got %q", res.State)
	}
	var haveAmbigNote bool
	for _, n := range res.Notes {
		if strings.Contains(n, "indeterminate transition") {
			haveAmbigNote = true
		}
	}
	if !haveAmbigNote {
		t.Errorf("ambiguous-state note missing — operator must see why classification is ambiguous; got notes: %v", res.Notes)
	}
}

// Symmetric case for the other partial shape: daemon up without the
// nftban table. Same reasoning — authority is ambiguous, not None.
func TestClassify_DaemonUpNoTable_NoExternal_IsAmbiguous(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Services["nftband.service"] = true
	mock.RunResults["iptables-save"] = executor.Result{
		ExitCode: 0,
		Stdout:   "# Generated by iptables-save\n*filter\n:INPUT ACCEPT\nCOMMIT\n",
	}

	res := Classify(mock, newTestLogger())
	if res.State != AuthorityAmbiguous {
		t.Errorf("daemon-up-no-table + no external MUST classify as Ambiguous. got %q", res.State)
	}
}

// ---------------------------------------------------------------------------
// Probe — 3-state prior-authority record detector
// ---------------------------------------------------------------------------

func TestProbe_NoRecord(t *testing.T) {
	mock := executor.NewMockExecutor()

	res := Probe(mock, newTestLogger())
	if res.State != PriorNoRecord {
		t.Errorf("State = %q; want %q", res.State, PriorNoRecord)
	}
	if res.Record != nil {
		t.Errorf("Record should be nil for NoRecord, got %+v", res.Record)
	}
}

func TestProbe_RecordUsable(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"1.100.0","firewall_type":"ufw","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordUsable {
		t.Errorf("State = %q; want %q", res.State, PriorRecordUsable)
	}
	if res.Record == nil {
		t.Fatal("Record must be populated for Usable state")
	}
	if res.Record.FirewallType != "ufw" {
		t.Errorf("FirewallType = %q; want ufw", res.Record.FirewallType)
	}
}

func TestProbe_RecordIncomplete_MalformedJSON(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{not valid json`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (malformed JSON)", res.State, PriorRecordIncomplete)
	}
}

func TestProbe_RecordIncomplete_MissingFirewallType(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"1.100.0","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (missing firewall_type)", res.State, PriorRecordIncomplete)
	}
}

func TestProbe_RecordIncomplete_UnknownFirewallType(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"1.100.0","firewall_type":"pf","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (unknown firewall_type)", res.State, PriorRecordIncomplete)
	}
}

func TestProbe_RecordIncomplete_SchemaMismatch(t *testing.T) {
	mock := executor.NewMockExecutor()
	mock.Files[PriorAuthorityPath] = []byte(`{"schema_version":"0.9.0","firewall_type":"ufw","active_at_install":true}`)

	res := Probe(mock, newTestLogger())
	if res.State != PriorRecordIncomplete {
		t.Errorf("State = %q; want %q (schema mismatch — no migration in v1.100)", res.State, PriorRecordIncomplete)
	}
}

// ---------------------------------------------------------------------------
// BuildPlan + Render — contract-language output
// ---------------------------------------------------------------------------

func happyClassify() *ClassifyResult {
	return &ClassifyResult{State: AuthorityNFTBan}
}

func noPriorProbe() *ProbeResult {
	return &ProbeResult{State: PriorNoRecord}
}

func usablePriorProbe() *ProbeResult {
	return &ProbeResult{
		State:  PriorRecordUsable,
		Record: &PriorRecord{SchemaVersion: PlanSchemaVersion, FirewallType: "ufw", ActiveAtInstall: true},
	}
}

func TestBuildPlan_Remove_Defaults(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), noPriorProbe(), false)
	if p.RequestedMode != ModeRemove {
		t.Errorf("RequestedMode = %q; want %q", p.RequestedMode, ModeRemove)
	}
	if p.TargetAuthority != AuthorityNone {
		t.Errorf("TargetAuthority = %q; want %q (Q2=C default is None)", p.TargetAuthority, AuthorityNone)
	}
	if p.RestoreRequested || p.RestoreAuthorized {
		t.Error("restore flags must be false by default")
	}
}

func TestBuildPlan_Purge_PreservesConfLocal_ArtifactPolicy(t *testing.T) {
	p := BuildPlan(ModePurge, happyClassify(), noPriorProbe(), false)
	if !strings.Contains(p.ArtifactPolicy, "preserve .conf.local") {
		t.Errorf("purge ArtifactPolicy must mention .conf.local preservation (Q3=B); got: %s", p.ArtifactPolicy)
	}
}

func TestBuildPlan_PurgeForceDOC_DescribesConfLocalDelete(t *testing.T) {
	p := BuildPlan(ModePurgeForceDOC, happyClassify(), noPriorProbe(), false)
	if !strings.Contains(p.ArtifactPolicy, "delete .conf.local") {
		t.Errorf("purge+force ArtifactPolicy must describe .conf.local deletion; got: %s", p.ArtifactPolicy)
	}
}

func TestBuildPlan_Restore_UsableRecord_Authorized(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), usablePriorProbe(), true)
	if !p.RestoreAuthorized {
		t.Error("restore must be authorized when prior record is usable AND flag is set (Q4=B)")
	}
	if p.TargetAuthority != CurrentAuthority("ufw") {
		t.Errorf("TargetAuthority = %q; want ufw (restored prior)", p.TargetAuthority)
	}
}

func TestBuildPlan_Restore_NoRecord_NotAuthorized(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), noPriorProbe(), true)
	if p.RestoreAuthorized {
		t.Error("restore must NOT be authorized when no prior record exists (Q4=B + §10.2 B-UN-restore-norecord)")
	}
	// A warning must surface for the operator.
	var found bool
	for _, w := range p.Warnings {
		if strings.Contains(w, "no prior-authority record") {
			found = true
		}
	}
	if !found {
		t.Error("plan must warn when restore requested but no record exists; PR-24 will enforce")
	}
}

func TestBuildPlan_Restore_IncompleteRecord_NotAuthorized(t *testing.T) {
	prior := &ProbeResult{State: PriorRecordIncomplete}
	p := BuildPlan(ModeRemove, happyClassify(), prior, true)
	if p.RestoreAuthorized {
		t.Error("restore must NOT be authorized when prior record is incomplete")
	}
	var found bool
	for _, w := range p.Warnings {
		if strings.Contains(w, "incomplete") {
			found = true
		}
	}
	if !found {
		t.Error("plan must warn when restore requested but record is incomplete")
	}
}

// Audit F — the critical semantic edge case for PR-22: with
// --restore-prior-authority set AND PriorRecordIncomplete, the plan
// must satisfy ALL THREE properties:
//
//  1. does NOT promise restoration (TargetAuthority is not the prior
//     firewall type)
//  2. does NOT silently downgrade to AuthorityNone without the operator
//     seeing why (warning + RestoreRequested=true must both surface)
//  3. explicitly reports restore requested but NOT authorized from
//     available evidence
//
// This is the exact contract surface that PR-24 will inherit. Muddy
// semantics here = poisoned contract downstream.
func TestBuildPlan_Restore_IncompleteRecord_SemanticEdge_Audit_F(t *testing.T) {
	prior := &ProbeResult{State: PriorRecordIncomplete}
	p := BuildPlan(ModeRemove, happyClassify(), prior, true)

	// Property 1: no restoration promise.
	if p.TargetAuthority != AuthorityNone {
		t.Errorf("TargetAuthority = %q; incomplete record must NOT promise restoration (Q4=B + audit F)", p.TargetAuthority)
	}

	// Property 2a: restore request is visible (not silent).
	if !p.RestoreRequested {
		t.Error("RestoreRequested must remain true so the operator SEES their request was heard — not silently dropped")
	}
	// Property 2b: not-authorized is also visible.
	if p.RestoreAuthorized {
		t.Error("RestoreAuthorized must be false because the record cannot be trusted")
	}

	// Property 3: warnings explicitly pair "requested" with "not authorized
	// from available evidence". A reader of the plan alone (without
	// reading the code) must see that the request exists but failed
	// authorization, NOT infer silently.
	var explicitWarning string
	for _, w := range p.Warnings {
		if strings.Contains(w, "restore") && strings.Contains(w, "incomplete") {
			explicitWarning = w
		}
	}
	if explicitWarning == "" {
		t.Errorf("plan must have an explicit warning tying 'restore requested' to 'record incomplete'; got warnings: %v", p.Warnings)
	}

	// Rendered output must also carry all three properties in human form
	// so operator audit at read-time catches the edge.
	var buf bytes.Buffer
	p.Render(&buf)
	rendered := buf.String()
	for _, needle := range []string{
		"Restore requested           : yes",
		"Restore authorized          : no",
		"Prior-authority record      : record_incomplete",
	} {
		if !strings.Contains(rendered, needle) {
			t.Errorf("render output missing semantic-edge line %q — operator must see the full picture:\n%s", needle, rendered)
		}
	}
}

// Render output — contract-language structural checks

func TestRender_HasMandatoryFieldsAndScopeBoundary(t *testing.T) {
	p := BuildPlan(ModeRemove, happyClassify(), noPriorProbe(), false)
	var buf bytes.Buffer
	p.Render(&buf)
	out := buf.String()

	mustHave := []string{
		"NFTBan Uninstall — Plan",
		"Requested mode",
		"Artifact policy",
		"Current authority",
		"Target authority",
		"Restore requested",
		"Restore authorized",
		"Prior-authority record",
		"Phases that would mutate (NOT IMPLEMENTED in PR-22):",
		"Scope boundary:",
		"Running this command does NOT uninstall nftban",
		// Render wraps the sentence across lines; match a substring that
		// fits within a single printed line.
		"PRs in the v1.100 track must land first",
	}
	for _, needle := range mustHave {
		if !strings.Contains(out, needle) {
			t.Errorf("Render output missing mandatory contract-language element %q", needle)
		}
	}
}

func TestRender_ScopeBoundaryBlock_AlwaysPresent_AllModes(t *testing.T) {
	// The scope-boundary block is MANDATORY regardless of mode; a future
	// change that branches it away for certain modes would violate the
	// PR-22 contract.
	for _, mode := range []Mode{ModeRemove, ModePurge, ModePurgeForceDOC} {
		p := BuildPlan(mode, happyClassify(), noPriorProbe(), false)
		var buf bytes.Buffer
		p.Render(&buf)
		if !strings.Contains(buf.String(), "Scope boundary:") {
			t.Errorf("mode %q: scope-boundary block missing", mode)
		}
	}
}

func TestPlan_JSON_RoundTrip_KeyFields(t *testing.T) {
	p := BuildPlan(ModePurge, happyClassify(), usablePriorProbe(), true)
	data, err := p.JSON()
	if err != nil {
		t.Fatalf("JSON encode: %v", err)
	}
	out := string(data)
	for _, needle := range []string{
		`"schema_version"`,
		`"requested_mode": "purge"`,
		`"restore_requested": true`,
		`"restore_authorized": true`,
		`"prior_state": "record_usable"`,
		`"phases_that_would_mutate"`,
	} {
		if !strings.Contains(out, needle) {
			t.Errorf("JSON output missing %s:\n%s", needle, out)
		}
	}
}
