// =============================================================================
// NFTBan v1.100 PR-P2-2 — Unified External-Firewall Detection Tests
// =============================================================================
// SPDX-License-Identifier: MPL-2.0
// meta:name="installer-extfw-detect-test"
// meta:type="test"
// meta:owner="Antonios Voulvoulis <contact@nftban.com>"
// meta:created_date="2026-04-20"
// meta:description="Unit tests for unified external-firewall detection"
// meta:inventory.files="internal/installer/extfw/detect_test.go"
// meta:inventory.binaries=""
// meta:inventory.env_vars=""
// meta:inventory.config_files=""
// meta:inventory.systemd_units=""
// meta:inventory.network=""
// meta:inventory.privileges="none"
// =============================================================================
package extfw

import (
	"testing"

	"github.com/itcmsgr/nftban/internal/installer/executor"
	"github.com/itcmsgr/nftban/internal/installer/logging"
)

func newTestLogger() *logging.Logger { return logging.New("/dev/null", false) }

// emptyIptablesSave returns the minimal iptables-save output a clean
// host produces (preamble only, below the 3-rule threshold).
func emptyIptablesSave() executor.Result {
	return executor.Result{
		ExitCode: 0,
		Stdout:   "# Generated by iptables-save\n*filter\n:INPUT ACCEPT\nCOMMIT\n",
	}
}

// cleanMock returns a MockExecutor that reports "no firewall of any
// kind." Tests that want to add a single firewall build on this base.
func cleanMock() *executor.MockExecutor {
	m := executor.NewMockExecutor()
	m.RunResults["iptables-save"] = emptyIptablesSave()
	m.ExistingCommands["nft"] = true
	m.RunResults["nft:list:tables"] = executor.Result{ExitCode: 0, Stdout: ""}
	return m
}

// ─────────────────────────────────────────────────────────────────────────────
// Single-firewall cases — one signal, one result
// ─────────────────────────────────────────────────────────────────────────────

func TestDetect_None(t *testing.T) {
	res := Detect(cleanMock(), newTestLogger())
	if res.Authoritative != NameNone {
		t.Errorf("Authoritative = %q; want NameNone on a clean host", res.Authoritative)
	}
	if res.Ambiguous {
		t.Error("Ambiguous must be false on a clean host")
	}
	if len(res.Active) != 0 {
		t.Errorf("Active must be empty on a clean host; got %v", res.Active)
	}
}

func TestDetect_UFW_Alone(t *testing.T) {
	m := cleanMock()
	m.Services["ufw.service"] = true

	res := Detect(m, newTestLogger())
	if res.Authoritative != NameUFW {
		t.Errorf("Authoritative = %q; want ufw", res.Authoritative)
	}
	if res.Ambiguous {
		t.Error("single firewall must not be Ambiguous")
	}
}

func TestDetect_Firewalld_Alone_BothSignals(t *testing.T) {
	// Service signal
	m := cleanMock()
	m.Services["firewalld.service"] = true
	res := Detect(m, newTestLogger())
	if res.Authoritative != NameFirewalld {
		t.Errorf("Authoritative = %q; want firewalld (service)", res.Authoritative)
	}

	// Ghost-table signal (without service)
	m2 := cleanMock()
	m2.RunResults["nft:list:tables"] = executor.Result{ExitCode: 0, Stdout: "table inet firewalld\n"}
	res2 := Detect(m2, newTestLogger())
	if res2.Authoritative != NameFirewalld {
		t.Errorf("Authoritative = %q; want firewalld (ghost table)", res2.Authoritative)
	}
}

func TestDetect_Iptables_AllThreeSignals(t *testing.T) {
	// Service signal
	m := cleanMock()
	m.Services["iptables.service"] = true
	if res := Detect(m, newTestLogger()); res.Authoritative != NameIptables {
		t.Errorf("service: Authoritative = %q; want iptables", res.Authoritative)
	}

	// Ghost-table signal (filter table, common iptables-nft case)
	m2 := cleanMock()
	m2.RunResults["nft:list:tables"] = executor.Result{ExitCode: 0, Stdout: "table ip filter\n"}
	if res := Detect(m2, newTestLogger()); res.Authoritative != NameIptables {
		t.Errorf("ghost-table: Authoritative = %q; want iptables", res.Authoritative)
	}

	// Active-rules signal (iptables-save)
	m3 := cleanMock()
	m3.RunResults["iptables-save"] = executor.Result{
		ExitCode: 0,
		Stdout:   "# Generated\n*filter\n:INPUT ACCEPT\n-A INPUT -j ACCEPT\n-A INPUT -p tcp --dport 22 -j ACCEPT\n-A INPUT -p tcp --dport 80 -j ACCEPT\nCOMMIT\n",
	}
	if res := Detect(m3, newTestLogger()); res.Authoritative != NameIptables {
		t.Errorf("iptables-save: Authoritative = %q; want iptables", res.Authoritative)
	}
}

// PR-P2-2 Option A RESOLUTION: /etc/csf/csf.conf alone (no running
// service) must produce CSF=active across ALL callers. This test is
// the locked regression guard for the unification decision. Pre-PR-P2-2
// the install side ignored the config-file signal; after PR-P2-2 every
// caller sees the same answer.
func TestDetect_CSF_ConfigFileOnly(t *testing.T) {
	m := cleanMock()
	m.Files["/etc/csf/csf.conf"] = []byte("# csf config stub for test\n")
	// Neither csf.service nor lfd.service active — config-only remnant.

	res := Detect(m, newTestLogger())
	if res.Authoritative != NameCSF {
		t.Errorf("Authoritative = %q; want csf (config-file-only remnant must be detected — Option A)", res.Authoritative)
	}
	if res.Ambiguous {
		t.Error("single CSF signal must not be Ambiguous")
	}
	// The observation must carry the config-file source so consumers
	// that care (e.g. future DisableConflicts branch) can distinguish
	// from a live-service detection.
	var haveConfigObs bool
	for _, o := range res.Observations {
		if o.Name == NameCSF && o.Source == SourceConfigFile {
			haveConfigObs = true
		}
	}
	if !haveConfigObs {
		t.Errorf("CSF config-file observation missing; got Observations=%+v", res.Observations)
	}
}

func TestDetect_CSF_BothServicesActive(t *testing.T) {
	m := cleanMock()
	m.Services["csf.service"] = true
	m.Services["lfd.service"] = true

	res := Detect(m, newTestLogger())
	if res.Authoritative != NameCSF {
		t.Errorf("Authoritative = %q; want csf", res.Authoritative)
	}
	// Two observations (one per unit) — DisableConflicts relies on
	// seeing both units so it can stop+disable+mask each.
	var csfUnits int
	for _, o := range res.Observations {
		if o.Name == NameCSF && o.Source == SourceService {
			csfUnits++
		}
	}
	if csfUnits != 2 {
		t.Errorf("expected 2 CSF service observations (csf + lfd); got %d", csfUnits)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Multi-firewall case — MUST be Ambiguous, no silent collapse
// ─────────────────────────────────────────────────────────────────────────────

// PR-P2-2 hard rule: multiple active firewalls do NOT collapse via
// precedence. The detector surfaces Ambiguous and the caller decides
// how to handle it.
func TestDetect_MultipleActive_IsAmbiguous_NoSilentCollapse(t *testing.T) {
	m := cleanMock()
	m.Services["ufw.service"] = true
	m.Services["firewalld.service"] = true // should NOT silently lose to ufw

	res := Detect(m, newTestLogger())
	if !res.Ambiguous {
		t.Error("multi-active host MUST be Ambiguous; detector is collapsing via precedence")
	}
	if res.Authoritative != NameNone {
		t.Errorf("Authoritative = %q on multi-active host; must be NameNone when Ambiguous", res.Authoritative)
	}
	if len(res.Active) != 2 {
		t.Errorf("Active list should have 2 entries; got %v", res.Active)
	}
	// Active list must be in locked precedence order.
	if res.Active[0] != NameUFW || res.Active[1] != NameFirewalld {
		t.Errorf("Active not in precedence order; got %v, want [ufw firewalld]", res.Active)
	}
}

func TestDetect_AllFourActive_IsAmbiguous(t *testing.T) {
	m := cleanMock()
	m.Services["ufw.service"] = true
	m.Services["firewalld.service"] = true
	m.Services["iptables.service"] = true
	m.Services["csf.service"] = true

	res := Detect(m, newTestLogger())
	if !res.Ambiguous {
		t.Error("4-way multi-active must be Ambiguous")
	}
	if len(res.Active) != 4 {
		t.Errorf("Active should have all 4 names; got %v", res.Active)
	}
	// Locked precedence order must be preserved.
	want := []Name{NameUFW, NameFirewalld, NameIptables, NameCSF}
	for i, w := range want {
		if res.Active[i] != w {
			t.Errorf("Active[%d] = %q; want %q (precedence order)", i, res.Active[i], w)
		}
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Precedence + same-firewall multi-signal coalescing
// ─────────────────────────────────────────────────────────────────────────────

// Multiple signals for the SAME firewall do NOT trigger Ambiguous —
// they agree, so the result is the single firewall. Only DIFFERENT
// firewalls triggering simultaneously count as ambiguous.
func TestDetect_SameFirewallMultiSignal_IsNotAmbiguous(t *testing.T) {
	m := cleanMock()
	m.Services["csf.service"] = true
	m.Services["lfd.service"] = true
	m.Files["/etc/csf/csf.conf"] = []byte("# config\n")
	// Three signals, all saying CSF.

	res := Detect(m, newTestLogger())
	if res.Ambiguous {
		t.Error("same-firewall multi-signal must NOT be Ambiguous")
	}
	if res.Authoritative != NameCSF {
		t.Errorf("Authoritative = %q; want csf (all signals agree)", res.Authoritative)
	}
	if len(res.Observations) < 3 {
		t.Errorf("expected ≥3 CSF observations; got %d", len(res.Observations))
	}
}

// Precedence lock test: with only two distinct firewalls active, the
// Active list must show them in the frozen order. This is the
// regression guard for "precedence changes unintentionally."
func TestDetect_PrecedenceOrder_Frozen(t *testing.T) {
	m := cleanMock()
	// Intentionally set in reverse of precedence order to prove the
	// result is order-independent of mock setup.
	m.Services["csf.service"] = true
	m.Services["ufw.service"] = true

	res := Detect(m, newTestLogger())
	if !res.Ambiguous {
		t.Fatal("two distinct firewalls must be Ambiguous")
	}
	if res.Active[0] != NameUFW || res.Active[1] != NameCSF {
		t.Errorf("Active = %v; want [ufw csf] per locked precedence ufw→firewalld→iptables→csf", res.Active)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// DisplayName legacy behavior (iptables vs iptables-nft)
// ─────────────────────────────────────────────────────────────────────────────

func TestObservation_DisplayName_IptablesGhostTable(t *testing.T) {
	o := Observation{Name: NameIptables, Source: SourceGhostTable}
	if got := o.DisplayName(); got != "iptables-nft" {
		t.Errorf("DisplayName() = %q; want iptables-nft (ghost-table source)", got)
	}
	// Service source → plain "iptables".
	o2 := Observation{Name: NameIptables, Source: SourceService}
	if got := o2.DisplayName(); got != "iptables" {
		t.Errorf("DisplayName() = %q; want iptables (service source)", got)
	}
}

func TestObservation_DisplayName_Uppercase(t *testing.T) {
	if got := (Observation{Name: NameUFW, Source: SourceService}.DisplayName()); got != "UFW" {
		t.Errorf("UFW DisplayName = %q", got)
	}
	if got := (Observation{Name: NameCSF, Source: SourceConfigFile}.DisplayName()); got != "CSF" {
		t.Errorf("CSF DisplayName = %q", got)
	}
}
