[Definition]
actionstart =
actionstop =
actioncheck =
actionban = /bin/bash -c 'echo "$(date "+%%Y-%%m-%%d %%H:%%M:%%S") - Jail: <name> - Banned IP: <ip> - Banned for: <bantime> seconds - Expires at: $(date -d "@$(( $(date +%%s) + <bantime> ))" "+%%Y-%%m-%%d %%H:%%M:%%S")" >> /var/log/nftban/nftban-fail2ban.log'
actionunban =

